// Code generated by go run ./cmd/tsgen; DO NOT EDIT.
// Regenerate with: make generate-ts
//
// TypeScript mirrors of the Go response structs the web UI consumes — one per
// entry in cmd/tsgen's manifest, generated from the Go source so the two
// cannot drift (`make check-ts` fails CI when they do). Field names come from
// the `json` tags; `omitempty`/`omitzero` makes a field optional; a pointer
// without either is `| null`; Go doc comments are carried over verbatim.
// See cmd/tsgen/main.go for the full rendering rules and their limits.

/**
 * sseEnvelope is the JSON shape streamed to each SSE client.
 *
 * Generated from Go `router.sseEnvelope` (internal/router/events.go).
 */
export interface StreamEvent {
  type: string
  time: string
  source: string
  /**
   * ResourceARN is the ARN of the event's primary resource, when known —
   * see events.Event.ResourceARN. Omitted when empty so older/simpler
   * consumers see no shape change.
   */
  resourceArn?: string
  /**
   * RequestID is the API call this event was published under, when known —
   * see events.Event.RequestID. Omitted when empty, both so older consumers
   * see no shape change and so a client can tell "not caused by a request"
   * from "caused by a request we could not name".
   */
  requestId?: string
  payload: unknown
}

/**
 * metricsSnapshot is the JSON body returned by GET /_overcast/metrics.
 * Exposes safe, read-only runtime statistics — no debug gate required.
 *
 * Generated from Go `router.metricsSnapshot` (internal/router/metrics.go).
 */
export interface MetricsSnapshot {
  /** timing */
  timestamp: string
  uptime: string
  uptime_secs: number
  start_time: string
  startup_duration_ms: number
  pre_init_ms: number
  startup_phases?: StartupPhase[]
  /** memory (bytes) */
  heap_alloc_bytes: number
  heap_sys_bytes: number
  heap_inuse_bytes: number
  sys_bytes: number
  stack_inuse_bytes: number
  /** GC */
  num_gc: number
  gc_pause_last_ms: number
  gc_pause_total_ms: number
  next_gc_bytes: number
  /** runtime */
  goroutines: number
  go_version: string
  num_cpu: number
}

/**
 * StartupPhase records a single timed phase during server initialization.
 * Exposed via /_overcast/metrics to power the startup timeline visualisation in the web UI.
 * StartMs is milliseconds since Go startup. Environment phases use the process-start anchor.
 *
 * Generated from Go `router.StartupPhase` (internal/router/startup_profile.go).
 */
export interface StartupPhase {
  name: string
  /** ms since Go startup, except environment phase */
  start_ms: number
  /** ms this phase took */
  duration_ms: number
  environment?: boolean
}

/**
 * healthResponse is the JSON body returned by GET /_overcast/health.
 *
 * Generated from Go `router.healthResponse` (internal/router/health.go).
 */
export interface HealthResponse {
  status: string
  timestamp: string
  version: string
  services: string[]
  /**
   * ServiceTiers and ServiceGoalTiers are keyed by service name. The value
   * type is the EmulationTier alias rather than bare string so cmd/tsgen
   * renders the web UI's type as the tier union, not `string`.
   */
  serviceTiers: Record<string, EmulationTier>
  serviceGoalTiers: Record<string, EmulationTier>
  storage: HealthStorage
  docker?: DockerHealth
}

/**
 * healthStorage describes the active storage configuration.
 *
 * Generated from Go `router.healthStorage` (internal/router/health.go).
 */
export interface HealthStorage {
  default: string
  /**
   * Configured is the raw OVERCAST_STATE value as configured — "auto" when
   * unset or explicitly "auto" (see config.StateSource), otherwise the
   * same value as Default. Distinguishing the two lets a caller tell "the
   * backend in effect" (Default, always concrete) apart from "what was
   * actually configured" (this field) — e.g. Default: "memory",
   * Configured: "auto" means the auto-resolver picked memory because it
   * found no evidence of persistence intent, not that anyone set
   * OVERCAST_STATE=memory. Omitted (not just empty) for callers/tests that
   * build a Config directly rather than via config.Load(), where this
   * field is never populated.
   */
  configured?: string
  serviceOverrides?: Record<string, string>
  persistent?: PersistentHealth
}

/**
 * persistentHealth is the health endpoint's view of state.PersistentHealth:
 * the same fields, with the timestamps already formatted as RFC 3339 strings
 * and omitted when zero (a zero time.Time would otherwise marshal as
 * "0001-01-01T00:00:00Z" — omitempty does not apply to structs).
 *
 * Generated from Go `router.persistentHealth` (internal/router/health.go).
 */
export interface PersistentHealth {
  mode: string
  healthy: boolean
  pendingWrites: number
  lastError?: string
  lastErrorAt?: string
  lastSuccessAt?: string
}

/**
 * EmulationTier describes how completely a service is emulated.
 *
 *   - "full"        — P1+P2 operations implemented; real SDK clients can use it.
 *   - "partial"     — P1 operations implemented; basic workflows work.
 *   - "inert"       — Full CRUD works, resources exist, but no side-effects or enforcement.
 *   - "stub"        — Registered with only a minimal discovery or control-plane subset;
 *     unsupported endpoints return 501 Not Implemented.
 *   - "unsupported" — Not registered in Overcast; no backend handler exists.
 *
 * Generated from Go `router.EmulationTier` (internal/router/tiers.go).
 */
export type EmulationTier = "full" | "partial" | "inert" | "stub" | "unsupported"

/**
 * Status is a snapshot of the Docker daemon state across all services.
 *
 * Generated from Go `docker.Status` (internal/docker/status.go).
 */
export interface DockerHealth {
  available: boolean
  services: DockerServiceHealth[]
  lastEvent?: string
  lastEventAt?: string
}

/**
 * ServiceHealth records the Docker connectivity state for a single service.
 *
 * Generated from Go `docker.ServiceHealth` (internal/docker/status.go).
 */
export interface DockerServiceHealth {
  service: string
  socket: string
  connected: boolean
  error?: string
  lastSeen?: string
}

/**
 * debugMetricsResponse is the JSON body for GET /_overcast/debug/metrics
 * (storage-plan.md item 3.6). Stores is one entry per distinct underlying
 * store that implements state.DebugMetricsReporter — see
 * state.DebugMetricsSnapshot's doc comment for why a *state.NamespacedStore
 * yields a list here instead of one merged entry. Every store implementation
 * in this codebase implements the interface (if only to report
 * state.StoreCounters — see that type's doc comment), so this is empty
 * (never null) only for a hypothetical future Store that doesn't.
 *
 * Advisories is the server-computed diagnostics list the web UI's Metrics &
 * Health page renders generically (see advisories.go's computeAdvisories) —
 * always present (never null), empty when nothing needs attention.
 *
 * Query params: ?includeRowCounts=true additionally computes
 * NamespaceRowCounts per store — for TierCached namespaces this issues one
 * SQL COUNT(*) per namespace, so it is opt-in rather than always computed.
 *
 * Generated from Go `router.debugMetricsResponse` (internal/router/debug.go).
 */
export interface DebugMetricsResponse {
  /**
   * state.DebugMetrics carries the JSON tags for this wire shape;
   * DebugFlushRecord timestamps are stored UTC and marshal as RFC 3339.
   */
  stores: DebugMetrics[]
  advisories: Advisory[]
}

/**
 * DebugMetrics is a snapshot of storage-layer diagnostics for
 * GET /_overcast/debug/metrics (storage-plan.md item 3.6): recent flush history, the
 * one-time TierHot seed duration, the pending write-ahead log's on-disk
 * size, and — only when DebugMetricsOptions.IncludeNamespaceRowCounts is
 * set — per-namespace row counts.
 *
 * Generated from Go `state.DebugMetrics` (internal/state/store.go).
 */
export interface DebugMetrics {
  /**
   * Mode identifies which backend produced this snapshot (e.g. "hybrid",
   * "persistent"), matching config.Config.State's values.
   */
  mode: string
  /**
   * FlushHistory holds the most recent flush attempts, oldest first,
   * bounded to a small ring buffer. Empty for backends that write
   * synchronously and never batch/flush (e.g. SQLiteStore).
   */
  flushHistory?: DebugFlushRecord[]
  /**
   * SeedDurationMillis is how long the background TierHot seed took to
   * complete, in milliseconds, or nil if seeding hasn't finished yet, is
   * still in flight, degraded to memory-only before finishing (see
   * HybridStore.degradeToMemoryOnly — there is no coherent "seed
   * duration" for a seed that didn't complete), or never happens for this
   * backend at all.
   */
  seedDurationMillis?: number
  /**
   * PendingLogBytes is the current on-disk size of the not-yet-flushed
   * write-ahead log, in bytes. 0 for backends without one.
   */
  pendingLogBytes?: number
  /**
   * NamespaceRowCounts maps namespace -> row count, populated only when
   * DebugMetricsOptions.IncludeNamespaceRowCounts was set.
   */
  namespaceRowCounts?: Record<string, number>
  /**
   * ReadRetryCount is the total number of individual retry attempts made
   * by the hybrid SQLite read-retry path (retrySQLiteGet/List/
   * ListNamespaces/Scan/ScanPage in hybrid.go) since process start, after
   * an initial read hit busy/locked contention or a canceled context. One
   * Get/List/Scan call under contention can contribute several retries.
   * 0 for backends without a read-retry path (MemoryStore, WALStore).
   */
  readRetryCount?: number
  /**
   * ReadTimeoutCount is the number of hybrid SQLite reads whose retry
   * window (hybridSQLiteReadRetryTimeout) was fully exhausted without
   * success since process start. Each of these is tagged with
   * ErrStorePressure (see HybridStore.wrapStorePressure) so callers up
   * the stack receive an AWS-shaped throttling error instead of a generic
   * InternalError — see protocol/errors.go. 0 for backends without a
   * read-retry path.
   */
  readTimeoutCount?: number
  /**
   * DataDirProbe reports the outcome of the one-time startup fsync
   * micro-probe (see HybridStore's runDataDirProbe) that flags a slow
   * data directory (e.g. a Docker Desktop bind mount) before it manifests
   * as flush/read latency. nil for backends that don't run the probe.
   */
  dataDirProbe?: DataDirProbeResult
  /**
   * JournalMode is the LIVE `PRAGMA journal_mode` readback from this
   * backend's SQLite connection, queried once during store initialisation
   * (after the connection is open and migrated, never per-request) — see
   * hybrid.go's seedFromSQLite and sqlite.go's runMigrate. Empty for
   * backends with no real SQLite connection to ask (MemoryStore, WALStore)
   * or when the backend degraded before the readback could run.
   *
   * This field exists because of a real historical failure, not a
   * hypothetical one: every persistent connection's DSN silently disabled
   * WAL mode for this project's entire history due to a driver-spelling
   * bug (see hybrid_journalmode_internal_test.go), while every doc comment
   * in this package confidently claimed WAL was active the whole time.
   * Surfacing the ACTUAL, LIVE pragma value here — rather than trusting the
   * DSN parameter we asked for — means that class of silent misconfiguration
   * can never hide again; see internal/router/advisories.go's
   * journal-mode-not-wal rule, which alerts the moment this diverges from
   * "wal" on a persistent/hybrid backend.
   */
  journalMode?: string
  /**
   * Degraded is true when the persistent backend permanently fell back to
   * memory-only for this process's lifetime (see
   * HybridStore.degradeToMemoryOnly) — every write since is memory-only and
   * will not survive a restart. Always false for backends that cannot
   * degrade this way: SQLiteStore fails outright rather than falling back,
   * and MemoryStore/WALStore never persist at all.
   */
  degraded?: boolean
  /**
   * Counters holds cumulative storage-layer read/write activity since
   * process start (health/metrics "storage activity" — the answer to "how
   * much is this backend actually doing"). Every implementation
   * (MemoryStore, SQLiteStore, WALStore, HybridStore) populates at least
   * Reads/Writes; see StoreCounters's doc comment for the hybrid-specific
   * tier split.
   */
  counters: StoreCounters
}

/**
 * DebugFlushRecord is one entry in DebugMetrics.FlushHistory: a single
 * attempt to persist buffered writes, whether or not it succeeded.
 *
 * Generated from Go `state.DebugFlushRecord` (internal/state/store.go).
 */
export interface DebugFlushRecord {
  timestamp: string
  durationMillis: number
  entries: number
  committed: boolean
  /**
   * Chunks is how many separate SQLite transactions this flush attempt
   * split Entries across (storage-pressure-handling item 2 — see
   * HybridStore's chunkHybridFlushOps). 1 for a batch small enough to fit
   * in a single transaction; 0 for backends that don't chunk flushes.
   */
  chunks?: number
}

/**
 * StoreCounters is a cheap, atomically-maintained tally of storage-layer
 * operations since process start — no locks and no per-op allocations on any
 * store's hot Get/Set path (sync/atomic only).
 *
 * Reads counts every Get/List/Scan/ScanPage/ListNamespaces call; Writes
 * counts every Set/Delete/DeletePrefix call. These two fields are populated
 * by all four store implementations.
 *
 * ReadsMemory/ReadsSQLite/WritesFlushedRows are populated only by
 * HybridStore, the only implementation that actually serves reads/writes
 * from two distinct tiers:
 *   - ReadsMemory is a read served from the in-memory tier — either a
 *     pending-overlay hit (an accepted-but-not-yet-flushed write, which
 *     lives only in RAM) or a plain MemoryStore read. ReadsSQLite is a read
 *     that fell through to a live SQLite query. ReadsMemory + ReadsSQLite
 *     always equals Reads.
 *   - WritesFlushedRows is the count of pending-op rows the background
 *     flush loop has actually committed to SQLite so far — necessarily a
 *     subset of Writes, since not every accepted write has been flushed
 *     yet. This reuses flushOnce's existing per-attempt entry count (see
 *     HybridStore.recordFlushHistory) rather than adding a second, separately
 *     maintained tally that could drift from it.
 *
 * Zero-valued (omitted from JSON) for every other backend, which has no
 * second tier to split against.
 *
 * Generated from Go `state.StoreCounters` (internal/state/store.go).
 */
export interface StoreCounters {
  reads: number
  writes: number
  readsMemory?: number
  readsSQLite?: number
  writesFlushedRows?: number
}

/**
 * DataDirProbeResult is the outcome of the startup fsync micro-probe (see
 * HybridStore's runDataDirProbe / probeDataDirFsync): a small write+fsync
 * timed against dataDirSlowFsyncThreshold, run once per process so a slow
 * data directory is visible before it degrades flush/read latency (docs/
 * performance.md "Data dir placement").
 *
 * Generated from Go `state.DataDirProbeResult` (internal/state/store.go).
 */
export interface DataDirProbeResult {
  /** FsyncMillis is how long the probe's write+fsync took, in milliseconds. */
  fsyncMillis: number
  /**
   * Slow is true when FsyncMillis exceeded the configured threshold
   * (dataDirSlowFsyncThreshold by default) — the same condition that
   * triggers the one-time startup warning log line.
   */
  slow: boolean
  /** ProbedAt is when the probe ran, UTC. */
  probedAt: string
  /**
   * FsType is the filesystem type hosting the data dir per /proc/mounts
   * (e.g. "ext4", "9p", "fuse.grpcfuse"); empty when it couldn't be read
   * (non-Linux, or /proc/mounts unavailable).
   */
  fsType?: string
  /**
   * MountClass is a coarse classification of FsType used to tailor the
   * slow-filesystem advisory: "native" (real in-VM/host filesystem —
   * slowness means I/O pressure, not a bind mount), "shared" (Docker
   * Desktop file-sharing protocol — the bind-mount tax; switching to a
   * named volume applies), or "unknown".
   */
  mountClass?: string
}

/**
 * Advisory is one actionable diagnostic surfaced alongside the storage
 * diagnostics in GET /_overcast/debug/metrics (see debugMetricsResponse.Advisories).
 * The web UI's Metrics & Health page renders these generically — icon/color
 * from Severity, then Title/Detail/optional DocsPath link — so adding a
 * future rule to computeAdvisories never requires a web UI change.
 *
 * Generated from Go `router.Advisory` (internal/router/advisories.go).
 */
export interface Advisory {
  /** Severity is one of "info", "warning", "critical". */
  severity: AdvisorySeverity
  /**
   * Code is a stable, machine-readable identifier for this advisory rule
   * (e.g. "journal-mode-not-wal") — safe to key UI behavior or tests off
   * of, unlike Title/Detail, which are free text that may be reworded.
   */
  code: string
  /** Title is a short, human-readable summary (fits in a single UI line). */
  title: string
  /**
   * Detail is a longer explanation, including any concrete numbers/values
   * relevant to this specific occurrence (e.g. the live journal mode
   * actually observed, or how many reads were affected).
   */
  detail: string
  /**
   * DocsPath, when non-empty, is a docs-browser-relative path (see
   * performanceDocsPath) the web UI can open for remediation guidance.
   */
  docsPath?: string
}

/**
 * AdvisorySeverity is the severity of an Advisory: one of the constants below.
 * The web UI (see web/src/features/metrics) renders these generically by
 * severity — icon/color only — so adding a value here requires a matching UI
 * mapping, unlike adding a new *rule*, which requires no UI change at all (see
 * computeAdvisories's doc comment). cmd/tsgen renders the typed constants as
 * the TypeScript union, which is what makes the UI's mapping type-checked
 * against this list.
 *
 * Generated from Go `router.AdvisorySeverity` (internal/router/advisories.go).
 */
export type AdvisorySeverity = "info" | "warning" | "critical"

/**
 * DiagnosticProvenance is where a piece of emulator diagnostic evidence came
 * from: one of the constants below. These are contract values — the console
 * renders one label per tier — so they are not free text, and cmd/tsgen
 * renders the typed constants as the TypeScript union the console's
 * provenance tag is keyed on.
 *
 * Overcast is allowed to say things AWS never would, but only where it is
 * unmistakably Overcast talking — see docs/dev/architecture.md § "Two things
 * called a bus". The risk that creates is a developer reading a captured
 * container log or an inferred summary, believing real AWS would have handed
 * them the same thing, and writing a fix that depends on a signal production
 * will never produce. Tagging every piece of evidence with its origin is what
 * makes that mistake hard, so the tier is carried on the payload rather than
 * being a blanket "emulator-only" badge on the panel.
 *
 * The vocabulary is deliberately service-neutral. CloudFormation deploy
 * diagnostics is the first consumer; RDS's retained-logs panel — which already
 * draws the same distinction with a bespoke `logSource: "container" |
 * "retained"` field — is the obvious second, and a second vocabulary would put
 * the two panels back to explaining the same idea in different words.
 *
 * Generated from Go `cloudformation.DiagnosticProvenance` (internal/services/cloudformation/diagnostics.go).
 */
export type DiagnosticProvenance = "aws-api" | "overcast-capture" | "overcast-inference"
