package bff

import (
	"io/fs"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"testing/fstest"
)

func TestDocsPage_validPath(t *testing.T) {
	// Given: a docs filesystem rooted at docs/.
	docsFS := fstest.MapFS{
		"cdk/local-vpc.md": &fstest.MapFile{Data: []byte("# Local VPCs for CDK\n")},
	}
	handler := NewHandler(nil, docsFS, UIConfig{})

	// When: we request a safe docs page path.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/page?path=cdk%2Flocal-vpc.md", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: the markdown content is returned.
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	if got := rec.Header().Get("Content-Type"); got != "text/markdown; charset=utf-8" {
		t.Fatalf("expected markdown content-type, got %q", got)
	}
	if rec.Body.String() != "# Local VPCs for CDK\n" {
		t.Fatalf("unexpected body: %q", rec.Body.String())
	}
}

func TestDocsPage_stripsFrontmatter(t *testing.T) {
	// Given: a doc with a YAML frontmatter block, as generated by scripts/docs-index.go.
	docsFS := fstest.MapFS{
		"README.md": &fstest.MapFile{Data: []byte("---\ntitle: \"Documentation\"\ntags:\n  - docs\n---\n\n# Documentation\n\nBody text.\n")},
	}
	handler := NewHandler(nil, docsFS, UIConfig{})

	// When: the page is requested through the docs browser API.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/page?path=README.md", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: the frontmatter block is stripped and only the markdown body is returned.
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	if got := rec.Body.String(); got != "# Documentation\n\nBody text.\n" {
		t.Fatalf("expected frontmatter stripped, got %q", got)
	}
}

func TestStripFrontmatter(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "no frontmatter",
			in:   "# Title\n\nBody text.\n",
			want: "# Title\n\nBody text.\n",
		},
		{
			name: "standard frontmatter",
			in:   "---\ntitle: \"X\"\n---\n\n# Title\n\nBody.\n",
			want: "# Title\n\nBody.\n",
		},
		{
			name: "frontmatter with no blank line before body",
			in:   "---\ntitle: \"X\"\n---\n# Title\n",
			want: "# Title\n",
		},
		{
			name: "CRLF line endings",
			in:   "---\r\ntitle: \"X\"\r\n---\r\n\r\n# Title\r\n",
			want: "# Title\r\n",
		},
		{
			name: "frontmatter consumes entire file",
			in:   "---\ntitle: \"X\"\n---\n",
			want: "",
		},
		{
			name: "unclosed frontmatter is left untouched",
			in:   "---\ntitle: \"X\"\n\n# Title\n",
			want: "---\ntitle: \"X\"\n\n# Title\n",
		},
		{
			name: "dashes mid-document are not treated as frontmatter",
			in:   "# Title\n\n---\n\nRest.\n",
			want: "# Title\n\n---\n\nRest.\n",
		},
		{
			name: "empty file",
			in:   "",
			want: "",
		},
		{
			name: "only opening delimiter, no newline",
			in:   "---",
			want: "---",
		},
		{
			name: "four dashes is not a frontmatter delimiter",
			in:   "----\ntitle: \"X\"\n----\n\n# Title\n",
			want: "----\ntitle: \"X\"\n----\n\n# Title\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := stripFrontmatter([]byte(tt.in))
			if string(got) != tt.want {
				t.Fatalf("stripFrontmatter(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestStripFrontmatter_doesNotMutateInput(t *testing.T) {
	// Given: doc content with frontmatter, kept as a reference copy.
	in := []byte("---\ntitle: \"X\"\n---\n\n# Title\n")
	original := append([]byte(nil), in...)

	// When: stripFrontmatter is called.
	_ = stripFrontmatter(in)

	// Then: the input slice's bytes are untouched (result may share its backing
	// array, but must not write into it).
	if string(in) != string(original) {
		t.Fatalf("stripFrontmatter mutated its input: got %q, want %q", in, original)
	}
}

func BenchmarkStripFrontmatter(b *testing.B) {
	content := []byte("---\ntitle: \"Documentation\"\ndescription: \"Some longer description text here.\"\nsection: \"Getting Started\"\ntags:\n  - docs\n  - documentation\n---\n\n# Documentation\n\n" +
		strings.Repeat("Body paragraph text repeated to simulate a realistic doc page.\n", 200))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		stripFrontmatter(content)
	}
}

func TestDocsPage_pathTraversal(t *testing.T) {
	// Given: a docs filesystem.
	handler := NewHandler(nil, fstest.MapFS{}, UIConfig{})

	// When: a path traversal request is made.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/page?path=..%2FREADME.md", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: it is rejected.
	if rec.Code != http.StatusNotFound {
		t.Fatalf("expected 404, got %d: %s", rec.Code, rec.Body.String())
	}
}

func TestDocsPage_rejectsDeveloperPlans(t *testing.T) {
	// Given: a docs filesystem that contains developer-only planning notes.
	docsFS := fstest.MapFS{
		"plans/mcp.md": &fstest.MapFile{Data: []byte("# MCP plan\n")},
	}
	handler := NewHandler(nil, docsFS, UIConfig{})

	// When: a plan document is requested directly.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/page?path=plans%2Fmcp.md", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: developer-only plans are not served through the docs browser API.
	if rec.Code != http.StatusNotFound {
		t.Fatalf("expected 404, got %d: %s", rec.Code, rec.Body.String())
	}
}

func TestDocsService_usesServicesSubdirectory(t *testing.T) {
	// Given: the BFF docs filesystem is rooted at docs/.
	docsFS := fstest.MapFS{
		"services/s3.md": &fstest.MapFile{Data: []byte("# S3\n")},
	}
	handler := NewHandler(nil, docsFS, UIConfig{})

	// When: the legacy service docs endpoint is requested.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/s3", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: it still returns docs/services/{service}.md.
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	if rec.Body.String() != "# S3\n" {
		t.Fatalf("unexpected body: %q", rec.Body.String())
	}
}

// TestDocsService_stripsFrontmatter pins that the per-service docs endpoint
// strips leading YAML frontmatter exactly like /api/docs/page does — the
// service docs modal renders this response verbatim, so unstripped
// frontmatter would show up in the UI as a thematic break plus raw
// "title:/description:" text above every service doc.
func TestDocsService_stripsFrontmatter(t *testing.T) {
	// Given: a service doc with a frontmatter block (as scripts/docs-index.go
	// writes for every published doc).
	docsFS := fstest.MapFS{
		"services/sqs.md": &fstest.MapFile{
			Data: []byte("---\ntitle: \"SQS\"\nsection: \"Service Reference\"\n---\n\n# SQS\nbody\n"),
		},
	}
	handler := NewHandler(nil, docsFS, UIConfig{})

	// When: the service docs endpoint is requested.
	req := httptest.NewRequest(http.MethodGet, "/api/docs/sqs", nil)
	rec := httptest.NewRecorder()
	handler.ServeHTTP(rec, req)

	// Then: the frontmatter is gone and the markdown body starts at the title.
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	if got := rec.Body.String(); got != "# SQS\nbody\n" {
		t.Fatalf("expected frontmatter to be stripped, got: %q", got)
	}
}

var _ fs.FS = fstest.MapFS{}
