//go:build dev

package eks

import "github.com/Neaox/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		capabilities.Capability{Service: "eks", Operation: "CreateCluster", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Stores cluster metadata including roleArn, version, resourcesVpcConfig, kubernetesNetworkConfig, and encryptionConfig; describe returns inline tags"},
		capabilities.Capability{Service: "eks", Operation: "DescribeCluster", Category: "Clusters", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "DescribeClusterVersions", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns synthetic supported Kubernetes version catalog"},
		capabilities.Capability{Service: "eks", Operation: "ListClusters", Category: "Clusters", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "CreateAccessEntry", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Stores cluster principal access entry metadata and persists inline tags"},
		capabilities.Capability{Service: "eks", Operation: "DescribeAccessEntry", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored access entry metadata for a cluster principal ARN with inline tags"},
		capabilities.Capability{Service: "eks", Operation: "UpdateAccessEntry", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Updates stored access entry username/groups for a cluster principal ARN"},
		capabilities.Capability{Service: "eks", Operation: "DeleteAccessEntry", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Deletes stored access entry metadata for a cluster principal ARN"},
		capabilities.Capability{Service: "eks", Operation: "ListAccessEntries", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored principal ARNs for cluster access entries"},
		capabilities.Capability{Service: "eks", Operation: "AssociateAccessPolicy", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Associates a policy ARN with a stored access entry principal"},
		capabilities.Capability{Service: "eks", Operation: "ListAccessPolicies", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns synthetic managed EKS access policy catalog"},
		capabilities.Capability{Service: "eks", Operation: "DescribeAccessPolicy", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns synthetic managed EKS access policy details by name"},
		capabilities.Capability{Service: "eks", Operation: "ListAssociatedAccessPolicies", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Lists associated policy ARNs and access scopes for a stored access entry principal"},
		capabilities.Capability{Service: "eks", Operation: "DisassociateAccessPolicy", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Disassociates a policy ARN from a stored access entry principal"},
		capabilities.Capability{Service: "eks", Operation: "ListIdentityProviderConfigs", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored identity provider config summaries"},
		capabilities.Capability{Service: "eks", Operation: "DescribeIdentityProviderConfig", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored identity provider config details by type/name with inline tags"},
		capabilities.Capability{Service: "eks", Operation: "UpdateIdentityProviderConfig", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Updates stored identity provider config fields and records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "AssociateIdentityProviderConfig", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Stores OIDC identity provider metadata, persists inline tags, and records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "DisassociateIdentityProviderConfig", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Removes stored identity provider metadata, clears inline tags, and records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "CreatePodIdentityAssociation", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Creates and stores pod identity association metadata for a cluster service account, persists inline tags, and rejects duplicate namespace/service-account bindings"},
		capabilities.Capability{Service: "eks", Operation: "ListPodIdentityAssociations", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored pod identity associations for a cluster"},
		capabilities.Capability{Service: "eks", Operation: "DescribePodIdentityAssociation", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns stored pod identity association details by association ID with inline tags"},
		capabilities.Capability{Service: "eks", Operation: "UpdatePodIdentityAssociation", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Updates stored pod identity association role ARN by association ID"},
		capabilities.Capability{Service: "eks", Operation: "DeletePodIdentityAssociation", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Deletes stored pod identity association metadata by association ID"},
		capabilities.Capability{Service: "eks", Operation: "ListUpdates", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Lists recorded update IDs for a cluster"},
		capabilities.Capability{Service: "eks", Operation: "ListInsights", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns synthetic health/readiness insight summaries for a cluster"},
		capabilities.Capability{Service: "eks", Operation: "DescribeInsight", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns synthetic health/readiness insight detail by insight ID"},
		capabilities.Capability{Service: "eks", Operation: "UpdateClusterConfig", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Updates stored cluster logging, resourcesVpcConfig, and kubernetesNetworkConfig; records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "UpdateClusterVersion", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Updates stored cluster version metadata"},
		capabilities.Capability{Service: "eks", Operation: "DescribeUpdate", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Returns previously recorded cluster/nodegroup update status by update ID"},
		capabilities.Capability{Service: "eks", Operation: "DeleteCluster", Category: "Clusters", Status: capabilities.StatusSupported, Notes: "Deletes cluster metadata and nodegroups"},
		capabilities.Capability{Service: "eks", Operation: "UpdateKubeconfig", Category: "Helpers", Status: capabilities.StatusSupported, Notes: "Returns generated kubeconfig YAML for mock clusters and ready live clusters (503 until live endpoint/CA are ready)"},
		capabilities.Capability{Service: "eks", Operation: "CreateNodegroup", Category: "Nodegroups", Status: capabilities.StatusSupported, Notes: "Stores full nodegroup metadata including instanceTypes, amiType, capacityType, diskSize, taints, labels, scalingConfig, updateConfig, launchTemplate, and releaseVersion"},
		capabilities.Capability{Service: "eks", Operation: "UpdateNodegroupVersion", Category: "Nodegroups", Status: capabilities.StatusSupported, Notes: "Updates stored nodegroup version metadata"},
		capabilities.Capability{Service: "eks", Operation: "UpdateNodegroupConfig", Category: "Nodegroups", Status: capabilities.StatusSupported, Notes: "Updates stored nodegroup labels, taints, scalingConfig, and updateConfig; records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "DescribeNodegroup", Category: "Nodegroups", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "ListNodegroups", Category: "Nodegroups", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "DeleteNodegroup", Category: "Nodegroups", Status: capabilities.StatusSupported, Notes: "Deletes nodegroup metadata"},
		capabilities.Capability{Service: "eks", Operation: "ListFargateProfiles", Category: "Fargate", Status: capabilities.StatusSupported, Notes: "Lists stored profiles; always includes synthetic \"default\" profile"},
		capabilities.Capability{Service: "eks", Operation: "DescribeFargateProfile", Category: "Fargate", Status: capabilities.StatusSupported, Notes: "Returns stored or synthetic default profile"},
		capabilities.Capability{Service: "eks", Operation: "CreateFargateProfile", Category: "Fargate", Status: capabilities.StatusSupported, Notes: "Stores Fargate profile metadata including podExecutionRoleArn, subnets, and selectors"},
		capabilities.Capability{Service: "eks", Operation: "DeleteFargateProfile", Category: "Fargate", Status: capabilities.StatusSupported, Notes: "Removes stored Fargate profile metadata"},
		capabilities.Capability{Service: "eks", Operation: "ListTagsForResource", Category: "Tags", Status: capabilities.StatusSupported, Notes: "Returns tags for any EKS resource ARN"},
		capabilities.Capability{Service: "eks", Operation: "TagResource", Category: "Tags", Status: capabilities.StatusSupported, Notes: "Adds tags to an EKS resource by ARN"},
		capabilities.Capability{Service: "eks", Operation: "UntagResource", Category: "Tags", Status: capabilities.StatusSupported, Notes: "Removes tags from an EKS resource by ARN"},
		capabilities.Capability{Service: "eks", Operation: "CreateAddon", Category: "Addons", Status: capabilities.StatusSupported, Notes: "Stores add-on metadata including addonVersion, configurationValues, and serviceAccountRoleArn; describe returns inline tags"},
		capabilities.Capability{Service: "eks", Operation: "DescribeAddon", Category: "Addons", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "ListAddons", Category: "Addons", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "eks", Operation: "UpdateAddon", Category: "Addons", Status: capabilities.StatusSupported, Notes: "Updates stored add-on version/configuration and records an update entry"},
		capabilities.Capability{Service: "eks", Operation: "DeleteAddon", Category: "Addons", Status: capabilities.StatusSupported, Notes: "Removes add-on metadata"},
		capabilities.Capability{Service: "eks", Operation: "DescribeAddonConfiguration", Category: "Addons", Status: capabilities.StatusSupported, Notes: "Returns synthetic configuration schema for core add-ons"},
		capabilities.Capability{Service: "eks", Operation: "DescribeAddonVersions", Category: "Addons", Status: capabilities.StatusSupported, Notes: "Returns synthetic version catalog for vpc-cni, coredns, kube-proxy, aws-ebs-csi-driver; empty for unknown add-ons"},
	)
}
