// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/scenarios/servicediscovery.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/scenarios/servicediscovery.json";

const GROUP_SERVICEDISCOVERY_GEN_NAMESPACE: Group = Group {
    name: "servicediscovery-gen-namespace",
    file: SCENARIO_FILE,
};

const GROUP_SERVICEDISCOVERY_GEN_INSTANCE: Group = Group {
    name: "servicediscovery-gen-instance",
    file: SCENARIO_FILE,
};

const GROUP_SERVICEDISCOVERY_GEN_PROBE: Group = Group {
    name: "servicediscovery-gen-probe",
    file: SCENARIO_FILE,
};

/// The generated servicediscovery groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosServicediscovery {
    client: aws_sdk_servicediscovery::Client,
}

impl ScenariosServicediscovery {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_servicediscovery::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_servicediscovery::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosServicediscovery {
    fn name(&self) -> &'static str {
        "scenarios/servicediscovery"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:CreateHttpNamespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "CreateHttpNamespace", test_servicediscovery_gen_namespace_create_http_namespace(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:GetNamespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "GetNamespace", test_servicediscovery_gen_namespace_get_namespace(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:UpdateHttpNamespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "UpdateHttpNamespace", test_servicediscovery_gen_namespace_update_http_namespace(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:TagResource".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "TagResource", test_servicediscovery_gen_namespace_tag_resource(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:ListTagsForResource".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "ListTagsForResource", test_servicediscovery_gen_namespace_list_tags_for_resource(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:UntagResource".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "UntagResource", test_servicediscovery_gen_namespace_untag_resource(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:ListNamespaces".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "ListNamespaces", test_servicediscovery_gen_namespace_list_namespaces(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-namespace:DeleteNamespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE
                            .run_test(&ctx, "DeleteNamespace", test_servicediscovery_gen_namespace_delete_namespace(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-instance:RegisterInstance".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE
                            .run_test(&ctx, "RegisterInstance", test_servicediscovery_gen_instance_register_instance(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-instance:GetInstance".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE
                            .run_test(&ctx, "GetInstance", test_servicediscovery_gen_instance_get_instance(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-instance:ListInstances".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE
                            .run_test(&ctx, "ListInstances", test_servicediscovery_gen_instance_list_instances(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-instance:DeregisterInstance".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE
                            .run_test(&ctx, "DeregisterInstance", test_servicediscovery_gen_instance_deregister_instance(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-probe:GetInstancesHealthStatus".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_PROBE
                            .run_test(&ctx, "GetInstancesHealthStatus", test_servicediscovery_gen_probe_get_instances_health_status(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "servicediscovery-gen-probe:GetOperation".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_PROBE
                            .run_test(&ctx, "GetOperation", test_servicediscovery_gen_probe_get_operation(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "servicediscovery-gen-namespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.run_setup(&ctx, setup_servicediscovery_gen_namespace(&client)).await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            setups.insert(
                "servicediscovery-gen-instance".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.run_setup(&ctx, setup_servicediscovery_gen_instance(&client)).await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            setups.insert(
                "servicediscovery-gen-probe".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_PROBE.run_setup(&ctx, setup_servicediscovery_gen_probe(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "servicediscovery-gen-namespace".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.run_teardown(&ctx, teardown_servicediscovery_gen_namespace(&client)).await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            teardowns.insert(
                "servicediscovery-gen-instance".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.run_teardown(&ctx, teardown_servicediscovery_gen_instance(&client)).await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            teardowns.insert(
                "servicediscovery-gen-probe".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SERVICEDISCOVERY_GEN_PROBE.run_teardown(&ctx, teardown_servicediscovery_gen_probe(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_servicediscovery_gen_namespace(_client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_servicediscovery_gen_namespace(client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    vec![
        Call {
            op: "DeleteNamespace",
            params: scenario::map(vec![("Id", scenario::context("namespace.id"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_namespace()
                            .id(b.string("Id")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_servicediscovery_gen_namespace_create_http_namespace(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "CreateHttpNamespace",
            params: scenario::map(vec![
                ("Description", scenario::lit(::serde_json::json!("compat scenario namespace"))),
                ("Name", scenario::name("ns")),
            ]),
            export: vec![
                ("namespace.operationId", "$.OperationId"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_http_namespace()
                            .description("compat scenario namespace")
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.OperationId"),
            ]),
            scenario::eventually(30, 2000,
                scenario::readback(
                    Call {
                        op: "GetOperation",
                        params: scenario::map(vec![
                            ("OperationId", scenario::context("namespace.operationId")),
                        ]),
                        export: vec![
                            ("namespace.id", "$.Operation.Targets.NAMESPACE"),
                        ],
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_operation()
                                        .operation_id(b.string("OperationId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::non_empty("$.Operation.Targets.NAMESPACE"),
                    ],
                ),
            ),
            scenario::eventually(30, 2000,
                scenario::readback(
                    Call {
                        op: "GetNamespace",
                        params: scenario::map(vec![
                            ("Id", scenario::context("namespace.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_namespace()
                                        .id(b.string("Id")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::equals("$.Namespace.Id", scenario::context("namespace.id")),
                    ],
                ),
            ),
            scenario::eventually(30, 2000,
                scenario::list_contains(
                    Some(Call {
                        op: "ListNamespaces",
                        params: scenario::lit(::serde_json::json!({})),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |_b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_namespaces()
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Namespaces",
                    vec![
                        scenario::where_entry("$.Id", scenario::context("namespace.id")),
                    ],
                ),
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_get_namespace(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "GetNamespace",
            params: scenario::map(vec![("Id", scenario::context("namespace.id"))]),
            export: vec![
                ("namespace.arn", "$.Namespace.Arn"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_namespace()
                            .id(b.string("Id")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.Namespace.Id", scenario::context("namespace.id")),
            ]),
        ],
    }
}

fn test_servicediscovery_gen_namespace_update_http_namespace(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "UpdateHttpNamespace",
            params: scenario::map(vec![
                ("Id", scenario::context("namespace.id")),
                ("Namespace", scenario::lit(::serde_json::json!({"Description": "compat scenario namespace, updated"}))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .update_http_namespace()
                            .id(b.string("Id")?)
                            .namespace(
                                aws_sdk_servicediscovery::types::HttpNamespaceChange::builder()
                                    .description("compat scenario namespace, updated")
                                    .build()
                                    .map_err(|err| scenario::build_error("Namespace", err))?
                            )
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(30, 2000,
                scenario::readback(
                    Call {
                        op: "GetNamespace",
                        params: scenario::map(vec![
                            ("Id", scenario::context("namespace.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_namespace()
                                        .id(b.string("Id")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::equals("$.Namespace.Description", scenario::lit(::serde_json::json!("compat scenario namespace, updated"))),
                    ],
                ),
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_tag_resource(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "TagResource",
            params: scenario::map(vec![
                ("ResourceARN", scenario::context("namespace.arn")),
                ("Tags", scenario::lit(::serde_json::json!([{"Key": "compat", "Value": "scenario"}]))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .tag_resource()
                            .resource_arn(b.string("ResourceARN")?)
                            .tags(
                                aws_sdk_servicediscovery::types::Tag::builder()
                                    .key("compat")
                                    .value("scenario")
                                    .build()
                                    .map_err(|err| scenario::build_error("Tags[0]", err))?
                            )
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(30, 2000,
                scenario::list_contains(
                    Some(Call {
                        op: "ListTagsForResource",
                        params: scenario::map(vec![
                            ("ResourceARN", scenario::context("namespace.arn")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_tags_for_resource()
                                        .resource_arn(b.string("ResourceARN")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Tags",
                    vec![
                        scenario::where_entry("$.Key", scenario::lit(::serde_json::json!("compat"))),
                        scenario::where_entry("$.Value", scenario::lit(::serde_json::json!("scenario"))),
                    ],
                ),
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_list_tags_for_resource(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "ListTagsForResource",
            params: scenario::map(vec![
                ("ResourceARN", scenario::context("namespace.arn")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_tags_for_resource()
                            .resource_arn(b.string("ResourceARN")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Tags",
                vec![
                    scenario::where_entry("$.Key", scenario::lit(::serde_json::json!("compat"))),
                    scenario::where_entry("$.Value", scenario::lit(::serde_json::json!("scenario"))),
                ],
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_untag_resource(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "UntagResource",
            params: scenario::map(vec![
                ("ResourceARN", scenario::context("namespace.arn")),
                ("TagKeys", scenario::lit(::serde_json::json!(["compat"]))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .untag_resource()
                            .resource_arn(b.string("ResourceARN")?)
                            .tag_keys("compat")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(30, 2000,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListTagsForResource",
                        params: scenario::map(vec![
                            ("ResourceARN", scenario::context("namespace.arn")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_tags_for_resource()
                                        .resource_arn(b.string("ResourceARN")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Tags",
                    vec![
                        scenario::where_entry("$.Key", scenario::lit(::serde_json::json!("compat"))),
                    ],
                ),
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_list_namespaces(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "ListNamespaces",
            params: scenario::lit(::serde_json::json!({})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_namespaces()
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Namespaces",
                vec![
                    scenario::where_entry("$.Id", scenario::context("namespace.id")),
                ],
            ),
        ],
    }
}

fn test_servicediscovery_gen_namespace_delete_namespace(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteNamespace",
            params: scenario::map(vec![("Id", scenario::context("namespace.id"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_namespace()
                            .id(b.string("Id")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(30, 2000,
                scenario::absent_by_error(
                    Call {
                        op: "GetNamespace",
                        params: scenario::map(vec![
                            ("Id", scenario::context("namespace.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_namespace()
                                        .id(b.string("Id")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("NamespaceNotFound", "NamespaceNotFound"),
                ),
            ),
        ],
    }
}

fn setup_servicediscovery_gen_instance(client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    vec![
        Call {
            op: "CreateHttpNamespace",
            params: scenario::map(vec![
                ("Description", scenario::lit(::serde_json::json!("compat scenario namespace"))),
                ("Name", scenario::name("ns")),
            ]),
            export: vec![
                ("namespace.operationId", "$.OperationId"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_http_namespace()
                            .description("compat scenario namespace")
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "GetOperation",
            params: scenario::map(vec![
                ("OperationId", scenario::context("namespace.operationId")),
            ]),
            export: vec![
                ("namespace.id", "$.Operation.Targets.NAMESPACE"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_operation()
                            .operation_id(b.string("OperationId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "CreateService",
            params: scenario::map(vec![
                ("Description", scenario::lit(::serde_json::json!("compat scenario service"))),
                ("Name", scenario::name("svc")),
                ("NamespaceId", scenario::context("namespace.id")),
                ("Type", scenario::lit(::serde_json::json!("HTTP"))),
            ]),
            export: vec![
                ("service.arn", "$.Service.Arn"),
                ("service.id", "$.Service.Id"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_service()
                            .description("compat scenario service")
                            .name(b.string("Name")?)
                            .namespace_id(b.string("NamespaceId")?)
                            .r#type(aws_sdk_servicediscovery::types::ServiceTypeOption::from("HTTP"))
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn teardown_servicediscovery_gen_instance(client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    vec![
        Call {
            op: "DeregisterInstance",
            params: scenario::map(vec![
                ("InstanceId", scenario::context("instance.id")),
                ("ServiceId", scenario::context("service.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .deregister_instance()
                            .instance_id(b.string("InstanceId")?)
                            .service_id(b.string("ServiceId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteService",
            params: scenario::map(vec![("Id", scenario::context("service.id"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_service()
                            .id(b.string("Id")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteNamespace",
            params: scenario::map(vec![("Id", scenario::context("namespace.id"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_namespace()
                            .id(b.string("Id")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_servicediscovery_gen_instance_register_instance(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "RegisterInstance",
            params: scenario::map(vec![
                ("Attributes", scenario::lit(::serde_json::json!({"AWS_INSTANCE_IPV4": "203.0.113.10"}))),
                ("InstanceId", scenario::name("i")),
                ("ServiceId", scenario::context("service.id")),
            ]),
            export: vec![
                ("instance.operationId", "$.OperationId"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .register_instance()
                            .attributes("AWS_INSTANCE_IPV4", "203.0.113.10")
                            .instance_id(b.string("InstanceId")?)
                            .service_id(b.string("ServiceId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.OperationId"),
            ]),
            scenario::eventually(30, 2000,
                scenario::readback(
                    Call {
                        op: "GetInstance",
                        params: scenario::map(vec![
                            ("InstanceId", scenario::name("i")),
                            ("ServiceId", scenario::context("service.id")),
                        ]),
                        export: vec![
                            ("instance.id", "$.Instance.Id"),
                        ],
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_instance()
                                        .instance_id(b.string("InstanceId")?)
                                        .service_id(b.string("ServiceId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::non_empty("$.Instance.Id"),
                    ],
                ),
            ),
            scenario::eventually(30, 2000,
                scenario::readback(
                    Call {
                        op: "GetInstance",
                        params: scenario::map(vec![
                            ("InstanceId", scenario::context("instance.id")),
                            ("ServiceId", scenario::context("service.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_instance()
                                        .instance_id(b.string("InstanceId")?)
                                        .service_id(b.string("ServiceId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::equals("$.Instance.Id", scenario::context("instance.id")),
                    ],
                ),
            ),
            scenario::eventually(30, 2000,
                scenario::list_contains(
                    Some(Call {
                        op: "ListInstances",
                        params: scenario::map(vec![
                            ("ServiceId", scenario::context("service.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_instances()
                                        .service_id(b.string("ServiceId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Instances",
                    vec![
                        scenario::where_entry("$.Id", scenario::context("instance.id")),
                    ],
                ),
            ),
        ],
    }
}

fn test_servicediscovery_gen_instance_get_instance(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "GetInstance",
            params: scenario::map(vec![
                ("InstanceId", scenario::context("instance.id")),
                ("ServiceId", scenario::context("service.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_instance()
                            .instance_id(b.string("InstanceId")?)
                            .service_id(b.string("ServiceId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.Instance.Id", scenario::context("instance.id")),
            ]),
        ],
    }
}

fn test_servicediscovery_gen_instance_list_instances(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "ListInstances",
            params: scenario::map(vec![
                ("ServiceId", scenario::context("service.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_instances()
                            .service_id(b.string("ServiceId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Instances",
                vec![
                    scenario::where_entry("$.Id", scenario::context("instance.id")),
                ],
            ),
        ],
    }
}

fn test_servicediscovery_gen_instance_deregister_instance(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "DeregisterInstance",
            params: scenario::map(vec![
                ("InstanceId", scenario::context("instance.id")),
                ("ServiceId", scenario::context("service.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .deregister_instance()
                            .instance_id(b.string("InstanceId")?)
                            .service_id(b.string("ServiceId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(30, 2000,
                scenario::absent_by_error(
                    Call {
                        op: "GetInstance",
                        params: scenario::map(vec![
                            ("InstanceId", scenario::context("instance.id")),
                            ("ServiceId", scenario::context("service.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_instance()
                                        .instance_id(b.string("InstanceId")?)
                                        .service_id(b.string("ServiceId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("InstanceNotFound", "InstanceNotFound"),
                ),
            ),
        ],
    }
}

fn setup_servicediscovery_gen_probe(_client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_servicediscovery_gen_probe(_client: &aws_sdk_servicediscovery::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn test_servicediscovery_gen_probe_get_instances_health_status(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "GetInstancesHealthStatus",
            params: scenario::lit(::serde_json::json!({"ServiceId": "srv-compatscenario00"})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_instances_health_status()
                            .service_id("srv-compatscenario00")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.Status"),
            ]),
        ],
    }
}

fn test_servicediscovery_gen_probe_get_operation(client: &aws_sdk_servicediscovery::Client) -> Test {
    Test {
        call: Call {
            op: "GetOperation",
            params: scenario::lit(::serde_json::json!({"OperationId": "compatscenariooperationnotfound0-00000000"})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_operation()
                            .operation_id("compatscenariooperationnotfound0-00000000")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.Operation"),
            ]),
        ],
    }
}
