// Command awsmodelgen converts pinned AWS Smithy JSON AST models into compact
// static operation metadata. It is an update-time tool; the emulator never
// reads model files at startup or while serving requests.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
)

func main() {
	modelsDir := flag.String("models", "", "directory containing Smithy JSON AST files")
	output := flag.String("output", "internal/awsapi/manifest.gen.go", "generated Go file")
	revision := flag.String("source-revision", "", "pinned upstream model revision")
	flag.Parse()
	if *modelsDir == "" || *revision == "" {
		fmt.Fprintln(os.Stderr, "awsmodelgen: -models and -source-revision are required")
		os.Exit(2)
	}
	if err := verifyModelRevision(*modelsDir, *revision); err != nil {
		fmt.Fprintf(os.Stderr, "awsmodelgen: %v\n", err)
		os.Exit(1)
	}
	contents, err := generateManifest(*modelsDir, *revision)
	if err != nil {
		fmt.Fprintf(os.Stderr, "awsmodelgen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, contents, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "awsmodelgen: write %s: %v\n", *output, err)
		os.Exit(1)
	}
}

type model struct {
	Shapes map[string]shape `json:"shapes"`
}

type shape struct {
	Type                 string                     `json:"type"`
	Version              string                     `json:"version"`
	Operations           []reference                `json:"operations"`
	CollectionOperations []reference                `json:"collectionOperations"`
	Resources            []reference                `json:"resources"`
	Create               *reference                 `json:"create"`
	Put                  *reference                 `json:"put"`
	Read                 *reference                 `json:"read"`
	Update               *reference                 `json:"update"`
	Delete               *reference                 `json:"delete"`
	List                 *reference                 `json:"list"`
	Traits               map[string]json.RawMessage `json:"traits"`
}

type reference struct {
	Target string `json:"target"`
}

type serviceTrait struct {
	SDKID string `json:"sdkId"`
}

type httpTrait struct {
	Method string `json:"method"`
	URI    string `json:"uri"`
}

type operation struct {
	Service, SDKID, APIVersion, Name, Protocol, TargetPrefix, HTTPMethod, URI string
	Protocols                                                                 []string
}

func generateManifest(modelsDir, revision string) ([]byte, error) {
	var operations []operation
	err := filepath.WalkDir(modelsDir, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".json" {
			return nil
		}
		parsed, err := parseModel(path)
		if err != nil {
			return err
		}
		operations = append(operations, parsed...)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("read models: %w", err)
	}
	if len(operations) == 0 {
		return nil, fmt.Errorf("no service operations found in %s", modelsDir)
	}
	sort.SliceStable(operations, func(i, j int) bool {
		if operations[i].Service != operations[j].Service {
			return operations[i].Service < operations[j].Service
		}
		if operations[i].Name != operations[j].Name {
			return operations[i].Name < operations[j].Name
		}
		if operations[i].APIVersion != operations[j].APIVersion {
			return operations[i].APIVersion < operations[j].APIVersion
		}
		return operations[i].URI < operations[j].URI
	})
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/awsmodelgen; DO NOT EDIT.\n")
	out.WriteString("package awsapi\n\n")
	fmt.Fprintf(&out, "const SourceRevision = %q\n\n", revision)
	out.WriteString("var manifest = []Operation{\n")
	for _, op := range operations {
		fmt.Fprintf(&out, "\t{Service: %q, SDKID: %q, APIVersion: %q, Name: %q, Protocol: Protocol%s, Protocols: %s, TargetPrefix: %q, HTTPMethod: %q, URI: %q},\n", op.Service, op.SDKID, op.APIVersion, op.Name, op.Protocol, protocolSetExpression(op.Protocols), op.TargetPrefix, op.HTTPMethod, op.URI)
	}
	out.WriteString("}\n")
	return out.Bytes(), nil
}

func parseModel(path string) ([]operation, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var parsed model
	if err := json.Unmarshal(contents, &parsed); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	var out []operation
	for shapeID, svc := range parsed.Shapes {
		if svc.Type != "service" {
			continue
		}
		rawTrait, ok := svc.Traits["aws.api#service"]
		if !ok {
			return nil, fmt.Errorf("%s: service %s has no aws.api#service trait", path, shapeID)
		}
		var trait serviceTrait
		if err := json.Unmarshal(rawTrait, &trait); err != nil {
			return nil, fmt.Errorf("parse service trait in %s: %w", path, err)
		}
		protocols := modelProtocols(svc.Traits)
		protocol := modelProtocol(svc.Traits)
		targetPrefix := targetPrefixForService(shapeID, protocols)
		refs, err := serviceOperationReferences(parsed.Shapes, shapeID, svc)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		for _, ref := range refs {
			op, ok := parsed.Shapes[ref.Target]
			if !ok || op.Type != "operation" {
				return nil, fmt.Errorf("%s: service %s references missing operation %s", path, shapeID, ref.Target)
			}
			var http httpTrait
			if raw, ok := op.Traits["smithy.api#http"]; ok {
				if err := json.Unmarshal(raw, &http); err != nil {
					return nil, fmt.Errorf("parse HTTP trait for %s: %w", ref.Target, err)
				}
			}
			out = append(out, operation{
				Service: strings.ToLower(strings.ReplaceAll(trait.SDKID, " ", "-")), SDKID: trait.SDKID,
				APIVersion: svc.Version, Name: shapeName(ref.Target), Protocol: protocol, Protocols: protocols,
				TargetPrefix: targetPrefix, HTTPMethod: http.Method, URI: http.URI,
			})
		}
	}
	return out, nil
}

func serviceOperationReferences(shapes map[string]shape, serviceID string, service shape) ([]reference, error) {
	refs := append([]reference(nil), service.Operations...)
	seenOperations := make(map[string]struct{}, len(refs))
	for _, ref := range refs {
		seenOperations[ref.Target] = struct{}{}
	}
	visitedResources := make(map[string]struct{})
	var visitResource func(reference) error
	visitResource = func(ref reference) error {
		if _, seen := visitedResources[ref.Target]; seen {
			return nil
		}
		visitedResources[ref.Target] = struct{}{}
		resource, ok := shapes[ref.Target]
		if !ok || resource.Type != "resource" {
			return fmt.Errorf("service %s references missing resource %s", serviceID, ref.Target)
		}
		operations := append([]reference{}, resource.Operations...)
		operations = append(operations, resource.CollectionOperations...)
		for _, lifecycle := range []*reference{resource.Create, resource.Put, resource.Read, resource.Update, resource.Delete, resource.List} {
			if lifecycle != nil {
				operations = append(operations, *lifecycle)
			}
		}
		for _, operation := range operations {
			if _, seen := seenOperations[operation.Target]; !seen {
				seenOperations[operation.Target] = struct{}{}
				refs = append(refs, operation)
			}
		}
		for _, nested := range resource.Resources {
			if err := visitResource(nested); err != nil {
				return err
			}
		}
		return nil
	}
	for _, resource := range service.Resources {
		if err := visitResource(resource); err != nil {
			return nil, err
		}
	}
	return refs, nil
}

func verifyModelRevision(modelsDir, revision string) error {
	cmd := exec.Command("git", "-C", filepath.Dir(modelsDir), "rev-parse", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("read model checkout revision: %w", err)
	}
	if got := strings.TrimSpace(string(output)); got != revision {
		return fmt.Errorf("model checkout revision %s does not match -source-revision %s", got, revision)
	}
	return nil
}

func modelProtocol(traits map[string]json.RawMessage) string {
	protocols := modelProtocols(traits)
	if len(protocols) == 0 {
		return "Unknown"
	}
	return protocols[0]
}

func modelProtocols(traits map[string]json.RawMessage) []string {
	// Smithy permits protocol extension traits to coexist. Keep this ordered so
	// generated output is reproducible even if a model exposes more than one
	// recognized protocol. The registry phase will retain the complete trait set
	// when protocol negotiation needs it.
	var protocols []string
	for _, candidate := range []struct {
		trait    string
		protocol string
	}{
		{"aws.protocols#awsJson1_1", "AWSJSON11"},
		{"aws.protocols#awsJson1_0", "AWSJSON10"},
		{"aws.protocols#ec2Query", "EC2Query"},
		{"aws.protocols#awsQuery", "AWSQuery"},
		{"aws.protocols#restJson1", "RESTJSON"},
		{"aws.protocols#restXml", "RESTXML"},
		{"smithy.protocols#rpcv2Cbor", "RPCV2CBOR"},
		{"smithy.protocols#rpcv2Json", "RPCV2JSON"},
	} {
		if _, ok := traits[candidate.trait]; ok {
			protocols = append(protocols, candidate.protocol)
		}
	}
	return protocols
}

func hasAWSJSONProtocol(protocols []string) bool {
	return slices.Contains(protocols, "AWSJSON10") || slices.Contains(protocols, "AWSJSON11")
}

// targetPrefixOverrides covers AWS JSON targets whose legacy wire prefix cannot
// be reconstructed from the public Smithy service shape name alone.
var targetPrefixOverrides = map[string]string{
	"com.amazonaws.cloudtrail#CloudTrail_20131101": "com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.",
}

func targetPrefixForService(shapeID string, protocols []string) string {
	if !hasAWSJSONProtocol(protocols) {
		return ""
	}
	if prefix, ok := targetPrefixOverrides[shapeID]; ok {
		return prefix
	}
	return shapeName(shapeID) + "."
}

func protocolSetExpression(protocols []string) string {
	if len(protocols) == 0 {
		return "0"
	}
	sets := make([]string, len(protocols))
	for i, protocol := range protocols {
		sets[i] = "Protocols" + protocol
	}
	return strings.Join(sets, " | ")
}

func shapeName(id string) string { return id[strings.LastIndex(id, "#")+1:] }
