// Command awsmodelgen converts pinned AWS Smithy JSON AST models into compact
// static operation metadata. It is an update-time tool; the emulator never
// reads model files at startup or while serving requests.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	modelsDir := flag.String("models", "models/aws", "directory containing Smithy JSON AST files")
	output := flag.String("output", "internal/awsapi/manifest.gen.go", "generated Go file")
	revision := flag.String("source-revision", "", "pinned upstream model revision")
	flag.Parse()
	if *revision == "" {
		fmt.Fprintln(os.Stderr, "awsmodelgen: -source-revision is required")
		os.Exit(2)
	}
	contents, err := generateManifest(*modelsDir, *revision)
	if err != nil {
		fmt.Fprintf(os.Stderr, "awsmodelgen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, contents, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "awsmodelgen: write %s: %v\n", *output, err)
		os.Exit(1)
	}
}

type model struct {
	Shapes map[string]shape `json:"shapes"`
}

type shape struct {
	Type       string                     `json:"type"`
	Version    string                     `json:"version"`
	Operations []reference                `json:"operations"`
	Traits     map[string]json.RawMessage `json:"traits"`
}

type reference struct {
	Target string `json:"target"`
}

type serviceTrait struct {
	SDKID          string `json:"sdkId"`
	EndpointPrefix string `json:"endpointPrefix"`
}

type httpTrait struct {
	Method string `json:"method"`
	URI    string `json:"uri"`
}

type operation struct {
	Service, SDKID, APIVersion, Name, Protocol, TargetPrefix, HTTPMethod, URI string
}

func generateManifest(modelsDir, revision string) ([]byte, error) {
	var operations []operation
	err := filepath.WalkDir(modelsDir, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".json" {
			return nil
		}
		parsed, err := parseModel(path)
		if err != nil {
			return err
		}
		operations = append(operations, parsed...)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("read models: %w", err)
	}
	sort.Slice(operations, func(i, j int) bool {
		if operations[i].Service != operations[j].Service {
			return operations[i].Service < operations[j].Service
		}
		return operations[i].Name < operations[j].Name
	})
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/awsmodelgen; DO NOT EDIT.\n")
	out.WriteString("package awsapi\n\n")
	fmt.Fprintf(&out, "const SourceRevision = %q\n\n", revision)
	out.WriteString("var Manifest = []Operation{\n")
	for _, op := range operations {
		fmt.Fprintf(&out, "\t{Service: %q, SDKID: %q, APIVersion: %q, Name: %q, Protocol: Protocol%s, TargetPrefix: %q, HTTPMethod: %q, URI: %q},\n", op.Service, op.SDKID, op.APIVersion, op.Name, op.Protocol, op.TargetPrefix, op.HTTPMethod, op.URI)
	}
	out.WriteString("}\n")
	return out.Bytes(), nil
}

func parseModel(path string) ([]operation, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var parsed model
	if err := json.Unmarshal(contents, &parsed); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	var out []operation
	for shapeID, svc := range parsed.Shapes {
		if svc.Type != "service" {
			continue
		}
		var trait serviceTrait
		if err := json.Unmarshal(svc.Traits["aws.api#service"], &trait); err != nil {
			return nil, fmt.Errorf("parse service trait in %s: %w", path, err)
		}
		protocol := modelProtocol(svc.Traits)
		for _, ref := range svc.Operations {
			op, ok := parsed.Shapes[ref.Target]
			if !ok || op.Type != "operation" {
				return nil, fmt.Errorf("%s: service %s references missing operation %s", path, shapeID, ref.Target)
			}
			var http httpTrait
			if raw, ok := op.Traits["smithy.api#http"]; ok {
				if err := json.Unmarshal(raw, &http); err != nil {
					return nil, fmt.Errorf("parse HTTP trait for %s: %w", ref.Target, err)
				}
			}
			out = append(out, operation{
				Service: strings.ToLower(strings.ReplaceAll(trait.SDKID, " ", "-")), SDKID: trait.SDKID,
				APIVersion: svc.Version, Name: shapeName(ref.Target), Protocol: protocol,
				TargetPrefix: trait.EndpointPrefix, HTTPMethod: http.Method, URI: http.URI,
			})
		}
	}
	return out, nil
}

func modelProtocol(traits map[string]json.RawMessage) string {
	// Smithy permits protocol extension traits to coexist. Keep this ordered so
	// generated output is reproducible even if a model exposes more than one
	// recognized protocol. The registry phase will retain the complete trait set
	// when protocol negotiation needs it.
	for _, candidate := range []struct {
		trait    string
		protocol string
	}{
		{"aws.protocols#awsJson1_1", "AWSJSON11"},
		{"aws.protocols#awsJson1_0", "AWSJSON10"},
		{"aws.protocols#ec2Query", "EC2Query"},
		{"aws.protocols#awsQuery", "AWSQuery"},
		{"aws.protocols#restJson1", "RESTJSON"},
		{"aws.protocols#restXml", "RESTXML"},
	} {
		if _, ok := traits[candidate.trait]; ok {
			return candidate.protocol
		}
	}
	return "Unknown"
}

func shapeName(id string) string { return id[strings.LastIndex(id, "#")+1:] }
