//go:build dev

package main

import (
	"encoding/json"
	"go/format"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

// The Go emitter, over the same hermetic fixture the rest of the generator's
// tests use (testdata/shapes/widgets.json + testdata/recipes/widgets.json).
// Nothing here reads the committed corpus, opens a network connection or
// compiles the emitted source; the emitted corpus is proved to compile by the
// go-sdk suite's own build.

// goldenPath is the emitted source for the fixture service. It carries a
// .golden suffix so the Go tool never treats it as part of any package: it
// imports an SDK package for a service that does not exist.
const goldenPath = "testdata/golden/scenarios_widgets_gen.go.golden"

// fixtureGoTypes resolves field types from testdata/awssdk, a checked-in
// stand-in for the AWS SDK for Go v2 that declares the fixture service's input
// structs under the SDK's own module path. That is what makes these tests
// hermetic: they type-check real Go, from a module inside the repository, with
// no module cache and no network. Only `make generate-compat-model` and
// `make compat-model-check` read the vendored SDK itself, out of the go-sdk
// suite's go.mod.
//
// One loader serves the whole test binary because a load starts a `go list`
// subprocess, and the loader is safe to share.
var fixtureGoTypes = sync.OnceValue(func() *goSDKTypes {
	return newGoSDKTypes(filepath.Join("testdata", "awssdk"))
})

func TestEmitGo_matchesTheGoldenSource(t *testing.T) {
	// Given: the fixture service, generated.
	_, gen := generateFixture(t)

	// When: it is emitted as Go.
	emission, err := emitGo(gen, fixtureGoTypes())
	if err != nil {
		t.Fatalf("emitGo: %v", err)
	}

	// Then: byte for byte what is committed.
	if emission.Path != "compat/suites/go-sdk/internal/groups/scenarios_widgets_gen.go" {
		t.Errorf("emitted path = %s", emission.Path)
	}
	assertGolden(t, goldenPath, emission.Contents)
}

func TestEmitGo_isDeterministicAndGofmtClean(t *testing.T) {
	_, gen := generateFixture(t)

	first, err := emitGo(gen, fixtureGoTypes())
	if err != nil {
		t.Fatalf("emitGo: %v", err)
	}
	second, err := emitGo(gen, fixtureGoTypes())
	if err != nil {
		t.Fatalf("emitGo: %v", err)
	}
	if string(first.Contents) != string(second.Contents) {
		t.Error("two emissions of one scenario differ; the byte-identical regeneration gate would fail at random")
	}
	// gofmt is applied inside emitGo, so this is the belt to that braces: it
	// proves the committed bytes are a fixed point rather than merely parseable.
	formatted, err := format.Source(first.Contents)
	if err != nil {
		t.Fatalf("emitted source does not parse: %v", err)
	}
	if string(formatted) != string(first.Contents) {
		t.Error("emitted source is not gofmt-clean")
	}
}

// TestEmitGo_emitsEveryGroupAndTest keeps the emitted registrations in step
// with the scenario. A test the emitter silently dropped would report as a
// hard failure in the suite (the generated-no-backend rule), which is loud but
// late.
func TestEmitGo_emitsEveryGroupAndTest(t *testing.T) {
	_, gen := generateFixture(t)
	emission, err := emitGo(gen, fixtureGoTypes())
	if err != nil {
		t.Fatalf("emitGo: %v", err)
	}
	source := string(emission.Contents)
	for _, g := range gen.scenario.Groups {
		for _, tc := range g.Tests {
			key := `"` + g.Name + ":" + tc.Name + `"`
			if !strings.Contains(source, key) {
				t.Errorf("no impl registered under %s", key)
			}
			if !strings.Contains(source, "func (g *widgetsScenarios) "+goNameTestMethod(g.Name, tc.Name)+"(") {
				t.Errorf("no function emitted for %s/%s", g.Name, tc.Name)
			}
		}
		// Every group registers both hooks, even the probe group whose two
		// lists are empty: an empty phase is a no-op, not a missing one.
		for _, method := range []string{goNameSetupMethod(g.Name), goNameTeardownMethod(g.Name)} {
			if !strings.Contains(source, "func (g *widgetsScenarios) "+method+"(") {
				t.Errorf("no %s emitted for %s", method, g.Name)
			}
		}
	}
	if !strings.Contains(source, "// Code generated by cmd/compatgen; DO NOT EDIT.") {
		t.Error("the generated-file marker is missing")
	}
}

// TestEmitGo_refusesWhatItCannotSpell pins every refusal this backend
// introduces, and what each costs: the group leaves the go-sdk column rather
// than being emitted as a guess or dropped silently.
//
// None of these arises from a committed scenario — the recipes and the
// upstream refusals see to that — so each is constructed against
// testdata/awssdk, whose api.go declares the field types that produce them.
// Three of the five are only reachable at all because the emitter now reads
// the SDK: under the reflective binder a renamed member and a union-typed
// field compiled and failed on the wire, and a value-typed zero was sent as
// nothing at all.
func TestEmitGo_refusesWhatItCannotSpell(t *testing.T) {
	for _, tc := range []struct {
		name       string
		op         string
		params     map[string]any
		wantMember string
		wantDetail string
	}{
		{
			// The fixture models ListWidgets with an optional CreatedAfter and
			// the SDK gives it a *time.Time. The modeled kind answers first,
			// because "a timestamp" is what a recipe author needs to read.
			name:       "a member whose modeled kind has no IR literal",
			op:         "ListWidgets",
			params:     map[string]any{"CreatedAfter": "2026-09-06T00:00:00Z"},
			wantMember: "CreatedAfter",
			wantDetail: "timestamp",
		},
		{
			// PurgeWidgets is modeled and the fixture SDK does not declare its
			// input, which is what an SDK older than the pinned model looks
			// like.
			name:       "an operation the vendored SDK does not have",
			op:         "PurgeWidgets",
			params:     nil,
			wantMember: "PurgeWidgetsInput",
			wantDetail: "older than the pinned model",
		},
		{
			// smithy-go's rename rule is capitalization plus reserved-word and
			// collision handling. Reproducing only half of it is what made this
			// case a run-time "has no settable member" and a red compat result.
			name:       "a member the SDK has no field for",
			op:         "FreezeWidget",
			params:     map[string]any{"WidgetId": "w-1"},
			wantMember: "WidgetId",
			wantDetail: "has no field for member",
		},
		{
			// The pinned snapshot calls ListGauges' Cursor a string; the
			// fixture SDK makes it a union, as a service really can. The SDK's
			// declaration is the authority, and no literal builds an interface.
			name:       "a field type no Go literal builds",
			op:         "ListGauges",
			params:     map[string]any{"Cursor": "page-2"},
			wantMember: "Cursor",
			wantDetail: "no Go literal builds a types.GaugeCursor",
		},
		{
			// compat/model/README.md § Values: the SDK serializes a value-typed
			// member only when it differs from the zero value, so a scenario
			// asking for 0 silently asks for the service's own default and the
			// backends stop agreeing about what was sent.
			name:       "a value-typed member set to its zero value",
			op:         "RotateWidget",
			params:     map[string]any{"Angle": 0, "WidgetId": "w-1"},
			wantMember: "Angle",
			wantDetail: "§ Values",
		},
		{
			// A deferred expression resolves into one scalar slot. A whole list
			// from a $ref has no typed slot to land in, and inventing one would
			// mean converting []any to []string at run time — reflection, by
			// another name.
			name:       "an expression bound to a composite member",
			op:         "UntagWidget",
			params:     map[string]any{"TagKeys": map[string]any{"$ref": "tags.keys"}},
			wantMember: "TagKeys",
			wantDetail: "can only be bound to a scalar member",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			// Given: a group whose call carries that member.
			_, gen := generateFixture(t)
			const name = "widgets-gen-refused"
			gen.scenario.Groups = append(gen.scenario.Groups, group{
				Name: name,
				Kind: groupLifecycle,
				Tests: []test{newTest(tc.op, tc.op, call{Op: tc.op, Params: tc.params},
					responseField(checks("$.Widgets", isList())))},
			})

			// When: the service is emitted.
			emission, err := emitGo(gen, fixtureGoTypes())
			if err != nil {
				t.Fatalf("emitGo: %v", err)
			}

			// Then: the group is not in the emitted source, it is reported as
			// unable so the registry scopes it away from go-sdk, and the
			// refusal names the member and says why.
			if strings.Contains(string(emission.Contents), name) {
				t.Error("a group the emitter cannot spell was emitted anyway")
			}
			if !emission.Refused[name] {
				t.Fatal("the refused group was not reported as unable")
			}
			if len(emission.Gaps) != 1 {
				t.Fatalf("gaps = %+v, want one", emission.Gaps)
			}
			got := emission.Gaps[0]
			if got.Reason != goEmitReason+":"+tc.wantMember || got.Operation != tc.op || got.Group != name {
				t.Errorf("gap = %+v", got)
			}
			if !strings.Contains(got.Detail, tc.wantDetail) {
				t.Errorf("gap detail does not say why: %q, want it to mention %q", got.Detail, tc.wantDetail)
			}

			// And: the emitted file still carries no import it stopped needing
			// when the group was dropped.
			if strings.Contains(string(emission.Contents), `"github.com/aws/aws-sdk-go-v2/service/widgets/types"`) &&
				!strings.Contains(string(emission.Contents), "types.") {
				t.Error("the refused group left an unused import behind")
			}
		})
	}
}

// TestGoSpeller_spellsEveryShapeOfField is the type-spelling table read back,
// one row at a time, against the fixture SDK's real Go types. The golden file
// proves what a whole service comes out as; this says which rule produced each
// piece of it, and it is where a new rule is added with its own row.
func TestGoSpeller_spellsEveryShapeOfField(t *testing.T) {
	svc, err := fixtureGoTypes().service("Widgets")
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		name   string
		op     string
		member string
		value  string
		want   string
	}{
		{"a pointer scalar", "CreateWidget", "Description", `"one"`, `aws.String("one")`},
		{"an enum", "CreateWidget", "Color", `"blue"`, `types.Color("blue")`},
		{"a value-typed number", "RotateWidget", "Angle", `45`, `45`},
		{"a string map", "TagWidget", "Tags", `{"compat":"scenario"}`, `map[string]string{"compat": "scenario"}`},
		{"a list of strings", "UntagWidget", "TagKeys", `["compat"]`, `[]string{"compat"}`},
		{
			// The element type is stated by the composite, so the struct
			// literal drops its own name — as a human would write it.
			"a list of structures", "TagSprocket", "Tags", `[{"Key":"k","Value":"v"}]`,
			`[]types.SprocketTag{{Key: aws.String("k"), Value: aws.String("v")}}`,
		},
		{
			"an expression into a pointer", "GetWidget", "WidgetId", `{"$ref":"widget.id"}`,
			`aws.String(scenario.Bind[string](b, "WidgetId", scenario.Ref("widget.id")))`,
		},
		{
			// The Bind result is a string, not a types.Color, so the
			// conversion stays even though the enum's own type is named.
			"an expression into an enum", "CreateWidget", "Color", `{"$name":"c"}`,
			`types.Color(scenario.Bind[string](b, "Color", scenario.Name("c")))`,
		},
		{
			"an expression inside a composite", "TagWidget", "Tags", `{"compat":{"$ref":"t"}}`,
			`map[string]string{"compat": scenario.Bind[string](b, "Tags", scenario.Ref("t"))}`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			sp := &goSpeller{svc: svc}
			field, err := sp.field(tc.op, tc.member)
			if err != nil {
				t.Fatal(err)
			}
			var v any
			if err := decodeStrict([]byte(tc.value), &v); err != nil {
				t.Fatal(err)
			}
			got, err := sp.value(field.Type(), v, tc.member, "", false)
			if err != nil {
				t.Fatalf("spelling %s.%s: %v", tc.op, tc.member, err)
			}
			if got != tc.want {
				t.Errorf("%s.%s = %s, want %s", tc.op, tc.member, got, tc.want)
			}
			// An import is recorded only when the spelling actually named it,
			// which is what keeps an emitted file free of unused imports.
			if sp.usesAWS != strings.Contains(tc.want, "aws.") {
				t.Errorf("usesAWS = %v for %s", sp.usesAWS, got)
			}
			if sp.usesTypes != strings.Contains(tc.want, "types.") {
				t.Errorf("usesTypes = %v for %s", sp.usesTypes, got)
			}
		})
	}
}

// TestBuildRegistry_scopesARefusedGroupAwayFromItsBackend is the other half of
// that refusal: `suites` is derived from backend availability, so a backend
// that cannot execute a group must not be listed against it — otherwise the
// loader's generated-no-backend rule turns the refusal into a hard failure.
func TestBuildRegistry_scopesARefusedGroupAwayFromItsBackend(t *testing.T) {
	_, gen := generateFixture(t)
	units := []*generation{gen}
	backends := []string{"cli", "go-sdk", "python-sdk"}
	refused := gen.scenario.Groups[0].Name

	reg := buildRegistry(units, backends, nil, unableSuites{refused: {"go-sdk": true}})
	for _, g := range reg.Groups {
		want := backends
		if g.Name == refused {
			want = []string{"cli", "python-sdk"}
		}
		if strings.Join(g.Suites, ",") != strings.Join(want, ",") {
			t.Errorf("group %s suites = %v, want %v", g.Name, g.Suites, want)
		}
	}

	// And a group no backend can execute is left out entirely rather than
	// written with an empty `suites`, which the schema refuses.
	none := unableSuites{refused: {"cli": true, "go-sdk": true, "python-sdk": true}}
	for _, g := range buildRegistry(units, backends, nil, none).Groups {
		if g.Name == refused {
			t.Error("a group no suite can execute was still registered")
		}
	}
}

// TestEmitGoIndex_isTheOnlyHandEditFreeRegistrationPoint pins both halves of
// the index: it lists what was emitted, and it still compiles when nothing was.
func TestEmitGoIndex_listsEveryEmittedServiceAndCompilesWhenEmpty(t *testing.T) {
	full, err := emitGoIndex([]string{"sqs", "organizations"})
	if err != nil {
		t.Fatal(err)
	}
	source := string(full)
	if !strings.Contains(source, "ScenariosOrganizations(c),") || !strings.Contains(source, "ScenariosSqs(c),") {
		t.Errorf("index does not name both services:\n%s", source)
	}
	if strings.Index(source, "ScenariosOrganizations") > strings.Index(source, "ScenariosSqs") {
		t.Error("the index is not sorted; regeneration would depend on recipe read order")
	}

	empty, err := emitGoIndex(nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(empty), "return nil") {
		t.Errorf("the empty index does not compile to an empty list:\n%s", empty)
	}
	if strings.Contains(string(empty), "c *clients.Clients") {
		t.Error("the empty index names an unused parameter, which does not compile")
	}
}

// TestGoValue_coversTheIRsValueGrammar keeps the naming table total: every form
// the IR admits has a Go expression, and nothing else does.
func TestGoValue_coversTheIRsValueGrammar(t *testing.T) {
	for _, tc := range []struct {
		name string
		in   string
		want string
	}{
		{"a string", `"hello"`, `"hello"`},
		{"a number", `30`, `30`},
		{"a boolean", `false`, `false`},
		{"null", `null`, `nil`},
		{"a list", `["a","b"]`, `[]any{"a", "b"}`},
		{"an object", `{"K":"v"}`, `map[string]any{"K": "v"}`},
		{"$name", `{"$name":"q"}`, `scenario.Name("q")`},
		{"$ref", `{"$ref":"queue.url"}`, `scenario.Ref("queue.url")`},
		{"$lit", `{"$lit":{"$weird":1}}`, `scenario.Lit(map[string]any{"$weird": 1})`},
		{"$concat", `{"$concat":["a",{"$ref":"q.u"}]}`, `scenario.Concat("a", scenario.Ref("q.u"))`},
		{"$index", `{"$index":[{"$ref":"q.urls"},1]}`, `scenario.Index(scenario.Ref("q.urls"), 1)`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var v any
			if err := decodeStrict([]byte(tc.in), &v); err != nil {
				t.Fatal(err)
			}
			got, err := goValue(v, "")
			if err != nil {
				t.Fatalf("goValue(%s): %v", tc.in, err)
			}
			if got != tc.want {
				t.Errorf("goValue(%s) = %s, want %s", tc.in, got, tc.want)
			}
		})
	}

	// A value outside the grammar has no expression, and says so rather than
	// rendering something that would not compile.
	if _, err := goValue(struct{}{}, ""); err == nil {
		t.Error("a value outside the IR's grammar was rendered")
	}
}

// TestGoValue_wrapsAWideComposite keeps a generated file reviewable: gofmt
// does not break a long literal, so the emitter does.
func TestGoValue_wrapsAWideComposite(t *testing.T) {
	var v any
	if err := json.Unmarshal([]byte(`{"AVeryLongMemberNameIndeed":"and a value long enough to pass the budget","Another":"one"}`), &v); err != nil {
		t.Fatal(err)
	}
	got, err := goValue(v, "\t")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "\n") {
		t.Errorf("a composite past the width budget stayed on one line:\n%s", got)
	}
}

// TestGoMethodNamesAreUnique refuses two names that fold to one Go identifier
// before the suite fails to build with no indication of which pair caused it.
func TestGoMethodNamesAreUnique(t *testing.T) {
	groups := []group{
		{Name: "svc-gen-a-b", Tests: []test{{Name: "C"}}},
		{Name: "svc-gen-a", Tests: []test{{Name: "BC"}}},
	}
	err := goMethodNamesAreUnique("svc", groups)
	if err == nil {
		t.Fatal("two colliding method names were accepted")
	}
	for _, want := range []string{"svc-gen-a-b/C", "svc-gen-a/BC", "testSvcGenABC"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the collision message lacks %q: %v", want, err)
		}
	}
}

// TestExplainGoRendersTheEmittedCall is the definition-of-done item that there
// is one naming table: `-explain -lang go` must print the statements the
// emitter writes, not a second description of them. It holds through the typed
// spelling too — both go through goInputLines, over the same resolved SDK
// types — which is what stops the explanation claiming a pointer where the
// vendored SDK gave a value.
func TestExplainGoRendersTheEmittedCall(t *testing.T) {
	_, gen := generateFixture(t)
	g, tc, ok := gen.scenario.findTest("widgets-gen-widget", "CreateWidget")
	if !ok {
		t.Fatal("fixture has no CreateWidget")
	}
	explained := renderGo(fixtureRenderEnv(gen), gen.scenario, g, tc)

	emission, err := emitGo(gen, fixtureGoTypes())
	if err != nil {
		t.Fatalf("emitGo: %v", err)
	}
	emitted := string(emission.Contents)

	svc, err := fixtureGoTypes().service(gen.scenario.Client.SDKID)
	if err != nil {
		t.Fatal(err)
	}
	lines, err := goInputLines(&goSpeller{svc: svc}, tc.Call.Op, tc.Call.Params, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) < 2 {
		t.Fatalf("CreateWidget renders %d line(s); the fixture no longer exercises member binding", len(lines))
	}
	for _, line := range lines {
		if !strings.Contains(explained, line) {
			t.Errorf("-explain -lang go does not render %q:\n%s", line, explained)
		}
		if !strings.Contains(emitted, line) {
			t.Errorf("the emitted source does not contain %q", line)
		}
	}
}
