//go:build dev

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The Java emitter, over the same hermetic fixture the rest of the generator's
// tests use (testdata/shapes/widgets.json + testdata/recipes/widgets.json).
// Nothing here reads the committed corpus, opens a network connection or
// compiles the emitted source; the emitted corpus is proved to compile by the
// java-sdk suite's own `mvn package`.
//
// Unlike the Go emitter's tests these need no stand-in SDK: the Java spelling
// is derived from the pinned model, which the fixture already carries. That is
// the whole content of the plan's binding decision for this backend, and it is
// what makes these tests hermetic without a second module.

// javaGoldenPath is the emitted source for the fixture service. It carries a
// .golden suffix so javac never sees it: it names an SDK package for a service
// that does not exist.
const javaGoldenPath = "testdata/golden/ScenariosWidgetsGen.java.golden"

func TestEmitJava_matchesTheGoldenSource(t *testing.T) {
	// Given: the fixture service, generated.
	_, gen := generateFixture(t)

	// When: it is emitted as Java.
	emission, err := emitJava(gen)
	if err != nil {
		t.Fatalf("emitJava: %v", err)
	}

	// Then: byte for byte what is committed.
	want := "compat/suites/java-sdk/src/main/java/io/overcast/compat/groups/ScenariosWidgetsGen.java"
	if emission.Path != want {
		t.Errorf("emitted path = %s, want %s", emission.Path, want)
	}
	if updateGolden() {
		if err := os.MkdirAll(filepath.Dir(javaGoldenPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(javaGoldenPath, emission.Contents, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Fatalf("golden file rewritten; re-run without OVERCAST_UPDATE_GOLDEN and read the diff")
	}
	golden, err := os.ReadFile(javaGoldenPath)
	if err != nil {
		t.Fatalf("read golden: %v (set OVERCAST_UPDATE_GOLDEN=1 to write it)", err)
	}
	if string(emission.Contents) != string(golden) {
		t.Errorf("emitted source differs from %s; set OVERCAST_UPDATE_GOLDEN=1 to update it after reading the diff\n--- got ---\n%s", javaGoldenPath, emission.Contents)
	}
}

func TestEmitJava_isDeterministic(t *testing.T) {
	_, gen := generateFixture(t)

	first, err := emitJava(gen)
	if err != nil {
		t.Fatalf("emitJava: %v", err)
	}
	second, err := emitJava(gen)
	if err != nil {
		t.Fatalf("emitJava: %v", err)
	}
	if string(first.Contents) != string(second.Contents) {
		t.Error("two emissions of one scenario differ; the byte-identical regeneration gate would fail at random")
	}
	if !strings.HasSuffix(string(first.Contents), "}\n") {
		t.Error("the emitted file does not end with exactly one trailing newline after the class")
	}
	if strings.Contains(string(first.Contents), "\r") {
		t.Error("the emitted file carries CRLF line endings")
	}
}

// TestEmitJava_emitsEveryGroupAndTest keeps the emitted registrations in step
// with the scenario. A test the emitter silently dropped would report as a hard
// failure in the suite (the generated-no-backend rule), which is loud but late.
func TestEmitJava_emitsEveryGroupAndTest(t *testing.T) {
	_, gen := generateFixture(t)
	emission, err := emitJava(gen)
	if err != nil {
		t.Fatalf("emitJava: %v", err)
	}
	source := string(emission.Contents)
	for _, g := range gen.scenario.Groups {
		for _, tc := range g.Tests {
			key := `"` + g.Name + ":" + tc.Name + `"`
			if !strings.Contains(source, key) {
				t.Errorf("no impl registered under %s", key)
			}
			if !strings.Contains(source, "private void "+javaNameTestMethod(g.Name, tc.Name)+"(TestContext t)") {
				t.Errorf("no method emitted for %s/%s", g.Name, tc.Name)
			}
		}
		// Every group registers both hooks, even the probe group whose two lists
		// are empty: an empty phase is a no-op, not a missing one.
		for _, method := range []string{javaNameSetupMethod(g.Name), javaNameTeardownMethod(g.Name)} {
			if !strings.Contains(source, "private void "+method+"(TestContext t)") {
				t.Errorf("no %s emitted for %s", method, g.Name)
			}
		}
	}
	if !strings.Contains(source, "// Code generated by cmd/compatgen; DO NOT EDIT.") {
		t.Error("the generated-file marker is missing")
	}
}

// TestEmitJava_refusesWhatItCannotSpell pins every refusal this backend
// introduces, and what each costs: the group leaves the java-sdk column rather
// than being emitted as a guess or dropped silently.
//
// None arises from a committed scenario — the recipes and the upstream refusals
// see to that — so each is constructed against the fixture model.
func TestEmitJava_refusesWhatItCannotSpell(t *testing.T) {
	for _, tc := range []struct {
		name       string
		op         string
		params     map[string]any
		wantMember string
		wantDetail string
	}{
		{
			// The fixture models ListWidgets with an optional CreatedAfter
			// targeting smithy.api#Timestamp. Blobs, documents and unions reach
			// the same branch; a timestamp is the one the fixture carries.
			name:       "a member whose modeled kind has no IR literal",
			op:         "ListWidgets",
			params:     map[string]any{"CreatedAfter": "2026-09-06T00:00:00Z"},
			wantMember: "CreatedAfter",
			wantDetail: "no Java value expression for a timestamp member",
		},
		{
			// A recipe naming a member the operation's input does not declare.
			// The binder refuses one upstream; this is the backstop, and it is
			// also what an operation with a unit input looks like.
			name:       "a member the model does not give the operation",
			op:         "RotateWidget",
			params:     map[string]any{"Nonexistent": "x", "WidgetId": "w-1"},
			wantMember: "Nonexistent",
			wantDetail: "no member \"Nonexistent\"",
		},
		{
			// "30" is not 30 anywhere else in the IR, and accepting it here
			// would let a wrong literal through into a typed slot.
			name:       "a literal of the wrong JSON type for the member",
			op:         "RotateWidget",
			params:     map[string]any{"Angle": "45", "WidgetId": "w-1"},
			wantMember: "Angle",
			wantDetail: "wants a number, got a string",
		},
		{
			// A deferred expression resolves into one scalar slot. A whole list
			// from a $ref has no typed slot to land in, and inventing one would
			// mean converting a document to a List<String> at run time —
			// reflection, by another name.
			name:       "an expression bound to a composite member",
			op:         "UntagWidget",
			params:     map[string]any{"TagKeys": map[string]any{"$ref": "tags.keys"}},
			wantMember: "TagKeys",
			wantDetail: "can only be bound to a scalar member",
		},
		{
			// The AWS SDK for Java v2 spells "unset" as null, so there is no
			// setter argument that sends an explicit JSON null: a scenario
			// asking for one would silently omit the member instead.
			name:       "an explicit null",
			op:         "UpdateWidget",
			params:     map[string]any{"Description": nil, "WidgetId": "w-1"},
			wantMember: "Description",
			wantDetail: "cannot send an explicit null",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			// Given: a group whose call carries that member.
			_, gen := generateFixture(t)
			const name = "widgets-gen-refused"
			gen.scenario.Groups = append(gen.scenario.Groups, group{
				Name: name,
				Kind: groupLifecycle,
				Tests: []test{newTest(tc.op, tc.op, call{Op: tc.op, Params: tc.params},
					responseField(checks("$.Widgets", isList())))},
			})

			// When: the service is emitted.
			emission, err := emitJava(gen)
			if err != nil {
				t.Fatalf("emitJava: %v", err)
			}

			// Then: the group is not in the emitted source, it is reported as
			// unable so the registry scopes it away from java-sdk, and the
			// refusal names the member and says why.
			if strings.Contains(string(emission.Contents), name) {
				t.Error("a group the emitter cannot spell was emitted anyway")
			}
			if !emission.Refused[name] {
				t.Fatal("the refused group was not reported as unable")
			}
			if len(emission.Gaps) != 1 {
				t.Fatalf("gaps = %+v, want one", emission.Gaps)
			}
			got := emission.Gaps[0]
			if got.Reason != javaEmitReason+":"+tc.wantMember || got.Operation != tc.op || got.Group != name {
				t.Errorf("gap = %+v", got)
			}
			if !strings.Contains(got.Detail, tc.wantDetail) {
				t.Errorf("gap detail does not say why: %q, want it to mention %q", got.Detail, tc.wantDetail)
			}
		})
	}
}

// TestJavaSpeller_spellsEveryShapeOfMember is the type-spelling table read back,
// one row at a time, against the fixture's modeled shapes. The golden file
// proves what a whole service comes out as; this says which rule produced each
// piece of it, and it is where a new rule is added with its own row.
func TestJavaSpeller_spellsEveryShapeOfMember(t *testing.T) {
	f, _ := generateFixture(t)
	for _, tc := range []struct {
		name      string
		op        string
		member    string
		value     string
		want      string
		wantTypes []string
	}{
		{"a string", "CreateWidget", "Description", `"one"`, `"one"`, nil},
		{"an enum", "CreateWidget", "Color", `"blue"`, `Color.fromValue("blue")`, []string{"Color"}},
		{"an integer", "RotateWidget", "Angle", `45`, `45`, nil},
		{"a string map", "TagWidget", "Tags", `{"compat":"scenario"}`, `Map.of("compat", "scenario")`, nil},
		{"a list of strings", "UntagWidget", "TagKeys", `["compat"]`, `List.of("compat")`, nil},
		{
			// The structure's own builder, one setter per member, in member
			// order — as a human would write it.
			"a list of structures", "TagSprocket", "Tags", `[{"Key":"k","Value":"v"}]`,
			`List.of(SprocketTag.builder().key("k").value("v").build())`, []string{"SprocketTag"},
		},
		{
			"an expression into a string", "GetWidget", "WidgetId", `{"$ref":"widget.id"}`,
			`b.string("WidgetId", Values.ref("widget.id"))`, nil,
		},
		{
			// The Binder result is a String, not a Color, so the enum
			// conversion is written around it.
			"an expression into an enum", "CreateWidget", "Color", `{"$name":"c"}`,
			`Color.fromValue(b.string("Color", Values.name("c")))`, []string{"Color"},
		},
		{
			"an expression inside a composite", "TagWidget", "Tags", `{"compat":{"$ref":"t"}}`,
			`Map.of("compat", b.string("Tags", Values.ref("t")))`, nil,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			sp := newJavaSpeller(f.model)
			target, err := sp.memberTarget(tc.op, tc.member)
			if err != nil {
				t.Fatal(err)
			}
			var v any
			if err := decodeStrict([]byte(tc.value), &v); err != nil {
				t.Fatal(err)
			}
			got, err := sp.value(target, v, tc.member)
			if err != nil {
				t.Fatalf("spelling %s.%s: %v", tc.op, tc.member, err)
			}
			if got != tc.want {
				t.Errorf("%s.%s = %s, want %s", tc.op, tc.member, got, tc.want)
			}
			// A model class is recorded only when the spelling actually named
			// it, which is what keeps an emitted file free of unused imports.
			if strings.Join(sp.modelImports(), ",") != strings.Join(tc.wantTypes, ",") {
				t.Errorf("model imports = %v, want %v", sp.modelImports(), tc.wantTypes)
			}
		})
	}
}

// TestJavaPascalAndUnCapitalize pins the two SDK naming rules that disagree, and
// the disagreement itself. Organizations really does declare
// `listAWSServiceAccessForOrganization(ListAwsServiceAccessForOrganizationRequest)`
// — one name pascal-cased, the other merely un-capitalized — and an emitter that
// derived either from the other would not compile against it.
func TestJavaPascalAndUnCapitalize(t *testing.T) {
	for _, tc := range []struct{ in, pascal, unCapitalized string }{
		{"SQS", "Sqs", "sqs"},
		{"DynamoDB", "DynamoDb", "dynamoDB"},
		{"WAFV2", "Wafv2", "wafv2"},
		{"Cognito Identity Provider", "CognitoIdentityProvider", "cognito Identity Provider"},
		{"Organizations", "Organizations", "organizations"},
		{"ListAccounts", "ListAccounts", "listAccounts"},
		{"ListAWSServiceAccessForOrganization", "ListAwsServiceAccessForOrganization", "listAWSServiceAccessForOrganization"},
		{"MD5OfBody", "Md5OfBody", "md5OfBody"},
	} {
		if got := javaPascal(tc.in); got != tc.pascal {
			t.Errorf("javaPascal(%q) = %q, want %q", tc.in, got, tc.pascal)
		}
		if got := javaUnCapitalize(tc.in); got != tc.unCapitalized {
			t.Errorf("javaUnCapitalize(%q) = %q, want %q", tc.in, got, tc.unCapitalized)
		}
	}
	if got := javaNameClientClass("SQS"); got != "SqsClient" {
		t.Errorf("javaNameClientClass(SQS) = %q", got)
	}
	if got := javaNamePackage("Cognito Identity Provider"); got != "software.amazon.awssdk.services.cognitoidentityprovider" {
		t.Errorf("javaNamePackage = %q", got)
	}
}

// TestEmitJavaIndex pins both halves of the index: it lists what was emitted,
// and it still compiles when nothing was.
func TestEmitJavaIndex_listsEveryEmittedServiceAndCompilesWhenEmpty(t *testing.T) {
	source := string(emitJavaIndex([]string{"sqs", "organizations"}))
	if !strings.Contains(source, "new ScenariosOrganizationsGen(clients)") || !strings.Contains(source, "new ScenariosSqsGen(clients)") {
		t.Errorf("index does not name both services:\n%s", source)
	}
	if strings.Index(source, "ScenariosOrganizationsGen") > strings.Index(source, "ScenariosSqsGen") {
		t.Error("the index is not sorted; regeneration would depend on recipe read order")
	}

	empty := string(emitJavaIndex(nil))
	if !strings.Contains(empty, "return List.of();") {
		t.Errorf("the empty index does not compile to an empty list:\n%s", empty)
	}
}

// TestJavaValue_coversTheIRsValueGrammar keeps the naming table total: every
// form the IR admits has a Java expression, and nothing else does.
func TestJavaValue_coversTheIRsValueGrammar(t *testing.T) {
	for _, tc := range []struct {
		name string
		in   string
		want string
	}{
		{"a string", `"hello"`, `"hello"`},
		// Every untyped number is compared as JSON against a response the
		// runtime normalised to a double, so it is written as one.
		{"a number", `30`, `30.0`},
		{"a boolean", `false`, `false`},
		{"null", `null`, `null`},
		{"a list", `["a","b"]`, `Values.list("a", "b")`},
		{"an object", `{"K":"v"}`, `Values.map("K", "v")`},
		{"$name", `{"$name":"q"}`, `Values.name("q")`},
		{"$ref", `{"$ref":"queue.url"}`, `Values.ref("queue.url")`},
		{"$lit", `{"$lit":{"$weird":1}}`, `Values.lit(Values.map("$weird", 1.0))`},
		{"$concat", `{"$concat":["a",{"$ref":"q.u"}]}`, `Values.concat("a", Values.ref("q.u"))`},
		{"$index", `{"$index":[{"$ref":"q.urls"},1]}`, `Values.index(Values.ref("q.urls"), 1)`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var v any
			if err := decodeStrict([]byte(tc.in), &v); err != nil {
				t.Fatal(err)
			}
			got, err := javaValue(v)
			if err != nil {
				t.Fatalf("javaValue(%s): %v", tc.in, err)
			}
			if got != tc.want {
				t.Errorf("javaValue(%s) = %s, want %s", tc.in, got, tc.want)
			}
		})
	}

	// A value outside the grammar has no expression, and says so rather than
	// rendering something that would not compile.
	if _, err := javaValue(struct{}{}); err == nil {
		t.Error("a value outside the IR's grammar was rendered")
	}
}

// TestJavaMethodNamesAreUnique refuses two names that fold to one Java
// identifier before the suite fails to build with no indication of which pair
// caused it.
func TestJavaMethodNamesAreUnique(t *testing.T) {
	groups := []group{
		{Name: "svc-gen-a-b", Tests: []test{{Name: "C"}}},
		{Name: "svc-gen-a", Tests: []test{{Name: "BC"}}},
	}
	err := javaMethodNamesAreUnique("svc", groups)
	if err == nil {
		t.Fatal("two colliding method names were accepted")
	}
	for _, want := range []string{"svc-gen-a-b/C", "svc-gen-a/BC", "testSvcGenABC"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the collision message lacks %q: %v", want, err)
		}
	}
}

// TestExplainJavaRendersTheEmittedCall is the definition-of-done item that there
// is one naming table: `-explain -lang java` must print the statements the
// emitter writes, not a second description of them. Both go through
// javaRequestLines, over the same modeled shapes.
func TestExplainJavaRendersTheEmittedCall(t *testing.T) {
	f, gen := generateFixture(t)
	g, tc, ok := gen.scenario.findTest("widgets-gen-widget", "CreateWidget")
	if !ok {
		t.Fatal("fixture has no CreateWidget")
	}
	e := &explainer{st: javaStyle(newJavaSpeller(f.model), nil)}
	explained := e.test(gen.scenario, g, tc, func() {})

	emission, err := emitJava(gen)
	if err != nil {
		t.Fatalf("emitJava: %v", err)
	}
	emitted := string(emission.Contents)

	lines, err := javaRequestLines(newJavaSpeller(f.model), tc.Call.Op, tc.Call.Params)
	if err != nil {
		t.Fatal(err)
	}
	if len(lines) < 3 {
		t.Fatalf("CreateWidget renders %d line(s); the fixture no longer exercises member binding", len(lines))
	}
	for _, line := range lines {
		if !strings.Contains(explained, line) {
			t.Errorf("-explain -lang java does not render %q:\n%s", line, explained)
		}
		if !strings.Contains(emitted, line) {
			t.Errorf("the emitted source does not contain %q", line)
		}
	}
	if !strings.Contains(explained, "client."+javaMethod(tc.Call.Op)+"(request)") {
		t.Errorf("-explain -lang java does not call the operation:\n%s", explained)
	}
}
