// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The generated sns groups.</summary>
/// <remarks>
/// Generated from compat/model/scenarios/sns.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosSns : IServiceGroup
{
    private static readonly ScenarioGroup GroupSnsGenTopic = new("sns-gen-topic", "compat/model/scenarios/sns.json");
    private static readonly ScenarioGroup GroupSnsGenSubscription = new("sns-gen-subscription", "compat/model/scenarios/sns.json");
    private static readonly ScenarioGroup GroupSnsGenProbe = new("sns-gen-probe", "compat/model/scenarios/sns.json");

    private readonly Lazy<AmazonSimpleNotificationServiceClient> _client;

    internal ScenariosSns(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonSimpleNotificationServiceClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonSimpleNotificationServiceClient(credentials, (AmazonSimpleNotificationServiceConfig)configuration),
            new AmazonSimpleNotificationServiceConfig()));
    }

    public string SourceName => "ScenariosSns";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["sns-gen-topic:CreateTopic"] = TestSnsGenTopicCreateTopic,
        ["sns-gen-topic:GetTopicAttributes"] = TestSnsGenTopicGetTopicAttributes,
        ["sns-gen-topic:SetTopicAttributes"] = TestSnsGenTopicSetTopicAttributes,
        ["sns-gen-topic:TagResource"] = TestSnsGenTopicTagResource,
        ["sns-gen-topic:ListTagsForResource"] = TestSnsGenTopicListTagsForResource,
        ["sns-gen-topic:UntagResource"] = TestSnsGenTopicUntagResource,
        ["sns-gen-topic:Publish"] = TestSnsGenTopicPublish,
        ["sns-gen-topic:PublishBatch"] = TestSnsGenTopicPublishBatch,
        ["sns-gen-topic:ConfirmSubscription"] = TestSnsGenTopicConfirmSubscription,
        ["sns-gen-topic:ListTopics"] = TestSnsGenTopicListTopics,
        ["sns-gen-topic:DeleteTopic"] = TestSnsGenTopicDeleteTopic,
        ["sns-gen-subscription:Subscribe"] = TestSnsGenSubscriptionSubscribe,
        ["sns-gen-subscription:GetSubscriptionAttributes"] = TestSnsGenSubscriptionGetSubscriptionAttributes,
        ["sns-gen-subscription:SetSubscriptionAttributes"] = TestSnsGenSubscriptionSetSubscriptionAttributes,
        ["sns-gen-subscription:GetTopicAttributesAfterCreate"] = TestSnsGenSubscriptionGetTopicAttributesAfterCreate,
        ["sns-gen-subscription:ListSubscriptionsByTopic"] = TestSnsGenSubscriptionListSubscriptionsByTopic,
        ["sns-gen-subscription:ListSubscriptions"] = TestSnsGenSubscriptionListSubscriptions,
        ["sns-gen-subscription:Unsubscribe"] = TestSnsGenSubscriptionUnsubscribe,
        ["sns-gen-probe:CheckIfPhoneNumberIsOptedOut"] = TestSnsGenProbeCheckIfPhoneNumberIsOptedOut,
        ["sns-gen-probe:GetDataProtectionPolicy"] = TestSnsGenProbeGetDataProtectionPolicy,
        ["sns-gen-probe:GetEndpointAttributes"] = TestSnsGenProbeGetEndpointAttributes,
        ["sns-gen-probe:GetPlatformApplicationAttributes"] = TestSnsGenProbeGetPlatformApplicationAttributes,
        ["sns-gen-probe:GetSMSAttributes"] = TestSnsGenProbeGetSMSAttributes,
        ["sns-gen-probe:GetSMSSandboxAccountStatus"] = TestSnsGenProbeGetSMSSandboxAccountStatus,
        ["sns-gen-probe:ListEndpointsByPlatformApplication"] = TestSnsGenProbeListEndpointsByPlatformApplication,
        ["sns-gen-probe:ListOriginationNumbers"] = TestSnsGenProbeListOriginationNumbers,
        ["sns-gen-probe:ListPhoneNumbersOptedOut"] = TestSnsGenProbeListPhoneNumbersOptedOut,
        ["sns-gen-probe:ListPlatformApplications"] = TestSnsGenProbeListPlatformApplications,
        ["sns-gen-probe:ListSMSSandboxPhoneNumbers"] = TestSnsGenProbeListSMSSandboxPhoneNumbers,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["sns-gen-topic"] = SetupSnsGenTopic,
        ["sns-gen-subscription"] = SetupSnsGenSubscription,
        ["sns-gen-probe"] = SetupSnsGenProbe,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["sns-gen-topic"] = TeardownSnsGenTopic,
        ["sns-gen-subscription"] = TeardownSnsGenSubscription,
        ["sns-gen-probe"] = TeardownSnsGenProbe,
    };

    private AmazonSimpleNotificationServiceClient Cl() => _client.Value;

    private Task SetupSnsGenTopic(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupSnsGenTopic.RunSetupAsync(t);

    private Task TeardownSnsGenTopic(TestContext t) =>
        GroupSnsGenTopic.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteTopic",
                Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
                Build = b =>
                {
                    var request = new DeleteTopicRequest();
                    request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteTopicAsync((DeleteTopicRequest)request),
            }
        );

    private Task TestSnsGenTopicCreateTopic(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "CreateTopic", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateTopic",
            Params = "{\"Attributes\":{\"DisplayName\":\"compat scenario topic\"},\"Name\":{\"$name\":\"t\"}}",
            Build = b =>
            {
                var request = new CreateTopicRequest();
                request.Attributes = new() { ["DisplayName"] = "compat scenario topic" };
                request.Name = b.Bind<string>("Name", Val.Name("t"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateTopicAsync((CreateTopicRequest)request),
            Export = new()
            {
                ["topic.id"] = "$.TopicArn",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.TopicArn")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetTopicAttributes",
                    Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
                    Build = b =>
                    {
                        var request = new GetTopicAttributesRequest();
                        request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetTopicAttributesAsync((GetTopicAttributesRequest)request),
                },
                Check.EqualTo("$.Attributes.TopicArn", Val.Ref("topic.id"))
            ),
            Clause.ListContains(
                new ScenarioCall
                {
                    Op = "ListTopics",
                    Params = "{}",
                    Build = b =>
                    {
                        var request = new ListTopicsRequest();
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListTopicsAsync((ListTopicsRequest)request),
                },
                "$.Topics",
                new WhereEntry("$.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenTopicGetTopicAttributes(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "GetTopicAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetTopicAttributes",
            Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new GetTopicAttributesRequest();
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetTopicAttributesAsync((GetTopicAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Attributes.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenTopicSetTopicAttributes(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "SetTopicAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "SetTopicAttributes",
            Params = "{\"AttributeName\":\"DisplayName\",\"AttributeValue\":\"compat scenario topic, updated\",\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new SetTopicAttributesRequest();
                request.AttributeName = "DisplayName";
                request.AttributeValue = "compat scenario topic, updated";
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().SetTopicAttributesAsync((SetTopicAttributesRequest)request),
        },
        Assert =
        [
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetTopicAttributes",
                    Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
                    Build = b =>
                    {
                        var request = new GetTopicAttributesRequest();
                        request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetTopicAttributesAsync((GetTopicAttributesRequest)request),
                },
                Check.EqualTo("$.Attributes.DisplayName", "compat scenario topic, updated")
            )
        ],
    });

    private Task TestSnsGenTopicTagResource(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "TagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "TagResource",
            Params = "{\"ResourceArn\":{\"$ref\":\"topic.id\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
            Build = b =>
            {
                var request = new TagResourceRequest();
                request.ResourceArn = b.Bind<string>("ResourceArn", Val.Ref("topic.id"));
                request.Tags = [new() { Key = "compat", Value = "scenario" }];
                return request;
            },
            SendAsync = async request =>
                await Cl().TagResourceAsync((TagResourceRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                new ScenarioCall
                {
                    Op = "ListTagsForResource",
                    Params = "{\"ResourceArn\":{\"$ref\":\"topic.id\"}}",
                    Build = b =>
                    {
                        var request = new ListTagsForResourceRequest();
                        request.ResourceArn = b.Bind<string>("ResourceArn", Val.Ref("topic.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                },
                "$.Tags",
                new WhereEntry("$.Key", "compat"),
                new WhereEntry("$.Value", "scenario")
            )
        ],
    });

    private Task TestSnsGenTopicListTagsForResource(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "ListTagsForResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListTagsForResource",
            Params = "{\"ResourceArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new ListTagsForResourceRequest();
                request.ResourceArn = b.Bind<string>("ResourceArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Tags",
                new WhereEntry("$.Key", "compat"),
                new WhereEntry("$.Value", "scenario")
            )
        ],
    });

    private Task TestSnsGenTopicUntagResource(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "UntagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UntagResource",
            Params = "{\"ResourceArn\":{\"$ref\":\"topic.id\"},\"TagKeys\":[\"compat\"]}",
            Build = b =>
            {
                var request = new UntagResourceRequest();
                request.ResourceArn = b.Bind<string>("ResourceArn", Val.Ref("topic.id"));
                request.TagKeys = ["compat"];
                return request;
            },
            SendAsync = async request =>
                await Cl().UntagResourceAsync((UntagResourceRequest)request),
        },
        Assert =
        [
            Clause.AbsentFromList(
                new ScenarioCall
                {
                    Op = "ListTagsForResource",
                    Params = "{\"ResourceArn\":{\"$ref\":\"topic.id\"}}",
                    Build = b =>
                    {
                        var request = new ListTagsForResourceRequest();
                        request.ResourceArn = b.Bind<string>("ResourceArn", Val.Ref("topic.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                },
                "$.Tags",
                new WhereEntry("$.Key", "compat")
            )
        ],
    });

    private Task TestSnsGenTopicPublish(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "Publish", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "Publish",
            Params = "{\"Message\":\"compat scenario message\",\"Subject\":\"compat scenario\",\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new PublishRequest();
                request.Message = "compat scenario message";
                request.Subject = "compat scenario";
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().PublishAsync((PublishRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.Matches("$.MessageId", "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
            )
        ],
    });

    private Task TestSnsGenTopicPublishBatch(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "PublishBatch", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "PublishBatch",
            Params = "{\"PublishBatchRequestEntries\":[{\"Id\":\"1\",\"Message\":\"compat scenario batch message 1\",\"Subject\":\"compat scenario 1\"},{\"Id\":\"2\",\"Message\":\"compat scenario batch message 2\",\"Subject\":\"compat scenario 2\"}],\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new PublishBatchRequest();
                request.PublishBatchRequestEntries = [
                    new()
                    {
                        Id = "1",
                        Message = "compat scenario batch message 1",
                        Subject = "compat scenario 1",
                    },
                    new()
                    {
                        Id = "2",
                        Message = "compat scenario batch message 2",
                        Subject = "compat scenario 2",
                    },
                ];
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().PublishBatchAsync((PublishBatchRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Successful[0].Id", "1"),
                Check.Matches("$.Successful[0].MessageId", "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"),
                Check.EqualTo("$.Successful[1].Id", "2")
            ),
            Clause.AbsentFromList(
                null,
                "$.Failed",
                new WhereEntry("$.Id", "1")
            )
        ],
    });

    private Task TestSnsGenTopicConfirmSubscription(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "ConfirmSubscription", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ConfirmSubscription",
            Params = "{\"Token\":\"compat-scenario-token-that-sns-never-issued\",\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new ConfirmSubscriptionRequest();
                request.Token = "compat-scenario-token-that-sns-never-issued";
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ConfirmSubscriptionAsync((ConfirmSubscriptionRequest)request),
        },
        Assert =
        [
            Clause.ErrorCode(new ErrorSpec("InvalidParameterException", "InvalidParameter"))
        ],
    });

    private Task TestSnsGenTopicListTopics(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "ListTopics", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListTopics",
            Params = "{}",
            Build = b =>
            {
                var request = new ListTopicsRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListTopicsAsync((ListTopicsRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Topics",
                new WhereEntry("$.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenTopicDeleteTopic(TestContext t) => GroupSnsGenTopic.RunTestAsync(t, "DeleteTopic", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteTopic",
            Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new DeleteTopicRequest();
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteTopicAsync((DeleteTopicRequest)request),
        },
        Assert =
        [
            Clause.AbsentByError(
                new ScenarioCall
                {
                    Op = "GetTopicAttributes",
                    Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
                    Build = b =>
                    {
                        var request = new GetTopicAttributesRequest();
                        request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetTopicAttributesAsync((GetTopicAttributesRequest)request),
                },
                new ErrorSpec("NotFoundException", "NotFound"))
        ],
    });

    private Task SetupSnsGenSubscription(TestContext t) =>
        GroupSnsGenSubscription.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateTopic",
                Params = "{\"Attributes\":{\"DisplayName\":\"compat scenario topic\"},\"Name\":{\"$name\":\"t\"}}",
                Build = b =>
                {
                    var request = new CreateTopicRequest();
                    request.Attributes = new() { ["DisplayName"] = "compat scenario topic" };
                    request.Name = b.Bind<string>("Name", Val.Name("t"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateTopicAsync((CreateTopicRequest)request),
                Export = new()
                {
                    ["topic.id"] = "$.TopicArn",
                },
            }
        );

    private Task TeardownSnsGenSubscription(TestContext t) =>
        GroupSnsGenSubscription.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "Unsubscribe",
                Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
                Build = b =>
                {
                    var request = new UnsubscribeRequest();
                    request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().UnsubscribeAsync((UnsubscribeRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteTopic",
                Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
                Build = b =>
                {
                    var request = new DeleteTopicRequest();
                    request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteTopicAsync((DeleteTopicRequest)request),
            }
        );

    private Task TestSnsGenSubscriptionSubscribe(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "Subscribe", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "Subscribe",
            Params = "{\"Attributes\":{\"FilterPolicy\":\"{\\\"compat\\\":[\\\"scenario\\\"]}\"},\"Endpoint\":{\"$concat\":[{\"$name\":\"s\"},\"@example.com\"]},\"Protocol\":\"email\",\"ReturnSubscriptionArn\":true,\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new SubscribeRequest();
                request.Attributes = new() { ["FilterPolicy"] = "{\"compat\":[\"scenario\"]}" };
                request.Endpoint = b.Bind<string>("Endpoint", Val.Concat(Val.Name("s"), "@example.com"));
                request.Protocol = "email";
                request.ReturnSubscriptionArn = true;
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().SubscribeAsync((SubscribeRequest)request),
            Export = new()
            {
                ["subscription.id"] = "$.SubscriptionArn",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.SubscriptionArn")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetSubscriptionAttributes",
                    Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
                    Build = b =>
                    {
                        var request = new GetSubscriptionAttributesRequest();
                        request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetSubscriptionAttributesAsync((GetSubscriptionAttributesRequest)request),
                },
                Check.EqualTo("$.Attributes.SubscriptionArn", Val.Ref("subscription.id"))
            )
        ],
    });

    private Task TestSnsGenSubscriptionGetSubscriptionAttributes(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "GetSubscriptionAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetSubscriptionAttributes",
            Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
            Build = b =>
            {
                var request = new GetSubscriptionAttributesRequest();
                request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetSubscriptionAttributesAsync((GetSubscriptionAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Attributes.SubscriptionArn", Val.Ref("subscription.id"))
            )
        ],
    });

    private Task TestSnsGenSubscriptionSetSubscriptionAttributes(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "SetSubscriptionAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "SetSubscriptionAttributes",
            Params = "{\"AttributeName\":\"FilterPolicy\",\"AttributeValue\":\"{\\\"compat\\\":[\\\"scenario\\\",\\\"updated\\\"]}\",\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
            Build = b =>
            {
                var request = new SetSubscriptionAttributesRequest();
                request.AttributeName = "FilterPolicy";
                request.AttributeValue = "{\"compat\":[\"scenario\",\"updated\"]}";
                request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().SetSubscriptionAttributesAsync((SetSubscriptionAttributesRequest)request),
        },
        Assert =
        [
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetSubscriptionAttributes",
                    Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
                    Build = b =>
                    {
                        var request = new GetSubscriptionAttributesRequest();
                        request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetSubscriptionAttributesAsync((GetSubscriptionAttributesRequest)request),
                },
                Check.EqualTo("$.Attributes.FilterPolicy", "{\"compat\":[\"scenario\",\"updated\"]}")
            )
        ],
    });

    private Task TestSnsGenSubscriptionGetTopicAttributesAfterCreate(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "GetTopicAttributesAfterCreate", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetTopicAttributes",
            Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new GetTopicAttributesRequest();
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetTopicAttributesAsync((GetTopicAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Attributes.DisplayName", "compat scenario topic"),
                Check.EqualTo("$.Attributes.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenSubscriptionListSubscriptionsByTopic(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "ListSubscriptionsByTopic", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListSubscriptionsByTopic",
            Params = "{\"TopicArn\":{\"$ref\":\"topic.id\"}}",
            Build = b =>
            {
                var request = new ListSubscriptionsByTopicRequest();
                request.TopicArn = b.Bind<string>("TopicArn", Val.Ref("topic.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListSubscriptionsByTopicAsync((ListSubscriptionsByTopicRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Subscriptions",
                new WhereEntry("$.Protocol", "email"),
                new WhereEntry("$.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenSubscriptionListSubscriptions(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "ListSubscriptions", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListSubscriptions",
            Params = "{}",
            Build = b =>
            {
                var request = new ListSubscriptionsRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListSubscriptionsAsync((ListSubscriptionsRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Subscriptions",
                new WhereEntry("$.Protocol", "email"),
                new WhereEntry("$.TopicArn", Val.Ref("topic.id"))
            )
        ],
    });

    private Task TestSnsGenSubscriptionUnsubscribe(TestContext t) => GroupSnsGenSubscription.RunTestAsync(t, "Unsubscribe", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "Unsubscribe",
            Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
            Build = b =>
            {
                var request = new UnsubscribeRequest();
                request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().UnsubscribeAsync((UnsubscribeRequest)request),
        },
        Assert =
        [
            Clause.AbsentByError(
                new ScenarioCall
                {
                    Op = "GetSubscriptionAttributes",
                    Params = "{\"SubscriptionArn\":{\"$ref\":\"subscription.id\"}}",
                    Build = b =>
                    {
                        var request = new GetSubscriptionAttributesRequest();
                        request.SubscriptionArn = b.Bind<string>("SubscriptionArn", Val.Ref("subscription.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetSubscriptionAttributesAsync((GetSubscriptionAttributesRequest)request),
                },
                new ErrorSpec("NotFoundException", "NotFound"))
        ],
    });

    private Task SetupSnsGenProbe(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupSnsGenProbe.RunSetupAsync(t);

    private Task TeardownSnsGenProbe(TestContext t) =>
        // No teardown steps: an empty phase is a no-op, not a missing one.
        GroupSnsGenProbe.RunTeardownAsync(t);

    private Task TestSnsGenProbeCheckIfPhoneNumberIsOptedOut(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "CheckIfPhoneNumberIsOptedOut", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CheckIfPhoneNumberIsOptedOut",
            Params = "{\"phoneNumber\":\"+12025550100\"}",
            Build = b =>
            {
                var request = new CheckIfPhoneNumberIsOptedOutRequest();
                request.PhoneNumber = "+12025550100";
                return request;
            },
            SendAsync = async request =>
                await Cl().CheckIfPhoneNumberIsOptedOutAsync((CheckIfPhoneNumberIsOptedOutRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.isOptedOut")
            )
        ],
    });

    private Task TestSnsGenProbeGetDataProtectionPolicy(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "GetDataProtectionPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetDataProtectionPolicy",
            Params = "{\"ResourceArn\":\"arn:aws:sns:us-east-1:123456789012:compat-scenario-nonexistent\"}",
            Build = b =>
            {
                var request = new GetDataProtectionPolicyRequest();
                request.ResourceArn = "arn:aws:sns:us-east-1:123456789012:compat-scenario-nonexistent";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetDataProtectionPolicyAsync((GetDataProtectionPolicyRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.DataProtectionPolicy")
            )
        ],
    });

    private Task TestSnsGenProbeGetEndpointAttributes(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "GetEndpointAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetEndpointAttributes",
            Params = "{\"EndpointArn\":\"arn:aws:sns:us-east-1:123456789012:endpoint/GCM/compat-scenario-nonexistent/00000000-0000-0000-0000-000000000000\"}",
            Build = b =>
            {
                var request = new GetEndpointAttributesRequest();
                request.EndpointArn = "arn:aws:sns:us-east-1:123456789012:endpoint/GCM/compat-scenario-nonexistent/00000000-0000-0000-0000-000000000000";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetEndpointAttributesAsync((GetEndpointAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Attributes")
            )
        ],
    });

    private Task TestSnsGenProbeGetPlatformApplicationAttributes(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "GetPlatformApplicationAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetPlatformApplicationAttributes",
            Params = "{\"PlatformApplicationArn\":\"arn:aws:sns:us-east-1:123456789012:app/GCM/compat-scenario-nonexistent\"}",
            Build = b =>
            {
                var request = new GetPlatformApplicationAttributesRequest();
                request.PlatformApplicationArn = "arn:aws:sns:us-east-1:123456789012:app/GCM/compat-scenario-nonexistent";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetPlatformApplicationAttributesAsync((GetPlatformApplicationAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Attributes")
            )
        ],
    });

    private Task TestSnsGenProbeGetSMSAttributes(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "GetSMSAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetSMSAttributes",
            Params = "{}",
            Build = b =>
            {
                var request = new GetSMSAttributesRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().GetSMSAttributesAsync((GetSMSAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.attributes")
            )
        ],
    });

    private Task TestSnsGenProbeGetSMSSandboxAccountStatus(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "GetSMSSandboxAccountStatus", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetSMSSandboxAccountStatus",
            Params = "{}",
            Build = b =>
            {
                var request = new GetSMSSandboxAccountStatusRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().GetSMSSandboxAccountStatusAsync((GetSMSSandboxAccountStatusRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.IsInSandbox")
            )
        ],
    });

    private Task TestSnsGenProbeListEndpointsByPlatformApplication(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "ListEndpointsByPlatformApplication", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListEndpointsByPlatformApplication",
            Params = "{\"PlatformApplicationArn\":\"arn:aws:sns:us-east-1:123456789012:app/GCM/compat-scenario-nonexistent\"}",
            Build = b =>
            {
                var request = new ListEndpointsByPlatformApplicationRequest();
                request.PlatformApplicationArn = "arn:aws:sns:us-east-1:123456789012:app/GCM/compat-scenario-nonexistent";
                return request;
            },
            SendAsync = async request =>
                await Cl().ListEndpointsByPlatformApplicationAsync((ListEndpointsByPlatformApplicationRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.Endpoints")
            )
        ],
    });

    private Task TestSnsGenProbeListOriginationNumbers(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "ListOriginationNumbers", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListOriginationNumbers",
            Params = "{}",
            Build = b =>
            {
                var request = new ListOriginationNumbersRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListOriginationNumbersAsync((ListOriginationNumbersRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.PhoneNumbers")
            )
        ],
    });

    private Task TestSnsGenProbeListPhoneNumbersOptedOut(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "ListPhoneNumbersOptedOut", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListPhoneNumbersOptedOut",
            Params = "{}",
            Build = b =>
            {
                var request = new ListPhoneNumbersOptedOutRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListPhoneNumbersOptedOutAsync((ListPhoneNumbersOptedOutRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.phoneNumbers")
            )
        ],
    });

    private Task TestSnsGenProbeListPlatformApplications(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "ListPlatformApplications", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListPlatformApplications",
            Params = "{}",
            Build = b =>
            {
                var request = new ListPlatformApplicationsRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListPlatformApplicationsAsync((ListPlatformApplicationsRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.PlatformApplications")
            )
        ],
    });

    private Task TestSnsGenProbeListSMSSandboxPhoneNumbers(TestContext t) => GroupSnsGenProbe.RunTestAsync(t, "ListSMSSandboxPhoneNumbers", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListSMSSandboxPhoneNumbers",
            Params = "{}",
            Build = b =>
            {
                var request = new ListSMSSandboxPhoneNumbersRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListSMSSandboxPhoneNumbersAsync((ListSMSSandboxPhoneNumbersRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.PhoneNumbers")
            )
        ],
    });
}
