// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.ServiceDiscovery;
using Amazon.ServiceDiscovery.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The generated servicediscovery groups.</summary>
/// <remarks>
/// Generated from compat/model/scenarios/servicediscovery.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosServicediscovery : IServiceGroup
{
    private static readonly ScenarioGroup GroupServicediscoveryGenNamespace = new("servicediscovery-gen-namespace", "compat/model/scenarios/servicediscovery.json");
    private static readonly ScenarioGroup GroupServicediscoveryGenService = new("servicediscovery-gen-service", "compat/model/scenarios/servicediscovery.json");
    private static readonly ScenarioGroup GroupServicediscoveryGenInstance = new("servicediscovery-gen-instance", "compat/model/scenarios/servicediscovery.json");
    private static readonly ScenarioGroup GroupServicediscoveryGenProbe = new("servicediscovery-gen-probe", "compat/model/scenarios/servicediscovery.json");

    private readonly Lazy<AmazonServiceDiscoveryClient> _client;

    internal ScenariosServicediscovery(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonServiceDiscoveryClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonServiceDiscoveryClient(credentials, (AmazonServiceDiscoveryConfig)configuration),
            new AmazonServiceDiscoveryConfig()));
    }

    public string SourceName => "ScenariosServicediscovery";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["servicediscovery-gen-namespace:CreateHttpNamespace"] = TestServicediscoveryGenNamespaceCreateHttpNamespace,
        ["servicediscovery-gen-namespace:GetNamespace"] = TestServicediscoveryGenNamespaceGetNamespace,
        ["servicediscovery-gen-namespace:UpdateHttpNamespace"] = TestServicediscoveryGenNamespaceUpdateHttpNamespace,
        ["servicediscovery-gen-namespace:TagResource"] = TestServicediscoveryGenNamespaceTagResource,
        ["servicediscovery-gen-namespace:ListTagsForResource"] = TestServicediscoveryGenNamespaceListTagsForResource,
        ["servicediscovery-gen-namespace:UntagResource"] = TestServicediscoveryGenNamespaceUntagResource,
        ["servicediscovery-gen-namespace:ListNamespaces"] = TestServicediscoveryGenNamespaceListNamespaces,
        ["servicediscovery-gen-namespace:DeleteNamespace"] = TestServicediscoveryGenNamespaceDeleteNamespace,
        ["servicediscovery-gen-service:CreateService"] = TestServicediscoveryGenServiceCreateService,
        ["servicediscovery-gen-service:GetService"] = TestServicediscoveryGenServiceGetService,
        ["servicediscovery-gen-service:UpdateService"] = TestServicediscoveryGenServiceUpdateService,
        ["servicediscovery-gen-service:TagResource"] = TestServicediscoveryGenServiceTagResource,
        ["servicediscovery-gen-service:ListTagsForResource"] = TestServicediscoveryGenServiceListTagsForResource,
        ["servicediscovery-gen-service:UntagResource"] = TestServicediscoveryGenServiceUntagResource,
        ["servicediscovery-gen-service:UpdateServiceAttributes"] = TestServicediscoveryGenServiceUpdateServiceAttributes,
        ["servicediscovery-gen-service:GetServiceAttributes"] = TestServicediscoveryGenServiceGetServiceAttributes,
        ["servicediscovery-gen-service:DeleteServiceAttributes"] = TestServicediscoveryGenServiceDeleteServiceAttributes,
        ["servicediscovery-gen-service:ListInstances"] = TestServicediscoveryGenServiceListInstances,
        ["servicediscovery-gen-service:DiscoverInstances"] = TestServicediscoveryGenServiceDiscoverInstances,
        ["servicediscovery-gen-service:ListOperations"] = TestServicediscoveryGenServiceListOperations,
        ["servicediscovery-gen-service:ListServices"] = TestServicediscoveryGenServiceListServices,
        ["servicediscovery-gen-service:DeleteService"] = TestServicediscoveryGenServiceDeleteService,
        ["servicediscovery-gen-instance:RegisterInstance"] = TestServicediscoveryGenInstanceRegisterInstance,
        ["servicediscovery-gen-instance:GetInstance"] = TestServicediscoveryGenInstanceGetInstance,
        ["servicediscovery-gen-instance:ListInstances"] = TestServicediscoveryGenInstanceListInstances,
        ["servicediscovery-gen-instance:DeregisterInstance"] = TestServicediscoveryGenInstanceDeregisterInstance,
        ["servicediscovery-gen-probe:GetInstancesHealthStatus"] = TestServicediscoveryGenProbeGetInstancesHealthStatus,
        ["servicediscovery-gen-probe:GetOperation"] = TestServicediscoveryGenProbeGetOperation,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["servicediscovery-gen-namespace"] = SetupServicediscoveryGenNamespace,
        ["servicediscovery-gen-service"] = SetupServicediscoveryGenService,
        ["servicediscovery-gen-instance"] = SetupServicediscoveryGenInstance,
        ["servicediscovery-gen-probe"] = SetupServicediscoveryGenProbe,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["servicediscovery-gen-namespace"] = TeardownServicediscoveryGenNamespace,
        ["servicediscovery-gen-service"] = TeardownServicediscoveryGenService,
        ["servicediscovery-gen-instance"] = TeardownServicediscoveryGenInstance,
        ["servicediscovery-gen-probe"] = TeardownServicediscoveryGenProbe,
    };

    private AmazonServiceDiscoveryClient Cl() => _client.Value;

    private Task SetupServicediscoveryGenNamespace(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupServicediscoveryGenNamespace.RunSetupAsync(t);

    private Task TeardownServicediscoveryGenNamespace(TestContext t) =>
        GroupServicediscoveryGenNamespace.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteNamespace",
                Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                Build = b =>
                {
                    var request = new DeleteNamespaceRequest();
                    request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteNamespaceAsync((DeleteNamespaceRequest)request),
            }
        );

    private Task TestServicediscoveryGenNamespaceCreateHttpNamespace(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "CreateHttpNamespace", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateHttpNamespace",
            Params = "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
            Build = b =>
            {
                var request = new CreateHttpNamespaceRequest();
                request.Description = "compat scenario namespace";
                request.Name = b.Bind<string>("Name", Val.Name("ns"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateHttpNamespaceAsync((CreateHttpNamespaceRequest)request),
            Export = new()
            {
                ["namespace.operationId"] = "$.OperationId",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.OperationId")
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetOperation",
                        Params = "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                        Build = b =>
                        {
                            var request = new GetOperationRequest();
                            request.OperationId = b.Bind<string>("OperationId", Val.Ref("namespace.operationId"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetOperationAsync((GetOperationRequest)request),
                        Export = new()
                        {
                            ["namespace.id"] = "$.Operation.Targets.NAMESPACE",
                        },
                    },
                    Check.NonEmpty("$.Operation.Targets.NAMESPACE")
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetNamespace",
                        Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        Build = b =>
                        {
                            var request = new GetNamespaceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetNamespaceAsync((GetNamespaceRequest)request),
                    },
                    Check.EqualTo("$.Namespace.Id", Val.Ref("namespace.id"))
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListNamespaces",
                        Params = "{}",
                        Build = b =>
                        {
                            var request = new ListNamespacesRequest();
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListNamespacesAsync((ListNamespacesRequest)request),
                    },
                    "$.Namespaces",
                    new WhereEntry("$.Id", Val.Ref("namespace.id"))
                )
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceGetNamespace(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "GetNamespace", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetNamespace",
            Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
            Build = b =>
            {
                var request = new GetNamespaceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetNamespaceAsync((GetNamespaceRequest)request),
            Export = new()
            {
                ["namespace.arn"] = "$.Namespace.Arn",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Namespace.Id", Val.Ref("namespace.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceUpdateHttpNamespace(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "UpdateHttpNamespace", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateHttpNamespace",
            Params = "{\"Id\":{\"$ref\":\"namespace.id\"},\"Namespace\":{\"Description\":\"compat scenario namespace, updated\"}}",
            Build = b =>
            {
                var request = new UpdateHttpNamespaceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                request.Namespace = new() { Description = "compat scenario namespace, updated" };
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateHttpNamespaceAsync((UpdateHttpNamespaceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetNamespace",
                        Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        Build = b =>
                        {
                            var request = new GetNamespaceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetNamespaceAsync((GetNamespaceRequest)request),
                    },
                    Check.EqualTo("$.Namespace.Description", "compat scenario namespace, updated")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceTagResource(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "TagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "TagResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
            Build = b =>
            {
                var request = new TagResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("namespace.arn"));
                request.Tags = [new() { Key = "compat", Value = "scenario" }];
                return request;
            },
            SendAsync = async request =>
                await Cl().TagResourceAsync((TagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListTagsForResource",
                        Params = "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
                        Build = b =>
                        {
                            var request = new ListTagsForResourceRequest();
                            request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("namespace.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat"),
                    new WhereEntry("$.Value", "scenario")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceListTagsForResource(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "ListTagsForResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListTagsForResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
            Build = b =>
            {
                var request = new ListTagsForResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("namespace.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Tags",
                new WhereEntry("$.Key", "compat"),
                new WhereEntry("$.Value", "scenario")
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceUntagResource(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "UntagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UntagResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"},\"TagKeys\":[\"compat\"]}",
            Build = b =>
            {
                var request = new UntagResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("namespace.arn"));
                request.TagKeys = ["compat"];
                return request;
            },
            SendAsync = async request =>
                await Cl().UntagResourceAsync((UntagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListTagsForResource",
                        Params = "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
                        Build = b =>
                        {
                            var request = new ListTagsForResourceRequest();
                            request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("namespace.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceListNamespaces(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "ListNamespaces", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListNamespaces",
            Params = "{}",
            Build = b =>
            {
                var request = new ListNamespacesRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListNamespacesAsync((ListNamespacesRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Namespaces",
                new WhereEntry("$.Id", Val.Ref("namespace.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenNamespaceDeleteNamespace(TestContext t) => GroupServicediscoveryGenNamespace.RunTestAsync(t, "DeleteNamespace", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteNamespace",
            Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
            Build = b =>
            {
                var request = new DeleteNamespaceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteNamespaceAsync((DeleteNamespaceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetNamespace",
                        Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        Build = b =>
                        {
                            var request = new GetNamespaceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetNamespaceAsync((GetNamespaceRequest)request),
                    },
                    new ErrorSpec("NamespaceNotFound", "NamespaceNotFound"))
            )
        ],
    });

    private Task SetupServicediscoveryGenService(TestContext t) =>
        GroupServicediscoveryGenService.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateHttpNamespace",
                Params = "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
                Build = b =>
                {
                    var request = new CreateHttpNamespaceRequest();
                    request.Description = "compat scenario namespace";
                    request.Name = b.Bind<string>("Name", Val.Name("ns"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateHttpNamespaceAsync((CreateHttpNamespaceRequest)request),
                Export = new()
                {
                    ["namespace.operationId"] = "$.OperationId",
                },
            },
            new ScenarioCall
            {
                Op = "GetOperation",
                Params = "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                Build = b =>
                {
                    var request = new GetOperationRequest();
                    request.OperationId = b.Bind<string>("OperationId", Val.Ref("namespace.operationId"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().GetOperationAsync((GetOperationRequest)request),
                Export = new()
                {
                    ["namespace.id"] = "$.Operation.Targets.NAMESPACE",
                },
            }
        );

    private Task TeardownServicediscoveryGenService(TestContext t) =>
        GroupServicediscoveryGenService.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteService",
                Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
                Build = b =>
                {
                    var request = new DeleteServiceRequest();
                    request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteServiceAsync((DeleteServiceRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteNamespace",
                Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                Build = b =>
                {
                    var request = new DeleteNamespaceRequest();
                    request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteNamespaceAsync((DeleteNamespaceRequest)request),
            }
        );

    private Task TestServicediscoveryGenServiceCreateService(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "CreateService", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateService",
            Params = "{\"Description\":\"compat scenario service\",\"Name\":{\"$name\":\"svc\"},\"NamespaceId\":{\"$ref\":\"namespace.id\"},\"Type\":\"HTTP\"}",
            Build = b =>
            {
                var request = new CreateServiceRequest();
                request.Description = "compat scenario service";
                request.Name = b.Bind<string>("Name", Val.Name("svc"));
                request.NamespaceId = b.Bind<string>("NamespaceId", Val.Ref("namespace.id"));
                request.Type = "HTTP";
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateServiceAsync((CreateServiceRequest)request),
            Export = new()
            {
                ["service.arn"] = "$.Service.Arn",
                ["service.id"] = "$.Service.Id",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Service.Arn"),
                Check.NonEmpty("$.Service.Id")
            ),
            Clause.Eventually(15, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetService",
                        Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetServiceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetServiceAsync((GetServiceRequest)request),
                    },
                    Check.EqualTo("$.Service.Id", Val.Ref("service.id"))
                )
            ),
            Clause.Eventually(15, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListServices",
                        Params = "{}",
                        Build = b =>
                        {
                            var request = new ListServicesRequest();
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListServicesAsync((ListServicesRequest)request),
                    },
                    "$.Services",
                    new WhereEntry("$.Id", Val.Ref("service.id"))
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceGetService(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "GetService", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetService",
            Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new GetServiceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetServiceAsync((GetServiceRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Service.Id", Val.Ref("service.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenServiceUpdateService(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "UpdateService", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateService",
            Params = "{\"Id\":{\"$ref\":\"service.id\"},\"Service\":{\"Description\":\"compat scenario service, updated\"}}",
            Build = b =>
            {
                var request = new UpdateServiceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                request.Service = new() { Description = "compat scenario service, updated" };
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateServiceAsync((UpdateServiceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetService",
                        Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetServiceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetServiceAsync((GetServiceRequest)request),
                    },
                    Check.EqualTo("$.Service.Description", "compat scenario service, updated")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceTagResource(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "TagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "TagResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"service.arn\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
            Build = b =>
            {
                var request = new TagResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("service.arn"));
                request.Tags = [new() { Key = "compat", Value = "scenario" }];
                return request;
            },
            SendAsync = async request =>
                await Cl().TagResourceAsync((TagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListTagsForResource",
                        Params = "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
                        Build = b =>
                        {
                            var request = new ListTagsForResourceRequest();
                            request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("service.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat"),
                    new WhereEntry("$.Value", "scenario")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceListTagsForResource(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "ListTagsForResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListTagsForResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
            Build = b =>
            {
                var request = new ListTagsForResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("service.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Tags",
                new WhereEntry("$.Key", "compat"),
                new WhereEntry("$.Value", "scenario")
            )
        ],
    });

    private Task TestServicediscoveryGenServiceUntagResource(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "UntagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UntagResource",
            Params = "{\"ResourceARN\":{\"$ref\":\"service.arn\"},\"TagKeys\":[\"compat\"]}",
            Build = b =>
            {
                var request = new UntagResourceRequest();
                request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("service.arn"));
                request.TagKeys = ["compat"];
                return request;
            },
            SendAsync = async request =>
                await Cl().UntagResourceAsync((UntagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListTagsForResource",
                        Params = "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
                        Build = b =>
                        {
                            var request = new ListTagsForResourceRequest();
                            request.ResourceARN = b.Bind<string>("ResourceARN", Val.Ref("service.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListTagsForResourceAsync((ListTagsForResourceRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceUpdateServiceAttributes(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "UpdateServiceAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateServiceAttributes",
            Params = "{\"Attributes\":{\"compat\":\"scenario\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new UpdateServiceAttributesRequest();
                request.Attributes = new() { ["compat"] = "scenario" };
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateServiceAttributesAsync((UpdateServiceAttributesRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetServiceAttributes",
                        Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetServiceAttributesRequest();
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetServiceAttributesAsync((GetServiceAttributesRequest)request),
                    },
                    Check.EqualTo("$.ServiceAttributes.Attributes.compat", "scenario")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceGetServiceAttributes(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "GetServiceAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetServiceAttributes",
            Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new GetServiceAttributesRequest();
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetServiceAttributesAsync((GetServiceAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ServiceAttributes.ServiceArn", Val.Ref("service.arn"))
            )
        ],
    });

    private Task TestServicediscoveryGenServiceDeleteServiceAttributes(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "DeleteServiceAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteServiceAttributes",
            Params = "{\"Attributes\":[\"compat\"],\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new DeleteServiceAttributesRequest();
                request.Attributes = ["compat"];
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteServiceAttributesAsync((DeleteServiceAttributesRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetServiceAttributes",
                        Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetServiceAttributesRequest();
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetServiceAttributesAsync((GetServiceAttributesRequest)request),
                    },
                    Check.Missing("$.ServiceAttributes.Attributes.compat")
                )
            )
        ],
    });

    private Task TestServicediscoveryGenServiceListInstances(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "ListInstances", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListInstances",
            Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new ListInstancesRequest();
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListInstancesAsync((ListInstancesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.Instances")
            )
        ],
    });

    private Task TestServicediscoveryGenServiceDiscoverInstances(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "DiscoverInstances", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DiscoverInstances",
            Params = "{\"NamespaceName\":{\"$name\":\"ns\"},\"ServiceName\":{\"$name\":\"svc\"}}",
            Build = b =>
            {
                var request = new DiscoverInstancesRequest();
                request.NamespaceName = b.Bind<string>("NamespaceName", Val.Name("ns"));
                request.ServiceName = b.Bind<string>("ServiceName", Val.Name("svc"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DiscoverInstancesAsync((DiscoverInstancesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.Instances")
            )
        ],
    });

    private Task TestServicediscoveryGenServiceListOperations(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "ListOperations", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListOperations",
            Params = "{\"Filters\":[{\"Condition\":\"EQ\",\"Name\":\"SERVICE_ID\",\"Values\":[{\"$ref\":\"service.id\"}]}]}",
            Build = b =>
            {
                var request = new ListOperationsRequest();
                request.Filters = [
                    new()
                    {
                        Condition = "EQ",
                        Name = "SERVICE_ID",
                        Values = [b.Bind<string>("Filters", Val.Ref("service.id"))],
                    },
                ];
                return request;
            },
            SendAsync = async request =>
                await Cl().ListOperationsAsync((ListOperationsRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.Operations")
            )
        ],
    });

    private Task TestServicediscoveryGenServiceListServices(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "ListServices", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListServices",
            Params = "{}",
            Build = b =>
            {
                var request = new ListServicesRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().ListServicesAsync((ListServicesRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Services",
                new WhereEntry("$.Id", Val.Ref("service.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenServiceDeleteService(TestContext t) => GroupServicediscoveryGenService.RunTestAsync(t, "DeleteService", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteService",
            Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new DeleteServiceRequest();
                request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteServiceAsync((DeleteServiceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(15, 2000,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetService",
                        Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetServiceRequest();
                            request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetServiceAsync((GetServiceRequest)request),
                    },
                    new ErrorSpec("ServiceNotFound", "ServiceNotFound"))
            )
        ],
    });

    private Task SetupServicediscoveryGenInstance(TestContext t) =>
        GroupServicediscoveryGenInstance.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateHttpNamespace",
                Params = "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
                Build = b =>
                {
                    var request = new CreateHttpNamespaceRequest();
                    request.Description = "compat scenario namespace";
                    request.Name = b.Bind<string>("Name", Val.Name("ns"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateHttpNamespaceAsync((CreateHttpNamespaceRequest)request),
                Export = new()
                {
                    ["namespace.operationId"] = "$.OperationId",
                },
            },
            new ScenarioCall
            {
                Op = "GetOperation",
                Params = "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                Build = b =>
                {
                    var request = new GetOperationRequest();
                    request.OperationId = b.Bind<string>("OperationId", Val.Ref("namespace.operationId"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().GetOperationAsync((GetOperationRequest)request),
                Export = new()
                {
                    ["namespace.id"] = "$.Operation.Targets.NAMESPACE",
                },
            },
            new ScenarioCall
            {
                Op = "CreateService",
                Params = "{\"Description\":\"compat scenario service\",\"Name\":{\"$name\":\"svc\"},\"NamespaceId\":{\"$ref\":\"namespace.id\"},\"Type\":\"HTTP\"}",
                Build = b =>
                {
                    var request = new CreateServiceRequest();
                    request.Description = "compat scenario service";
                    request.Name = b.Bind<string>("Name", Val.Name("svc"));
                    request.NamespaceId = b.Bind<string>("NamespaceId", Val.Ref("namespace.id"));
                    request.Type = "HTTP";
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateServiceAsync((CreateServiceRequest)request),
                Export = new()
                {
                    ["service.arn"] = "$.Service.Arn",
                    ["service.id"] = "$.Service.Id",
                },
            }
        );

    private Task TeardownServicediscoveryGenInstance(TestContext t) =>
        GroupServicediscoveryGenInstance.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeregisterInstance",
                Params = "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                Build = b =>
                {
                    var request = new DeregisterInstanceRequest();
                    request.InstanceId = b.Bind<string>("InstanceId", Val.Ref("instance.id"));
                    request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeregisterInstanceAsync((DeregisterInstanceRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteService",
                Params = "{\"Id\":{\"$ref\":\"service.id\"}}",
                Build = b =>
                {
                    var request = new DeleteServiceRequest();
                    request.Id = b.Bind<string>("Id", Val.Ref("service.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteServiceAsync((DeleteServiceRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteNamespace",
                Params = "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                Build = b =>
                {
                    var request = new DeleteNamespaceRequest();
                    request.Id = b.Bind<string>("Id", Val.Ref("namespace.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteNamespaceAsync((DeleteNamespaceRequest)request),
            }
        );

    private Task TestServicediscoveryGenInstanceRegisterInstance(TestContext t) => GroupServicediscoveryGenInstance.RunTestAsync(t, "RegisterInstance", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "RegisterInstance",
            Params = "{\"Attributes\":{\"AWS_INSTANCE_IPV4\":\"203.0.113.10\"},\"InstanceId\":{\"$name\":\"i\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new RegisterInstanceRequest();
                request.Attributes = new() { ["AWS_INSTANCE_IPV4"] = "203.0.113.10" };
                request.InstanceId = b.Bind<string>("InstanceId", Val.Name("i"));
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().RegisterInstanceAsync((RegisterInstanceRequest)request),
            Export = new()
            {
                ["instance.operationId"] = "$.OperationId",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.OperationId")
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetInstance",
                        Params = "{\"InstanceId\":{\"$name\":\"i\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetInstanceRequest();
                            request.InstanceId = b.Bind<string>("InstanceId", Val.Name("i"));
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetInstanceAsync((GetInstanceRequest)request),
                        Export = new()
                        {
                            ["instance.id"] = "$.Instance.Id",
                        },
                    },
                    Check.NonEmpty("$.Instance.Id")
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetInstance",
                        Params = "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetInstanceRequest();
                            request.InstanceId = b.Bind<string>("InstanceId", Val.Ref("instance.id"));
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetInstanceAsync((GetInstanceRequest)request),
                    },
                    Check.EqualTo("$.Instance.Id", Val.Ref("instance.id"))
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListInstances",
                        Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new ListInstancesRequest();
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListInstancesAsync((ListInstancesRequest)request),
                    },
                    "$.Instances",
                    new WhereEntry("$.Id", Val.Ref("instance.id"))
                )
            )
        ],
    });

    private Task TestServicediscoveryGenInstanceGetInstance(TestContext t) => GroupServicediscoveryGenInstance.RunTestAsync(t, "GetInstance", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetInstance",
            Params = "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new GetInstanceRequest();
                request.InstanceId = b.Bind<string>("InstanceId", Val.Ref("instance.id"));
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetInstanceAsync((GetInstanceRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Instance.Id", Val.Ref("instance.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenInstanceListInstances(TestContext t) => GroupServicediscoveryGenInstance.RunTestAsync(t, "ListInstances", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListInstances",
            Params = "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new ListInstancesRequest();
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListInstancesAsync((ListInstancesRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Instances",
                new WhereEntry("$.Id", Val.Ref("instance.id"))
            )
        ],
    });

    private Task TestServicediscoveryGenInstanceDeregisterInstance(TestContext t) => GroupServicediscoveryGenInstance.RunTestAsync(t, "DeregisterInstance", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeregisterInstance",
            Params = "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
            Build = b =>
            {
                var request = new DeregisterInstanceRequest();
                request.InstanceId = b.Bind<string>("InstanceId", Val.Ref("instance.id"));
                request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeregisterInstanceAsync((DeregisterInstanceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetInstance",
                        Params = "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        Build = b =>
                        {
                            var request = new GetInstanceRequest();
                            request.InstanceId = b.Bind<string>("InstanceId", Val.Ref("instance.id"));
                            request.ServiceId = b.Bind<string>("ServiceId", Val.Ref("service.id"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetInstanceAsync((GetInstanceRequest)request),
                    },
                    new ErrorSpec("InstanceNotFound", "InstanceNotFound"))
            )
        ],
    });

    private Task SetupServicediscoveryGenProbe(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupServicediscoveryGenProbe.RunSetupAsync(t);

    private Task TeardownServicediscoveryGenProbe(TestContext t) =>
        // No teardown steps: an empty phase is a no-op, not a missing one.
        GroupServicediscoveryGenProbe.RunTeardownAsync(t);

    private Task TestServicediscoveryGenProbeGetInstancesHealthStatus(TestContext t) => GroupServicediscoveryGenProbe.RunTestAsync(t, "GetInstancesHealthStatus", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetInstancesHealthStatus",
            Params = "{\"ServiceId\":\"srv-compatscenario00\"}",
            Build = b =>
            {
                var request = new GetInstancesHealthStatusRequest();
                request.ServiceId = "srv-compatscenario00";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetInstancesHealthStatusAsync((GetInstancesHealthStatusRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Status")
            )
        ],
    });

    private Task TestServicediscoveryGenProbeGetOperation(TestContext t) => GroupServicediscoveryGenProbe.RunTestAsync(t, "GetOperation", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetOperation",
            Params = "{\"OperationId\":\"compatscenariooperationnotfound0-00000000\"}",
            Build = b =>
            {
                var request = new GetOperationRequest();
                request.OperationId = "compatscenariooperationnotfound0-00000000";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetOperationAsync((GetOperationRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Operation")
            )
        ],
    });
}
