// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.SecretsManager;
using Amazon.SecretsManager.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The generated secretsmanager groups.</summary>
/// <remarks>
/// Generated from compat/model/scenarios/secretsmanager.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosSecretsmanager : IServiceGroup
{
    private static readonly ScenarioGroup GroupSecretsmanagerGenSecret = new("secretsmanager-gen-secret", "compat/model/scenarios/secretsmanager.json");
    private static readonly ScenarioGroup GroupSecretsmanagerGenVersion = new("secretsmanager-gen-version", "compat/model/scenarios/secretsmanager.json");

    private readonly Lazy<AmazonSecretsManagerClient> _client;

    internal ScenariosSecretsmanager(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonSecretsManagerClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonSecretsManagerClient(credentials, (AmazonSecretsManagerConfig)configuration),
            new AmazonSecretsManagerConfig()));
    }

    public string SourceName => "ScenariosSecretsmanager";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["secretsmanager-gen-secret:CreateSecret"] = TestSecretsmanagerGenSecretCreateSecret,
        ["secretsmanager-gen-secret:DescribeSecret"] = TestSecretsmanagerGenSecretDescribeSecret,
        ["secretsmanager-gen-secret:UpdateSecret"] = TestSecretsmanagerGenSecretUpdateSecret,
        ["secretsmanager-gen-secret:TagResource"] = TestSecretsmanagerGenSecretTagResource,
        ["secretsmanager-gen-secret:UntagResource"] = TestSecretsmanagerGenSecretUntagResource,
        ["secretsmanager-gen-secret:GetRandomPassword"] = TestSecretsmanagerGenSecretGetRandomPassword,
        ["secretsmanager-gen-secret:BatchGetSecretValue"] = TestSecretsmanagerGenSecretBatchGetSecretValue,
        ["secretsmanager-gen-secret:ValidateResourcePolicy"] = TestSecretsmanagerGenSecretValidateResourcePolicy,
        ["secretsmanager-gen-secret:PutResourcePolicy"] = TestSecretsmanagerGenSecretPutResourcePolicy,
        ["secretsmanager-gen-secret:GetResourcePolicy"] = TestSecretsmanagerGenSecretGetResourcePolicy,
        ["secretsmanager-gen-secret:DeleteResourcePolicy"] = TestSecretsmanagerGenSecretDeleteResourcePolicy,
        ["secretsmanager-gen-secret:CancelRotateSecret"] = TestSecretsmanagerGenSecretCancelRotateSecret,
        ["secretsmanager-gen-secret:ListSecrets"] = TestSecretsmanagerGenSecretListSecrets,
        ["secretsmanager-gen-secret:DeleteSecret"] = TestSecretsmanagerGenSecretDeleteSecret,
        ["secretsmanager-gen-version:PutSecretValue"] = TestSecretsmanagerGenVersionPutSecretValue,
        ["secretsmanager-gen-version:GetSecretValue"] = TestSecretsmanagerGenVersionGetSecretValue,
        ["secretsmanager-gen-version:UpdateSecretVersionStage"] = TestSecretsmanagerGenVersionUpdateSecretVersionStage,
        ["secretsmanager-gen-version:ListSecretVersionIds"] = TestSecretsmanagerGenVersionListSecretVersionIds,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["secretsmanager-gen-secret"] = SetupSecretsmanagerGenSecret,
        ["secretsmanager-gen-version"] = SetupSecretsmanagerGenVersion,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["secretsmanager-gen-secret"] = TeardownSecretsmanagerGenSecret,
        ["secretsmanager-gen-version"] = TeardownSecretsmanagerGenVersion,
    };

    private AmazonSecretsManagerClient Cl() => _client.Value;

    private Task SetupSecretsmanagerGenSecret(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupSecretsmanagerGenSecret.RunSetupAsync(t);

    private Task TeardownSecretsmanagerGenSecret(TestContext t) =>
        GroupSecretsmanagerGenSecret.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteSecret",
                Params = "{\"ForceDeleteWithoutRecovery\":true,\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                Build = b =>
                {
                    var request = new DeleteSecretRequest();
                    request.ForceDeleteWithoutRecovery = true;
                    request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteSecretAsync((DeleteSecretRequest)request),
            }
        );

    private Task TestSecretsmanagerGenSecretCreateSecret(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "CreateSecret", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateSecret",
            Params = "{\"Description\":\"compat scenario secret\",\"Name\":{\"$name\":\"s\"},\"SecretString\":\"compat-scenario-initial\"}",
            Build = b =>
            {
                var request = new CreateSecretRequest();
                request.Description = "compat scenario secret";
                request.Name = b.Bind<string>("Name", Val.Name("s"));
                request.SecretString = "compat-scenario-initial";
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateSecretAsync((CreateSecretRequest)request),
            Export = new()
            {
                ["secret.arn"] = "$.ARN",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.ARN")
            ),
            Clause.Eventually(10, 1000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeSecret",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new DescribeSecretRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
                    },
                    Check.EqualTo("$.ARN", Val.Ref("secret.arn")),
                    Check.EqualTo("$.Description", "compat scenario secret")
                )
            ),
            Clause.Eventually(10, 1000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListSecrets",
                        Params = "{\"Filters\":[{\"Key\":\"name\",\"Values\":[{\"$name\":\"s\"}]}]}",
                        Build = b =>
                        {
                            var request = new ListSecretsRequest();
                            request.Filters = [
                                new()
                                {
                                    Key = "name",
                                    Values = [b.Bind<string>("Filters", Val.Name("s"))],
                                },
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListSecretsAsync((ListSecretsRequest)request),
                    },
                    "$.SecretList",
                    new WhereEntry("$.ARN", Val.Ref("secret.arn"))
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretDescribeSecret(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "DescribeSecret", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeSecret",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new DescribeSecretRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ARN", Val.Ref("secret.arn"))
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretUpdateSecret(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "UpdateSecret", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateSecret",
            Params = "{\"Description\":\"compat scenario secret, updated\",\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new UpdateSecretRequest();
                request.Description = "compat scenario secret, updated";
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateSecretAsync((UpdateSecretRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeSecret",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new DescribeSecretRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
                    },
                    Check.EqualTo("$.Description", "compat scenario secret, updated")
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretTagResource(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "TagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "TagResource",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
            Build = b =>
            {
                var request = new TagResourceRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                request.Tags = [new() { Key = "compat", Value = "scenario" }];
                return request;
            },
            SendAsync = async request =>
                await Cl().TagResourceAsync((TagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "DescribeSecret",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new DescribeSecretRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat"),
                    new WhereEntry("$.Value", "scenario")
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretUntagResource(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "UntagResource", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UntagResource",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"TagKeys\":[\"compat\"]}",
            Build = b =>
            {
                var request = new UntagResourceRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                request.TagKeys = ["compat"];
                return request;
            },
            SendAsync = async request =>
                await Cl().UntagResourceAsync((UntagResourceRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "DescribeSecret",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new DescribeSecretRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
                    },
                    "$.Tags",
                    new WhereEntry("$.Key", "compat")
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretGetRandomPassword(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "GetRandomPassword", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetRandomPassword",
            Params = "{\"ExcludePunctuation\":true,\"PasswordLength\":24}",
            Build = b =>
            {
                var request = new GetRandomPasswordRequest();
                request.ExcludePunctuation = true;
                request.PasswordLength = 24L;
                return request;
            },
            SendAsync = async request =>
                await Cl().GetRandomPasswordAsync((GetRandomPasswordRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.Matches("$.RandomPassword", "^[A-Za-z0-9]{24}$")
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretBatchGetSecretValue(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "BatchGetSecretValue", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "BatchGetSecretValue",
            Params = "{\"SecretIdList\":[{\"$ref\":\"secret.arn\"}]}",
            Build = b =>
            {
                var request = new BatchGetSecretValueRequest();
                request.SecretIdList = [b.Bind<string>("SecretIdList", Val.Ref("secret.arn"))];
                return request;
            },
            SendAsync = async request =>
                await Cl().BatchGetSecretValueAsync((BatchGetSecretValueRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.SecretValues",
                new WhereEntry("$.ARN", Val.Ref("secret.arn")),
                new WhereEntry("$.SecretString", "compat-scenario-initial")
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretValidateResourcePolicy(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "ValidateResourcePolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ValidateResourcePolicy",
            Params = "{\"ResourcePolicy\":\"{\\\"Version\\\":\\\"2012-10-17\\\",\\\"Statement\\\":[{\\\"Effect\\\":\\\"Allow\\\",\\\"Principal\\\":{\\\"AWS\\\":\\\"arn:aws:iam::123456789012:root\\\"},\\\"Action\\\":\\\"secretsmanager:GetSecretValue\\\",\\\"Resource\\\":\\\"*\\\"}]}\",\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new ValidateResourcePolicyRequest();
                request.ResourcePolicy = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":\"secretsmanager:GetSecretValue\",\"Resource\":\"*\"}]}";
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ValidateResourcePolicyAsync((ValidateResourcePolicyRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.PolicyValidationPassed", true)
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretPutResourcePolicy(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "PutResourcePolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "PutResourcePolicy",
            Params = "{\"ResourcePolicy\":\"{\\\"Version\\\":\\\"2012-10-17\\\",\\\"Statement\\\":[{\\\"Effect\\\":\\\"Allow\\\",\\\"Principal\\\":{\\\"AWS\\\":\\\"arn:aws:iam::123456789012:root\\\"},\\\"Action\\\":\\\"secretsmanager:GetSecretValue\\\",\\\"Resource\\\":\\\"*\\\"}]}\",\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new PutResourcePolicyRequest();
                request.ResourcePolicy = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":\"secretsmanager:GetSecretValue\",\"Resource\":\"*\"}]}";
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().PutResourcePolicyAsync((PutResourcePolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetResourcePolicy",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new GetResourcePolicyRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetResourcePolicyAsync((GetResourcePolicyRequest)request),
                    },
                    Check.EqualTo("$.ARN", Val.Ref("secret.arn")),
                    Check.Matches("$.ResourcePolicy", "secretsmanager:GetSecretValue")
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretGetResourcePolicy(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "GetResourcePolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetResourcePolicy",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new GetResourcePolicyRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetResourcePolicyAsync((GetResourcePolicyRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ARN", Val.Ref("secret.arn")),
                Check.Matches("$.ResourcePolicy", "secretsmanager:GetSecretValue")
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretDeleteResourcePolicy(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "DeleteResourcePolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteResourcePolicy",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new DeleteResourcePolicyRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteResourcePolicyAsync((DeleteResourcePolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetResourcePolicy",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new GetResourcePolicyRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetResourcePolicyAsync((GetResourcePolicyRequest)request),
                    },
                    Check.Missing("$.ResourcePolicy")
                )
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretCancelRotateSecret(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "CancelRotateSecret", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CancelRotateSecret",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new CancelRotateSecretRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CancelRotateSecretAsync((CancelRotateSecretRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ARN", Val.Ref("secret.arn")),
                Check.EqualTo("$.Name", Val.Name("s"))
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretListSecrets(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "ListSecrets", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListSecrets",
            Params = "{\"Filters\":[{\"Key\":\"name\",\"Values\":[{\"$name\":\"s\"}]}]}",
            Build = b =>
            {
                var request = new ListSecretsRequest();
                request.Filters = [
                    new()
                    {
                        Key = "name",
                        Values = [b.Bind<string>("Filters", Val.Name("s"))],
                    },
                ];
                return request;
            },
            SendAsync = async request =>
                await Cl().ListSecretsAsync((ListSecretsRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.SecretList",
                new WhereEntry("$.ARN", Val.Ref("secret.arn"))
            )
        ],
    });

    private Task TestSecretsmanagerGenSecretDeleteSecret(TestContext t) => GroupSecretsmanagerGenSecret.RunTestAsync(t, "DeleteSecret", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteSecret",
            Params = "{\"ForceDeleteWithoutRecovery\":true,\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new DeleteSecretRequest();
                request.ForceDeleteWithoutRecovery = true;
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteSecretAsync((DeleteSecretRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 1000,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "DescribeSecret",
                        Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                        Build = b =>
                        {
                            var request = new DescribeSecretRequest();
                            request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeSecretAsync((DescribeSecretRequest)request),
                    },
                    new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException"))
            )
        ],
    });

    private Task SetupSecretsmanagerGenVersion(TestContext t) =>
        GroupSecretsmanagerGenVersion.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateSecret",
                Params = "{\"Description\":\"compat scenario secret\",\"Name\":{\"$name\":\"s\"},\"SecretString\":\"compat-scenario-initial\"}",
                Build = b =>
                {
                    var request = new CreateSecretRequest();
                    request.Description = "compat scenario secret";
                    request.Name = b.Bind<string>("Name", Val.Name("s"));
                    request.SecretString = "compat-scenario-initial";
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateSecretAsync((CreateSecretRequest)request),
                Export = new()
                {
                    ["secret.arn"] = "$.ARN",
                },
            }
        );

    private Task TeardownSecretsmanagerGenVersion(TestContext t) =>
        GroupSecretsmanagerGenVersion.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteSecret",
                Params = "{\"ForceDeleteWithoutRecovery\":true,\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                Build = b =>
                {
                    var request = new DeleteSecretRequest();
                    request.ForceDeleteWithoutRecovery = true;
                    request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteSecretAsync((DeleteSecretRequest)request),
            }
        );

    private Task TestSecretsmanagerGenVersionPutSecretValue(TestContext t) => GroupSecretsmanagerGenVersion.RunTestAsync(t, "PutSecretValue", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "PutSecretValue",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"SecretString\":\"compat scenario version value\"}",
            Build = b =>
            {
                var request = new PutSecretValueRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                request.SecretString = "compat scenario version value";
                return request;
            },
            SendAsync = async request =>
                await Cl().PutSecretValueAsync((PutSecretValueRequest)request),
            Export = new()
            {
                ["version.id"] = "$.VersionId",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.VersionId")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetSecretValue",
                    Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"VersionId\":{\"$ref\":\"version.id\"}}",
                    Build = b =>
                    {
                        var request = new GetSecretValueRequest();
                        request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                        request.VersionId = b.Bind<string>("VersionId", Val.Ref("version.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetSecretValueAsync((GetSecretValueRequest)request),
                },
                Check.EqualTo("$.VersionId", Val.Ref("version.id"))
            ),
            Clause.ListContains(
                new ScenarioCall
                {
                    Op = "ListSecretVersionIds",
                    Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
                    Build = b =>
                    {
                        var request = new ListSecretVersionIdsRequest();
                        request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListSecretVersionIdsAsync((ListSecretVersionIdsRequest)request),
                },
                "$.Versions",
                new WhereEntry("$.VersionId", Val.Ref("version.id"))
            )
        ],
    });

    private Task TestSecretsmanagerGenVersionGetSecretValue(TestContext t) => GroupSecretsmanagerGenVersion.RunTestAsync(t, "GetSecretValue", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetSecretValue",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"VersionId\":{\"$ref\":\"version.id\"}}",
            Build = b =>
            {
                var request = new GetSecretValueRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                request.VersionId = b.Bind<string>("VersionId", Val.Ref("version.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetSecretValueAsync((GetSecretValueRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.VersionId", Val.Ref("version.id"))
            )
        ],
    });

    private Task TestSecretsmanagerGenVersionUpdateSecretVersionStage(TestContext t) => GroupSecretsmanagerGenVersion.RunTestAsync(t, "UpdateSecretVersionStage", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateSecretVersionStage",
            Params = "{\"MoveToVersionId\":{\"$ref\":\"version.id\"},\"SecretId\":{\"$ref\":\"secret.arn\"},\"VersionStage\":\"COMPATSCENARIO\"}",
            Build = b =>
            {
                var request = new UpdateSecretVersionStageRequest();
                request.MoveToVersionId = b.Bind<string>("MoveToVersionId", Val.Ref("version.id"));
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                request.VersionStage = "COMPATSCENARIO";
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateSecretVersionStageAsync((UpdateSecretVersionStageRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ARN", Val.Ref("secret.arn"))
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetSecretValue",
                    Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"},\"VersionStage\":\"COMPATSCENARIO\"}",
                    Build = b =>
                    {
                        var request = new GetSecretValueRequest();
                        request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                        request.VersionStage = "COMPATSCENARIO";
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetSecretValueAsync((GetSecretValueRequest)request),
                },
                Check.EqualTo("$.SecretString", "compat scenario version value"),
                Check.EqualTo("$.VersionId", Val.Ref("version.id"))
            )
        ],
    });

    private Task TestSecretsmanagerGenVersionListSecretVersionIds(TestContext t) => GroupSecretsmanagerGenVersion.RunTestAsync(t, "ListSecretVersionIds", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListSecretVersionIds",
            Params = "{\"SecretId\":{\"$ref\":\"secret.arn\"}}",
            Build = b =>
            {
                var request = new ListSecretVersionIdsRequest();
                request.SecretId = b.Bind<string>("SecretId", Val.Ref("secret.arn"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListSecretVersionIdsAsync((ListSecretVersionIdsRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Versions",
                new WhereEntry("$.VersionId", Val.Ref("version.id"))
            )
        ],
    });
}
