// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.ErrorSpec;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import io.overcast.compat.scenario.Where;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.servicediscovery.ServiceDiscoveryClient;
import software.amazon.awssdk.services.servicediscovery.model.CreateHttpNamespaceRequest;
import software.amazon.awssdk.services.servicediscovery.model.CreateServiceRequest;
import software.amazon.awssdk.services.servicediscovery.model.DeleteNamespaceRequest;
import software.amazon.awssdk.services.servicediscovery.model.DeleteServiceAttributesRequest;
import software.amazon.awssdk.services.servicediscovery.model.DeleteServiceRequest;
import software.amazon.awssdk.services.servicediscovery.model.DeregisterInstanceRequest;
import software.amazon.awssdk.services.servicediscovery.model.DiscoverInstancesRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetInstanceRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetInstancesHealthStatusRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetNamespaceRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetOperationRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetServiceAttributesRequest;
import software.amazon.awssdk.services.servicediscovery.model.GetServiceRequest;
import software.amazon.awssdk.services.servicediscovery.model.HttpNamespaceChange;
import software.amazon.awssdk.services.servicediscovery.model.ListInstancesRequest;
import software.amazon.awssdk.services.servicediscovery.model.ListNamespacesRequest;
import software.amazon.awssdk.services.servicediscovery.model.ListOperationsRequest;
import software.amazon.awssdk.services.servicediscovery.model.ListServicesRequest;
import software.amazon.awssdk.services.servicediscovery.model.ListTagsForResourceRequest;
import software.amazon.awssdk.services.servicediscovery.model.OperationFilter;
import software.amazon.awssdk.services.servicediscovery.model.RegisterInstanceRequest;
import software.amazon.awssdk.services.servicediscovery.model.ServiceChange;
import software.amazon.awssdk.services.servicediscovery.model.Tag;
import software.amazon.awssdk.services.servicediscovery.model.TagResourceRequest;
import software.amazon.awssdk.services.servicediscovery.model.UntagResourceRequest;
import software.amazon.awssdk.services.servicediscovery.model.UpdateHttpNamespaceRequest;
import software.amazon.awssdk.services.servicediscovery.model.UpdateServiceAttributesRequest;
import software.amazon.awssdk.services.servicediscovery.model.UpdateServiceRequest;

/**
 * The generated servicediscovery groups.
 *
 * <p>Generated from compat/model/scenarios/servicediscovery.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosServicediscoveryGen implements ServiceGroup {

    private static final Group GROUP_SERVICEDISCOVERY_GEN_NAMESPACE =
            new Group("servicediscovery-gen-namespace", "compat/model/scenarios/servicediscovery.json");
    private static final Group GROUP_SERVICEDISCOVERY_GEN_SERVICE =
            new Group("servicediscovery-gen-service", "compat/model/scenarios/servicediscovery.json");
    private static final Group GROUP_SERVICEDISCOVERY_GEN_INSTANCE =
            new Group("servicediscovery-gen-instance", "compat/model/scenarios/servicediscovery.json");
    private static final Group GROUP_SERVICEDISCOVERY_GEN_PROBE =
            new Group("servicediscovery-gen-probe", "compat/model/scenarios/servicediscovery.json");

    private final AwsClients clients;
    private volatile ServiceDiscoveryClient client;

    public ScenariosServicediscoveryGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/servicediscovery";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("servicediscovery-gen-namespace:CreateHttpNamespace", this::testServicediscoveryGenNamespaceCreateHttpNamespace),
                Map.entry("servicediscovery-gen-namespace:GetNamespace", this::testServicediscoveryGenNamespaceGetNamespace),
                Map.entry("servicediscovery-gen-namespace:UpdateHttpNamespace", this::testServicediscoveryGenNamespaceUpdateHttpNamespace),
                Map.entry("servicediscovery-gen-namespace:TagResource", this::testServicediscoveryGenNamespaceTagResource),
                Map.entry("servicediscovery-gen-namespace:ListTagsForResource", this::testServicediscoveryGenNamespaceListTagsForResource),
                Map.entry("servicediscovery-gen-namespace:UntagResource", this::testServicediscoveryGenNamespaceUntagResource),
                Map.entry("servicediscovery-gen-namespace:ListNamespaces", this::testServicediscoveryGenNamespaceListNamespaces),
                Map.entry("servicediscovery-gen-namespace:DeleteNamespace", this::testServicediscoveryGenNamespaceDeleteNamespace),
                Map.entry("servicediscovery-gen-service:CreateService", this::testServicediscoveryGenServiceCreateService),
                Map.entry("servicediscovery-gen-service:GetService", this::testServicediscoveryGenServiceGetService),
                Map.entry("servicediscovery-gen-service:UpdateService", this::testServicediscoveryGenServiceUpdateService),
                Map.entry("servicediscovery-gen-service:TagResource", this::testServicediscoveryGenServiceTagResource),
                Map.entry("servicediscovery-gen-service:ListTagsForResource", this::testServicediscoveryGenServiceListTagsForResource),
                Map.entry("servicediscovery-gen-service:UntagResource", this::testServicediscoveryGenServiceUntagResource),
                Map.entry("servicediscovery-gen-service:UpdateServiceAttributes", this::testServicediscoveryGenServiceUpdateServiceAttributes),
                Map.entry("servicediscovery-gen-service:GetServiceAttributes", this::testServicediscoveryGenServiceGetServiceAttributes),
                Map.entry("servicediscovery-gen-service:DeleteServiceAttributes", this::testServicediscoveryGenServiceDeleteServiceAttributes),
                Map.entry("servicediscovery-gen-service:ListInstances", this::testServicediscoveryGenServiceListInstances),
                Map.entry("servicediscovery-gen-service:DiscoverInstances", this::testServicediscoveryGenServiceDiscoverInstances),
                Map.entry("servicediscovery-gen-service:ListOperations", this::testServicediscoveryGenServiceListOperations),
                Map.entry("servicediscovery-gen-service:ListServices", this::testServicediscoveryGenServiceListServices),
                Map.entry("servicediscovery-gen-service:DeleteService", this::testServicediscoveryGenServiceDeleteService),
                Map.entry("servicediscovery-gen-instance:RegisterInstance", this::testServicediscoveryGenInstanceRegisterInstance),
                Map.entry("servicediscovery-gen-instance:GetInstance", this::testServicediscoveryGenInstanceGetInstance),
                Map.entry("servicediscovery-gen-instance:ListInstances", this::testServicediscoveryGenInstanceListInstances),
                Map.entry("servicediscovery-gen-instance:DeregisterInstance", this::testServicediscoveryGenInstanceDeregisterInstance),
                Map.entry("servicediscovery-gen-probe:GetInstancesHealthStatus", this::testServicediscoveryGenProbeGetInstancesHealthStatus),
                Map.entry("servicediscovery-gen-probe:GetOperation", this::testServicediscoveryGenProbeGetOperation));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("servicediscovery-gen-namespace", this::setupServicediscoveryGenNamespace),
                Map.entry("servicediscovery-gen-service", this::setupServicediscoveryGenService),
                Map.entry("servicediscovery-gen-instance", this::setupServicediscoveryGenInstance),
                Map.entry("servicediscovery-gen-probe", this::setupServicediscoveryGenProbe));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("servicediscovery-gen-namespace", this::teardownServicediscoveryGenNamespace),
                Map.entry("servicediscovery-gen-service", this::teardownServicediscoveryGenService),
                Map.entry("servicediscovery-gen-instance", this::teardownServicediscoveryGenInstance),
                Map.entry("servicediscovery-gen-probe", this::teardownServicediscoveryGenProbe));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private ServiceDiscoveryClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(ServiceDiscoveryClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupServicediscoveryGenNamespace(TestContext t) {
        // No setup steps: an empty phase is a no-op, not a missing one.
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runSetup(t);
    }

    private void teardownServicediscoveryGenNamespace(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTeardown(t,
                new Call("DeleteNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        b -> DeleteNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .build(),
                        r -> cl().deleteNamespace((DeleteNamespaceRequest) r)));
    }

    private void testServicediscoveryGenNamespaceCreateHttpNamespace(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "CreateHttpNamespace",
                new Call("CreateHttpNamespace", "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
                        b -> CreateHttpNamespaceRequest.builder()
                                .description("compat scenario namespace")
                                .name(b.string("Name", Values.name("ns")))
                                .build(),
                        r -> cl().createHttpNamespace((CreateHttpNamespaceRequest) r))
                        .export("namespace.operationId", "$.OperationId"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.OperationId")
                        ),
                        Clause.eventually(30, 2000,
                                Clause.readback(
                                        new Call("GetOperation", "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                                                b -> GetOperationRequest.builder()
                                                        .operationId(b.string("OperationId", Values.ref("namespace.operationId")))
                                                        .build(),
                                                r -> cl().getOperation((GetOperationRequest) r))
                                                .export("namespace.id", "$.Operation.Targets.NAMESPACE"),
                                        Check.nonEmpty("$.Operation.Targets.NAMESPACE")
                                )),
                        Clause.eventually(30, 2000,
                                Clause.readback(
                                        new Call("GetNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                                                b -> GetNamespaceRequest.builder()
                                                        .id(b.string("Id", Values.ref("namespace.id")))
                                                        .build(),
                                                r -> cl().getNamespace((GetNamespaceRequest) r)),
                                        Check.equalTo("$.Namespace.Id", Values.ref("namespace.id"))
                                )),
                        Clause.eventually(30, 2000,
                                Clause.listContains(
                                        new Call("ListNamespaces", "{}",
                                                b -> ListNamespacesRequest.builder()
                                                        .build(),
                                                r -> cl().listNamespaces((ListNamespacesRequest) r)),
                                        "$.Namespaces",
                                        Where.of("$.Id", Values.ref("namespace.id"))
                                ))
                ));
    }

    private void testServicediscoveryGenNamespaceGetNamespace(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "GetNamespace",
                new Call("GetNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        b -> GetNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .build(),
                        r -> cl().getNamespace((GetNamespaceRequest) r))
                        .export("namespace.arn", "$.Namespace.Arn"),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Namespace.Id", Values.ref("namespace.id"))
                        )
                ));
    }

    private void testServicediscoveryGenNamespaceUpdateHttpNamespace(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "UpdateHttpNamespace",
                new Call("UpdateHttpNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"},\"Namespace\":{\"Description\":\"compat scenario namespace, updated\"}}",
                        b -> UpdateHttpNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .namespace(HttpNamespaceChange.builder().description("compat scenario namespace, updated").build())
                                .build(),
                        r -> cl().updateHttpNamespace((UpdateHttpNamespaceRequest) r)),
                List.of(
                        Clause.eventually(30, 2000,
                                Clause.readback(
                                        new Call("GetNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                                                b -> GetNamespaceRequest.builder()
                                                        .id(b.string("Id", Values.ref("namespace.id")))
                                                        .build(),
                                                r -> cl().getNamespace((GetNamespaceRequest) r)),
                                        Check.equalTo("$.Namespace.Description", "compat scenario namespace, updated")
                                ))
                ));
    }

    private void testServicediscoveryGenNamespaceTagResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "TagResource",
                new Call("TagResource", "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
                        b -> TagResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("namespace.arn")))
                                .tags(List.of(Tag.builder().key("compat").value("scenario").build()))
                                .build(),
                        r -> cl().tagResource((TagResourceRequest) r)),
                List.of(
                        Clause.eventually(30, 2000,
                                Clause.listContains(
                                        new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
                                                b -> ListTagsForResourceRequest.builder()
                                                        .resourceARN(b.string("ResourceARN", Values.ref("namespace.arn")))
                                                        .build(),
                                                r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                        "$.Tags",
                                        Where.of("$.Key", "compat"),
                                        Where.of("$.Value", "scenario")
                                ))
                ));
    }

    private void testServicediscoveryGenNamespaceListTagsForResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "ListTagsForResource",
                new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
                        b -> ListTagsForResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("namespace.arn")))
                                .build(),
                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Tags",
                                Where.of("$.Key", "compat"),
                                Where.of("$.Value", "scenario")
                        )
                ));
    }

    private void testServicediscoveryGenNamespaceUntagResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "UntagResource",
                new Call("UntagResource", "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"},\"TagKeys\":[\"compat\"]}",
                        b -> UntagResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("namespace.arn")))
                                .tagKeys(List.of("compat"))
                                .build(),
                        r -> cl().untagResource((UntagResourceRequest) r)),
                List.of(
                        Clause.eventually(30, 2000,
                                Clause.absentFromList(
                                        new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"namespace.arn\"}}",
                                                b -> ListTagsForResourceRequest.builder()
                                                        .resourceARN(b.string("ResourceARN", Values.ref("namespace.arn")))
                                                        .build(),
                                                r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                        "$.Tags",
                                        Where.of("$.Key", "compat")
                                ))
                ));
    }

    private void testServicediscoveryGenNamespaceListNamespaces(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "ListNamespaces",
                new Call("ListNamespaces", "{}",
                        b -> ListNamespacesRequest.builder()
                                .build(),
                        r -> cl().listNamespaces((ListNamespacesRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Namespaces",
                                Where.of("$.Id", Values.ref("namespace.id"))
                        )
                ));
    }

    private void testServicediscoveryGenNamespaceDeleteNamespace(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_NAMESPACE.runTest(t, "DeleteNamespace",
                new Call("DeleteNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        b -> DeleteNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .build(),
                        r -> cl().deleteNamespace((DeleteNamespaceRequest) r)),
                List.of(
                        Clause.eventually(30, 2000,
                                Clause.absentByError(
                                        new Call("GetNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                                                b -> GetNamespaceRequest.builder()
                                                        .id(b.string("Id", Values.ref("namespace.id")))
                                                        .build(),
                                                r -> cl().getNamespace((GetNamespaceRequest) r)),
                                        ErrorSpec.of("NamespaceNotFound", "NamespaceNotFound")))
                ));
    }

    private void setupServicediscoveryGenService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runSetup(t,
                new Call("CreateHttpNamespace", "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
                        b -> CreateHttpNamespaceRequest.builder()
                                .description("compat scenario namespace")
                                .name(b.string("Name", Values.name("ns")))
                                .build(),
                        r -> cl().createHttpNamespace((CreateHttpNamespaceRequest) r))
                        .export("namespace.operationId", "$.OperationId"),
                new Call("GetOperation", "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                        b -> GetOperationRequest.builder()
                                .operationId(b.string("OperationId", Values.ref("namespace.operationId")))
                                .build(),
                        r -> cl().getOperation((GetOperationRequest) r))
                        .export("namespace.id", "$.Operation.Targets.NAMESPACE"));
    }

    private void teardownServicediscoveryGenService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTeardown(t,
                new Call("DeleteService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                        b -> DeleteServiceRequest.builder()
                                .id(b.string("Id", Values.ref("service.id")))
                                .build(),
                        r -> cl().deleteService((DeleteServiceRequest) r)),
                new Call("DeleteNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        b -> DeleteNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .build(),
                        r -> cl().deleteNamespace((DeleteNamespaceRequest) r)));
    }

    private void testServicediscoveryGenServiceCreateService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "CreateService",
                new Call("CreateService", "{\"Description\":\"compat scenario service\",\"Name\":{\"$name\":\"svc\"},\"NamespaceId\":{\"$ref\":\"namespace.id\"},\"Type\":\"HTTP\"}",
                        b -> CreateServiceRequest.builder()
                                .description("compat scenario service")
                                .name(b.string("Name", Values.name("svc")))
                                .namespaceId(b.string("NamespaceId", Values.ref("namespace.id")))
                                .type("HTTP")
                                .build(),
                        r -> cl().createService((CreateServiceRequest) r))
                        .export("service.arn", "$.Service.Arn")
                        .export("service.id", "$.Service.Id"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.Service.Arn"),
                                Check.nonEmpty("$.Service.Id")
                        ),
                        Clause.eventually(15, 2000,
                                Clause.readback(
                                        new Call("GetService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                                                b -> GetServiceRequest.builder()
                                                        .id(b.string("Id", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getService((GetServiceRequest) r)),
                                        Check.equalTo("$.Service.Id", Values.ref("service.id"))
                                )),
                        Clause.eventually(15, 2000,
                                Clause.listContains(
                                        new Call("ListServices", "{}",
                                                b -> ListServicesRequest.builder()
                                                        .build(),
                                                r -> cl().listServices((ListServicesRequest) r)),
                                        "$.Services",
                                        Where.of("$.Id", Values.ref("service.id"))
                                ))
                ));
    }

    private void testServicediscoveryGenServiceGetService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "GetService",
                new Call("GetService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                        b -> GetServiceRequest.builder()
                                .id(b.string("Id", Values.ref("service.id")))
                                .build(),
                        r -> cl().getService((GetServiceRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Service.Id", Values.ref("service.id"))
                        )
                ));
    }

    private void testServicediscoveryGenServiceUpdateService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "UpdateService",
                new Call("UpdateService", "{\"Id\":{\"$ref\":\"service.id\"},\"Service\":{\"Description\":\"compat scenario service, updated\"}}",
                        b -> UpdateServiceRequest.builder()
                                .id(b.string("Id", Values.ref("service.id")))
                                .service(ServiceChange.builder().description("compat scenario service, updated").build())
                                .build(),
                        r -> cl().updateService((UpdateServiceRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.readback(
                                        new Call("GetService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                                                b -> GetServiceRequest.builder()
                                                        .id(b.string("Id", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getService((GetServiceRequest) r)),
                                        Check.equalTo("$.Service.Description", "compat scenario service, updated")
                                ))
                ));
    }

    private void testServicediscoveryGenServiceTagResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "TagResource",
                new Call("TagResource", "{\"ResourceARN\":{\"$ref\":\"service.arn\"},\"Tags\":[{\"Key\":\"compat\",\"Value\":\"scenario\"}]}",
                        b -> TagResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("service.arn")))
                                .tags(List.of(Tag.builder().key("compat").value("scenario").build()))
                                .build(),
                        r -> cl().tagResource((TagResourceRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.listContains(
                                        new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
                                                b -> ListTagsForResourceRequest.builder()
                                                        .resourceARN(b.string("ResourceARN", Values.ref("service.arn")))
                                                        .build(),
                                                r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                        "$.Tags",
                                        Where.of("$.Key", "compat"),
                                        Where.of("$.Value", "scenario")
                                ))
                ));
    }

    private void testServicediscoveryGenServiceListTagsForResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "ListTagsForResource",
                new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
                        b -> ListTagsForResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("service.arn")))
                                .build(),
                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Tags",
                                Where.of("$.Key", "compat"),
                                Where.of("$.Value", "scenario")
                        )
                ));
    }

    private void testServicediscoveryGenServiceUntagResource(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "UntagResource",
                new Call("UntagResource", "{\"ResourceARN\":{\"$ref\":\"service.arn\"},\"TagKeys\":[\"compat\"]}",
                        b -> UntagResourceRequest.builder()
                                .resourceARN(b.string("ResourceARN", Values.ref("service.arn")))
                                .tagKeys(List.of("compat"))
                                .build(),
                        r -> cl().untagResource((UntagResourceRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.absentFromList(
                                        new Call("ListTagsForResource", "{\"ResourceARN\":{\"$ref\":\"service.arn\"}}",
                                                b -> ListTagsForResourceRequest.builder()
                                                        .resourceARN(b.string("ResourceARN", Values.ref("service.arn")))
                                                        .build(),
                                                r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                        "$.Tags",
                                        Where.of("$.Key", "compat")
                                ))
                ));
    }

    private void testServicediscoveryGenServiceUpdateServiceAttributes(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "UpdateServiceAttributes",
                new Call("UpdateServiceAttributes", "{\"Attributes\":{\"compat\":\"scenario\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> UpdateServiceAttributesRequest.builder()
                                .attributes(Map.of("compat", "scenario"))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().updateServiceAttributes((UpdateServiceAttributesRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.readback(
                                        new Call("GetServiceAttributes", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> GetServiceAttributesRequest.builder()
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getServiceAttributes((GetServiceAttributesRequest) r)),
                                        Check.equalTo("$.ServiceAttributes.Attributes.compat", "scenario")
                                ))
                ));
    }

    private void testServicediscoveryGenServiceGetServiceAttributes(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "GetServiceAttributes",
                new Call("GetServiceAttributes", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> GetServiceAttributesRequest.builder()
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().getServiceAttributes((GetServiceAttributesRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.ServiceAttributes.ServiceArn", Values.ref("service.arn"))
                        )
                ));
    }

    private void testServicediscoveryGenServiceDeleteServiceAttributes(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "DeleteServiceAttributes",
                new Call("DeleteServiceAttributes", "{\"Attributes\":[\"compat\"],\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> DeleteServiceAttributesRequest.builder()
                                .attributes(List.of("compat"))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().deleteServiceAttributes((DeleteServiceAttributesRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.readback(
                                        new Call("GetServiceAttributes", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> GetServiceAttributesRequest.builder()
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getServiceAttributes((GetServiceAttributesRequest) r)),
                                        Check.missing("$.ServiceAttributes.Attributes.compat")
                                ))
                ));
    }

    private void testServicediscoveryGenServiceListInstances(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "ListInstances",
                new Call("ListInstances", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> ListInstancesRequest.builder()
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().listInstances((ListInstancesRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.isList("$.Instances")
                        )
                ));
    }

    private void testServicediscoveryGenServiceDiscoverInstances(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "DiscoverInstances",
                new Call("DiscoverInstances", "{\"NamespaceName\":{\"$name\":\"ns\"},\"ServiceName\":{\"$name\":\"svc\"}}",
                        b -> DiscoverInstancesRequest.builder()
                                .namespaceName(b.string("NamespaceName", Values.name("ns")))
                                .serviceName(b.string("ServiceName", Values.name("svc")))
                                .build(),
                        r -> cl().discoverInstances((DiscoverInstancesRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.isList("$.Instances")
                        )
                ));
    }

    private void testServicediscoveryGenServiceListOperations(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "ListOperations",
                new Call("ListOperations", "{\"Filters\":[{\"Condition\":\"EQ\",\"Name\":\"SERVICE_ID\",\"Values\":[{\"$ref\":\"service.id\"}]}]}",
                        b -> ListOperationsRequest.builder()
                                .filters(List.of(OperationFilter.builder().condition("EQ").name("SERVICE_ID").values(List.of(b.string("Filters", Values.ref("service.id")))).build()))
                                .build(),
                        r -> cl().listOperations((ListOperationsRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.isList("$.Operations")
                        )
                ));
    }

    private void testServicediscoveryGenServiceListServices(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "ListServices",
                new Call("ListServices", "{}",
                        b -> ListServicesRequest.builder()
                                .build(),
                        r -> cl().listServices((ListServicesRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Services",
                                Where.of("$.Id", Values.ref("service.id"))
                        )
                ));
    }

    private void testServicediscoveryGenServiceDeleteService(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_SERVICE.runTest(t, "DeleteService",
                new Call("DeleteService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                        b -> DeleteServiceRequest.builder()
                                .id(b.string("Id", Values.ref("service.id")))
                                .build(),
                        r -> cl().deleteService((DeleteServiceRequest) r)),
                List.of(
                        Clause.eventually(15, 2000,
                                Clause.absentByError(
                                        new Call("GetService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                                                b -> GetServiceRequest.builder()
                                                        .id(b.string("Id", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getService((GetServiceRequest) r)),
                                        ErrorSpec.of("ServiceNotFound", "ServiceNotFound")))
                ));
    }

    private void setupServicediscoveryGenInstance(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runSetup(t,
                new Call("CreateHttpNamespace", "{\"Description\":\"compat scenario namespace\",\"Name\":{\"$name\":\"ns\"}}",
                        b -> CreateHttpNamespaceRequest.builder()
                                .description("compat scenario namespace")
                                .name(b.string("Name", Values.name("ns")))
                                .build(),
                        r -> cl().createHttpNamespace((CreateHttpNamespaceRequest) r))
                        .export("namespace.operationId", "$.OperationId"),
                new Call("GetOperation", "{\"OperationId\":{\"$ref\":\"namespace.operationId\"}}",
                        b -> GetOperationRequest.builder()
                                .operationId(b.string("OperationId", Values.ref("namespace.operationId")))
                                .build(),
                        r -> cl().getOperation((GetOperationRequest) r))
                        .export("namespace.id", "$.Operation.Targets.NAMESPACE"),
                new Call("CreateService", "{\"Description\":\"compat scenario service\",\"Name\":{\"$name\":\"svc\"},\"NamespaceId\":{\"$ref\":\"namespace.id\"},\"Type\":\"HTTP\"}",
                        b -> CreateServiceRequest.builder()
                                .description("compat scenario service")
                                .name(b.string("Name", Values.name("svc")))
                                .namespaceId(b.string("NamespaceId", Values.ref("namespace.id")))
                                .type("HTTP")
                                .build(),
                        r -> cl().createService((CreateServiceRequest) r))
                        .export("service.arn", "$.Service.Arn")
                        .export("service.id", "$.Service.Id"));
    }

    private void teardownServicediscoveryGenInstance(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runTeardown(t,
                new Call("DeregisterInstance", "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> DeregisterInstanceRequest.builder()
                                .instanceId(b.string("InstanceId", Values.ref("instance.id")))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().deregisterInstance((DeregisterInstanceRequest) r)),
                new Call("DeleteService", "{\"Id\":{\"$ref\":\"service.id\"}}",
                        b -> DeleteServiceRequest.builder()
                                .id(b.string("Id", Values.ref("service.id")))
                                .build(),
                        r -> cl().deleteService((DeleteServiceRequest) r)),
                new Call("DeleteNamespace", "{\"Id\":{\"$ref\":\"namespace.id\"}}",
                        b -> DeleteNamespaceRequest.builder()
                                .id(b.string("Id", Values.ref("namespace.id")))
                                .build(),
                        r -> cl().deleteNamespace((DeleteNamespaceRequest) r)));
    }

    private void testServicediscoveryGenInstanceRegisterInstance(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runTest(t, "RegisterInstance",
                new Call("RegisterInstance", "{\"Attributes\":{\"AWS_INSTANCE_IPV4\":\"203.0.113.10\"},\"InstanceId\":{\"$name\":\"i\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> RegisterInstanceRequest.builder()
                                .attributes(Map.of("AWS_INSTANCE_IPV4", "203.0.113.10"))
                                .instanceId(b.string("InstanceId", Values.name("i")))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().registerInstance((RegisterInstanceRequest) r))
                        .export("instance.operationId", "$.OperationId"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.OperationId")
                        ),
                        Clause.eventually(30, 2000,
                                Clause.readback(
                                        new Call("GetInstance", "{\"InstanceId\":{\"$name\":\"i\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> GetInstanceRequest.builder()
                                                        .instanceId(b.string("InstanceId", Values.name("i")))
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getInstance((GetInstanceRequest) r))
                                                .export("instance.id", "$.Instance.Id"),
                                        Check.nonEmpty("$.Instance.Id")
                                )),
                        Clause.eventually(30, 2000,
                                Clause.readback(
                                        new Call("GetInstance", "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> GetInstanceRequest.builder()
                                                        .instanceId(b.string("InstanceId", Values.ref("instance.id")))
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getInstance((GetInstanceRequest) r)),
                                        Check.equalTo("$.Instance.Id", Values.ref("instance.id"))
                                )),
                        Clause.eventually(30, 2000,
                                Clause.listContains(
                                        new Call("ListInstances", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> ListInstancesRequest.builder()
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().listInstances((ListInstancesRequest) r)),
                                        "$.Instances",
                                        Where.of("$.Id", Values.ref("instance.id"))
                                ))
                ));
    }

    private void testServicediscoveryGenInstanceGetInstance(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runTest(t, "GetInstance",
                new Call("GetInstance", "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> GetInstanceRequest.builder()
                                .instanceId(b.string("InstanceId", Values.ref("instance.id")))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().getInstance((GetInstanceRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Instance.Id", Values.ref("instance.id"))
                        )
                ));
    }

    private void testServicediscoveryGenInstanceListInstances(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runTest(t, "ListInstances",
                new Call("ListInstances", "{\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> ListInstancesRequest.builder()
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().listInstances((ListInstancesRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Instances",
                                Where.of("$.Id", Values.ref("instance.id"))
                        )
                ));
    }

    private void testServicediscoveryGenInstanceDeregisterInstance(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_INSTANCE.runTest(t, "DeregisterInstance",
                new Call("DeregisterInstance", "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                        b -> DeregisterInstanceRequest.builder()
                                .instanceId(b.string("InstanceId", Values.ref("instance.id")))
                                .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                .build(),
                        r -> cl().deregisterInstance((DeregisterInstanceRequest) r)),
                List.of(
                        Clause.eventually(30, 2000,
                                Clause.absentByError(
                                        new Call("GetInstance", "{\"InstanceId\":{\"$ref\":\"instance.id\"},\"ServiceId\":{\"$ref\":\"service.id\"}}",
                                                b -> GetInstanceRequest.builder()
                                                        .instanceId(b.string("InstanceId", Values.ref("instance.id")))
                                                        .serviceId(b.string("ServiceId", Values.ref("service.id")))
                                                        .build(),
                                                r -> cl().getInstance((GetInstanceRequest) r)),
                                        ErrorSpec.of("InstanceNotFound", "InstanceNotFound")))
                ));
    }

    private void setupServicediscoveryGenProbe(TestContext t) {
        // No setup steps: an empty phase is a no-op, not a missing one.
        GROUP_SERVICEDISCOVERY_GEN_PROBE.runSetup(t);
    }

    private void teardownServicediscoveryGenProbe(TestContext t) {
        // No teardown steps: an empty phase is a no-op, not a missing one.
        GROUP_SERVICEDISCOVERY_GEN_PROBE.runTeardown(t);
    }

    private void testServicediscoveryGenProbeGetInstancesHealthStatus(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_PROBE.runTest(t, "GetInstancesHealthStatus",
                new Call("GetInstancesHealthStatus", "{\"ServiceId\":\"srv-compatscenario00\"}",
                        b -> GetInstancesHealthStatusRequest.builder()
                                .serviceId("srv-compatscenario00")
                                .build(),
                        r -> cl().getInstancesHealthStatus((GetInstancesHealthStatusRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.Status")
                        )
                ));
    }

    private void testServicediscoveryGenProbeGetOperation(TestContext t) {
        GROUP_SERVICEDISCOVERY_GEN_PROBE.runTest(t, "GetOperation",
                new Call("GetOperation", "{\"OperationId\":\"compatscenariooperationnotfound0-00000000\"}",
                        b -> GetOperationRequest.builder()
                                .operationId("compatscenariooperationnotfound0-00000000")
                                .build(),
                        r -> cl().getOperation((GetOperationRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.Operation")
                        )
                ));
    }
}
