//go:build dev

package ec2

import "github.com/Neaox/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		capabilities.Capability{Service: "ec2", Operation: "AcceptVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "Transitions from `pending-acceptance` to `active`"},
		capabilities.Capability{Service: "ec2", Operation: "AllocateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates eipalloc- ID and synthetic public IP"},
		capabilities.Capability{Service: "ec2", Operation: "AssociateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "Associates EIP with instance; generates eipassoc- ID"},
		capabilities.Capability{Service: "ec2", Operation: "AssociateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Associates route table with subnet"},
		capabilities.Capability{Service: "ec2", Operation: "AttachInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Toggles VPC Docker network from `--internal` to external (bridge)"},
		capabilities.Capability{Service: "ec2", Operation: "AttachVpnGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Metadata-only VPC attachment"},
		capabilities.Capability{Service: "ec2", Operation: "AuthorizeSecurityGroupEgress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "AuthorizeSecurityGroupIngress", Category: "General", Status: capabilities.StatusSupported, Notes: "IpPermissions with protocol, ports, CIDR ranges"},
		capabilities.Capability{Service: "ec2", Operation: "CreateInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates igw-xxx ID"},
		capabilities.Capability{Service: "ec2", Operation: "CreateKeyPair", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates dummy fingerprint and key material"},
		capabilities.Capability{Service: "ec2", Operation: "CreateNatGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Requires subnet and EIP; supports TagSpecification"},
		capabilities.Capability{Service: "ec2", Operation: "CreateNetworkInterface", Category: "General", Status: capabilities.StatusSupported, Notes: "Requires subnet; assigns synthetic private IP"},
		capabilities.Capability{Service: "ec2", Operation: "CreateRoute", Category: "General", Status: capabilities.StatusSupported, Notes: "DestinationCidrBlock + GatewayId or NatGatewayId"},
		capabilities.Capability{Service: "ec2", Operation: "CreateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "VPC must exist; auto-creates local route"},
		capabilities.Capability{Service: "ec2", Operation: "CreateSecurityGroup", Category: "General", Status: capabilities.StatusSupported, Notes: "Default egress allow-all rule added on create"},
		capabilities.Capability{Service: "ec2", Operation: "CreateSubnet", Category: "General", Status: capabilities.StatusSupported, Notes: "VPC must exist; honors AvailabilityZone; defaults to region+\"a\""},
		capabilities.Capability{Service: "ec2", Operation: "CreateTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Tag any resource by ID; visible to that resource's own describe"},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpc", Category: "General", Status: capabilities.StatusSupported, Notes: "CidrBlock required; creates Docker bridge network (`--internal` unless IGW attached) and main route table"},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpcEndpoint", Category: "General", Status: capabilities.StatusSupported, Notes: "Metadata-only; Gateway and Interface types accepted; state always \"available\""},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpnGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Metadata-only; type ipsec.1 with AmazonSideAsn"},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "Both VPCs must exist; starts in `pending-acceptance` state"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Must be detached first"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteKeyPair", Category: "General", Status: capabilities.StatusSupported, Notes: "Idempotent (no error if not found)"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteNatGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Marks as deleted"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteNetworkInterface", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteRoute", Category: "General", Status: capabilities.StatusSupported, Notes: "Removes route by RouteTableId + DestinationCidrBlock"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Cannot delete main route table"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteSecurityGroup", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteSubnet", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Remove tags by key; a resource's tags are removed with the resource"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpc", Category: "General", Status: capabilities.StatusSupported, Notes: "Removes Docker network; fails if subnets/IGW attached"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpcEndpoints", Category: "General", Status: capabilities.StatusSupported, Notes: "Accepts VpcEndpointId.N; silently skips unknown IDs"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpnGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Requires gateway to be detached"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "From `active` or `pending-acceptance`; transitions to `deleted`"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAccountAttributes", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded defaults (supported-platforms, max-instances…)"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAddresses", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by AllocationId.N; Filters: allocation-id, association-id, domain, instance-id, network-interface-id, private-ip-address, public-ip"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAvailabilityZones", Category: "General", Status: capabilities.StatusSupported, Notes: "3 AZs per region (a, b, c); Filters: region-name, state, zone-name"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeDhcpOptions", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns a fabricated default DHCP options set; Filters: none"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeImages", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded set of 4 AMIs (AL2, Ubuntu, Windows, AL2023); selects by ImageId.N; Filters: architecture, description, image-id, image-type, is-public, name, owner-id, root-device-type, state, virtualization-type"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInstanceTypes", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded set: t3.micro/small/medium, m5.large/xlarge; Filters: current-generation, instance-type, memory-info.size-in-mib, vcpu-info.default-vcpus"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by InstanceId.N; Filters: availability-zone, image-id, instance-id, instance-state-code, instance-state-name, instance-type, placement.availability-zone, subnet-id, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInternetGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by InternetGatewayId.N; Filters: attachment.state, attachment.vpc-id, internet-gateway-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeKeyPairs", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by KeyName.N; Filters: fingerprint, key-name, key-pair-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeNatGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by NatGatewayId.N; Filters: nat-gateway-id, state, subnet-id, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeNetworkInterfaces", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by NetworkInterfaceId.N; Filters: availability-zone, description, mac-address, network-interface-id, status, subnet-id, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeRegions", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded list of 8 regions; Filters: endpoint, opt-in-status, region-name"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeRouteTables", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by RouteTableId.N; includes NAT gateway routes; Filters: association.main, association.route-table-association-id, association.subnet-id, route-table-id, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeSecurityGroups", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by GroupId.N; Filters: description, group-id, group-name, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeSubnets", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by SubnetId.N; includes tagSet for CDK subnet groups; Filters: availability-zone, cidr-block, state, subnet-id, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Filters: key, resource-id, resource-type, value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns enableDnsSupport or enableDnsHostnames"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcEndpoints", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by VpcEndpointId.N; Filters: service-name, vpc-endpoint-id, vpc-endpoint-state, vpc-endpoint-type, vpc-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpnGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by VpnGatewayId.N; Filters: amazon-side-asn, attachment.state, attachment.vpc-id, availability-zone, state, type, vpn-gateway-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcPeeringConnections", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by VpcPeeringConnectionId.N; Filters: accepter-vpc-info.vpc-id, requester-vpc-info.vpc-id, status-code, vpc-peering-connection-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcs", Category: "General", Status: capabilities.StatusSupported, Notes: "Selects by VpcId.N; Filters: cidr, isDefault, state, vpc-id, tag:<key>, tag-key, tag-value"},
		capabilities.Capability{Service: "ec2", Operation: "DetachInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Toggles VPC Docker network back to `--internal`"},
		capabilities.Capability{Service: "ec2", Operation: "DetachVpnGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Metadata-only VPC detachment"},
		capabilities.Capability{Service: "ec2", Operation: "DisassociateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "By AssociationId"},
		capabilities.Capability{Service: "ec2", Operation: "DisassociateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Cannot disassociate main association"},
		capabilities.Capability{Service: "ec2", Operation: "ModifyInstanceAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "InstanceType.Value persisted; all other attributes accepted"},
		capabilities.Capability{Service: "ec2", Operation: "ModifySubnetAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "MapPublicIpOnLaunch (metadata only)"},
		capabilities.Capability{Service: "ec2", Operation: "ModifyVpcAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "EnableDnsSupport, EnableDnsHostnames (metadata only)"},
		capabilities.Capability{Service: "ec2", Operation: "ReleaseAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "By AllocationId"},
		capabilities.Capability{Service: "ec2", Operation: "RevokeSecurityGroupEgress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "RevokeSecurityGroupIngress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "RunInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "MinCount/MaxCount, TagSpecifications, async pending→running"},
		capabilities.Capability{Service: "ec2", Operation: "StartInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "From stopped state only"},
		capabilities.Capability{Service: "ec2", Operation: "StopInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "From running state only; async stopping→stopped"},
		capabilities.Capability{Service: "ec2", Operation: "TerminateInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "Async shutting-down→terminated transition"},
		capabilities.Capability{Service: "ec2", Operation: "unbacked", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "No Docker network (Docker unavailable, or the last create failed)", DocOnly: true},
		capabilities.Capability{Service: "ec2", Operation: "conflict", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "Reserved for strict mode when CIDR collides with another existing VPC", DocOnly: true},
		capabilities.Capability{Service: "ec2", Operation: "remapped", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "Reserved for remapped mode and backed by a shadow CIDR", DocOnly: true},
	)
}
