//go:build dev

package ec2

import "github.com/Neaox/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		capabilities.Capability{Service: "ec2", Operation: "AcceptVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "Transitions from `pending-acceptance` to `active`"},
		capabilities.Capability{Service: "ec2", Operation: "AllocateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates eipalloc- ID and synthetic public IP"},
		capabilities.Capability{Service: "ec2", Operation: "AssociateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "Associates EIP with instance; generates eipassoc- ID"},
		capabilities.Capability{Service: "ec2", Operation: "AssociateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Associates route table with subnet"},
		capabilities.Capability{Service: "ec2", Operation: "AttachInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Toggles VPC Docker network from `--internal` to external (bridge)"},
		capabilities.Capability{Service: "ec2", Operation: "AuthorizeSecurityGroupEgress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "AuthorizeSecurityGroupIngress", Category: "General", Status: capabilities.StatusSupported, Notes: "IpPermissions with protocol, ports, CIDR ranges"},
		capabilities.Capability{Service: "ec2", Operation: "CreateInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates igw-xxx ID"},
		capabilities.Capability{Service: "ec2", Operation: "CreateKeyPair", Category: "General", Status: capabilities.StatusSupported, Notes: "Generates dummy fingerprint and key material"},
		capabilities.Capability{Service: "ec2", Operation: "CreateNatGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Requires subnet and EIP; supports TagSpecification"},
		capabilities.Capability{Service: "ec2", Operation: "CreateNetworkInterface", Category: "General", Status: capabilities.StatusSupported, Notes: "Requires subnet; assigns synthetic private IP"},
		capabilities.Capability{Service: "ec2", Operation: "CreateRoute", Category: "General", Status: capabilities.StatusSupported, Notes: "DestinationCidrBlock + GatewayId"},
		capabilities.Capability{Service: "ec2", Operation: "CreateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "VPC must exist; auto-creates local route"},
		capabilities.Capability{Service: "ec2", Operation: "CreateSecurityGroup", Category: "General", Status: capabilities.StatusSupported, Notes: "Default egress allow-all rule added on create"},
		capabilities.Capability{Service: "ec2", Operation: "CreateSubnet", Category: "General", Status: capabilities.StatusSupported, Notes: "VPC must exist; AZ defaults to region+\"a\""},
		capabilities.Capability{Service: "ec2", Operation: "CreateTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Tag any resource by ID"},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpc", Category: "General", Status: capabilities.StatusSupported, Notes: "CidrBlock required; creates Docker bridge network (`--internal` unless IGW attached) and main route table"},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpcEndpoint", Category: "General", Status: capabilities.StatusSupported, Notes: "Metadata-only; Gateway and Interface types accepted; state always \"available\""},
		capabilities.Capability{Service: "ec2", Operation: "CreateVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "Both VPCs must exist; starts in `pending-acceptance` state"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Must be detached first"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteKeyPair", Category: "General", Status: capabilities.StatusSupported, Notes: "Idempotent (no error if not found)"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteNatGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Marks as deleted"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteNetworkInterface", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteRoute", Category: "General", Status: capabilities.StatusSupported, Notes: "Removes route by RouteTableId + DestinationCidrBlock"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Cannot delete main route table"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteSecurityGroup", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteSubnet", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "DeleteTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Remove tags by key from resources"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpc", Category: "General", Status: capabilities.StatusSupported, Notes: "Removes Docker network; fails if subnets/IGW attached"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpcEndpoints", Category: "General", Status: capabilities.StatusSupported, Notes: "Accepts VpcEndpointId.N; silently skips unknown IDs"},
		capabilities.Capability{Service: "ec2", Operation: "DeleteVpcPeeringConnection", Category: "General", Status: capabilities.StatusSupported, Notes: "From `active` or `pending-acceptance`; transitions to `deleted`"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAccountAttributes", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded defaults (supported-platforms, max-instances…)"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAddresses", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by AllocationId"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeAvailabilityZones", Category: "General", Status: capabilities.StatusSupported, Notes: "3 AZs per region (a, b, c)"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeDhcpOptions", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns default DHCP options set for the VPC"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeImages", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded set of 4 AMIs (AL2, Ubuntu, Windows, AL2023); filter by ImageId"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInstanceTypes", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded set: t3.micro/small/medium, m5.large/xlarge"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by instance-id, instance-state-name"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeInternetGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by internet-gateway-id, attachment.vpc-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeKeyPairs", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by KeyName"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeNatGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by nat-gateway-id, vpc-id, subnet-id, state"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeNetworkInterfaces", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by network-interface-id, subnet-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeRegions", Category: "General", Status: capabilities.StatusSupported, Notes: "Hardcoded list of 8 regions"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeRouteTables", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by route-table-id, vpc-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeSecurityGroups", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by group-id, group-name, vpc-id"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeSubnets", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by subnet-id, vpc-id, availability-zone"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeTags", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by resource-id, resource-type, key"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns enableDnsSupport or enableDnsHostnames"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcEndpoints", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by VpcEndpointId.N, vpc-id filter, service-name filter"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpnGateways", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns an empty vpnGatewaySet"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcPeeringConnections", Category: "General", Status: capabilities.StatusSupported, Notes: "Filter by ID, status-code, requester/accepter VPC"},
		capabilities.Capability{Service: "ec2", Operation: "DescribeVpcs", Category: "General", Status: capabilities.StatusSupported, Notes: "Lists all VPCs; filter by VpcId"},
		capabilities.Capability{Service: "ec2", Operation: "DetachInternetGateway", Category: "General", Status: capabilities.StatusSupported, Notes: "Toggles VPC Docker network back to `--internal`"},
		capabilities.Capability{Service: "ec2", Operation: "DisassociateAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "By AssociationId"},
		capabilities.Capability{Service: "ec2", Operation: "DisassociateRouteTable", Category: "General", Status: capabilities.StatusSupported, Notes: "Cannot disassociate main association"},
		capabilities.Capability{Service: "ec2", Operation: "ModifyInstanceAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "InstanceType.Value persisted; all other attributes accepted"},
		capabilities.Capability{Service: "ec2", Operation: "ModifySubnetAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "MapPublicIpOnLaunch (metadata only)"},
		capabilities.Capability{Service: "ec2", Operation: "ModifyVpcAttribute", Category: "General", Status: capabilities.StatusSupported, Notes: "EnableDnsSupport, EnableDnsHostnames (metadata only)"},
		capabilities.Capability{Service: "ec2", Operation: "ReleaseAddress", Category: "General", Status: capabilities.StatusSupported, Notes: "By AllocationId"},
		capabilities.Capability{Service: "ec2", Operation: "RevokeSecurityGroupEgress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "RevokeSecurityGroupIngress", Category: "General", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ec2", Operation: "RunInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "MinCount/MaxCount, TagSpecifications, async pending→running"},
		capabilities.Capability{Service: "ec2", Operation: "StartInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "From stopped state only"},
		capabilities.Capability{Service: "ec2", Operation: "StopInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "From running state only; async stopping→stopped"},
		capabilities.Capability{Service: "ec2", Operation: "TerminateInstances", Category: "General", Status: capabilities.StatusSupported, Notes: "Async shutting-down→terminated transition"},
		capabilities.Capability{Service: "ec2", Operation: "unbacked", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "No Docker network (Docker unavailable, or the last create failed)", DocOnly: true},
		capabilities.Capability{Service: "ec2", Operation: "conflict", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "Reserved for strict mode when CIDR collides with another existing VPC", DocOnly: true},
		capabilities.Capability{Service: "ec2", Operation: "remapped", Category: "VPC network states", Status: capabilities.StatusSupported, Notes: "Reserved for remapped mode and backed by a shadow CIDR", DocOnly: true},
	)
}
