// Code generated by cmd/compatgen; DO NOT EDIT.

package groups

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/servicediscovery"
	"github.com/aws/aws-sdk-go-v2/service/servicediscovery/types"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/clients"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/harness"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/scenario"
)

// ScenariosServicediscovery returns the generated servicediscovery groups.
//
// Generated from compat/model/scenarios/servicediscovery.json by cmd/compatgen.
// The semantics live in internal/scenario; this file is the data and the
// typed SDK calls.
func ScenariosServicediscovery(c *clients.Clients) ServiceGroup {
	g := &servicediscoveryScenarios{c: c}
	return ServiceGroup{
		Name: "scenarios/servicediscovery",
		Impls: map[string]harness.TestFn{
			"servicediscovery-gen-namespace:CreateHttpNamespace":   g.testServicediscoveryGenNamespaceCreateHttpNamespace,
			"servicediscovery-gen-namespace:GetNamespace":          g.testServicediscoveryGenNamespaceGetNamespace,
			"servicediscovery-gen-namespace:UpdateHttpNamespace":   g.testServicediscoveryGenNamespaceUpdateHttpNamespace,
			"servicediscovery-gen-namespace:TagResource":           g.testServicediscoveryGenNamespaceTagResource,
			"servicediscovery-gen-namespace:ListTagsForResource":   g.testServicediscoveryGenNamespaceListTagsForResource,
			"servicediscovery-gen-namespace:UntagResource":         g.testServicediscoveryGenNamespaceUntagResource,
			"servicediscovery-gen-namespace:ListNamespaces":        g.testServicediscoveryGenNamespaceListNamespaces,
			"servicediscovery-gen-namespace:DeleteNamespace":       g.testServicediscoveryGenNamespaceDeleteNamespace,
			"servicediscovery-gen-service:CreateService":           g.testServicediscoveryGenServiceCreateService,
			"servicediscovery-gen-service:GetService":              g.testServicediscoveryGenServiceGetService,
			"servicediscovery-gen-service:UpdateService":           g.testServicediscoveryGenServiceUpdateService,
			"servicediscovery-gen-service:TagResource":             g.testServicediscoveryGenServiceTagResource,
			"servicediscovery-gen-service:ListTagsForResource":     g.testServicediscoveryGenServiceListTagsForResource,
			"servicediscovery-gen-service:UntagResource":           g.testServicediscoveryGenServiceUntagResource,
			"servicediscovery-gen-service:UpdateServiceAttributes": g.testServicediscoveryGenServiceUpdateServiceAttributes,
			"servicediscovery-gen-service:GetServiceAttributes":    g.testServicediscoveryGenServiceGetServiceAttributes,
			"servicediscovery-gen-service:DeleteServiceAttributes": g.testServicediscoveryGenServiceDeleteServiceAttributes,
			"servicediscovery-gen-service:ListInstances":           g.testServicediscoveryGenServiceListInstances,
			"servicediscovery-gen-service:DiscoverInstances":       g.testServicediscoveryGenServiceDiscoverInstances,
			"servicediscovery-gen-service:ListOperations":          g.testServicediscoveryGenServiceListOperations,
			"servicediscovery-gen-service:ListServices":            g.testServicediscoveryGenServiceListServices,
			"servicediscovery-gen-service:DeleteService":           g.testServicediscoveryGenServiceDeleteService,
			"servicediscovery-gen-instance:RegisterInstance":       g.testServicediscoveryGenInstanceRegisterInstance,
			"servicediscovery-gen-instance:GetInstance":            g.testServicediscoveryGenInstanceGetInstance,
			"servicediscovery-gen-instance:ListInstances":          g.testServicediscoveryGenInstanceListInstances,
			"servicediscovery-gen-instance:DeregisterInstance":     g.testServicediscoveryGenInstanceDeregisterInstance,
			"servicediscovery-gen-probe:GetInstancesHealthStatus":  g.testServicediscoveryGenProbeGetInstancesHealthStatus,
			"servicediscovery-gen-probe:GetOperation":              g.testServicediscoveryGenProbeGetOperation,
		},
		Setup: map[string]func(context.Context, *harness.TestContext) error{
			"servicediscovery-gen-namespace": g.setupServicediscoveryGenNamespace,
			"servicediscovery-gen-service":   g.setupServicediscoveryGenService,
			"servicediscovery-gen-instance":  g.setupServicediscoveryGenInstance,
			"servicediscovery-gen-probe":     g.setupServicediscoveryGenProbe,
		},
		Teardown: map[string]func(context.Context, *harness.TestContext) error{
			"servicediscovery-gen-namespace": g.teardownServicediscoveryGenNamespace,
			"servicediscovery-gen-service":   g.teardownServicediscoveryGenService,
			"servicediscovery-gen-instance":  g.teardownServicediscoveryGenInstance,
			"servicediscovery-gen-probe":     g.teardownServicediscoveryGenProbe,
		},
	}
}

type servicediscoveryScenarios struct {
	c      *clients.Clients
	once   sync.Once
	client *servicediscovery.Client
}

// cl builds this service's client once, from the config the suite's
// hand-written groups share. A generated group builds its own rather than
// adding an accessor to internal/clients for every service the generator
// learns to cover; nothing else about the client differs.
func (g *servicediscoveryScenarios) cl() *servicediscovery.Client {
	g.once.Do(func() { g.client = servicediscovery.NewFromConfig(g.c.Config()) })
	return g.client
}

var groupServicediscoveryGenNamespace = scenario.Group{Name: "servicediscovery-gen-namespace", File: "compat/model/scenarios/servicediscovery.json"}

func (g *servicediscoveryScenarios) setupServicediscoveryGenNamespace(ctx context.Context, t *harness.TestContext) error {
	// No setup steps: an empty phase is a no-op, not a missing one.
	return groupServicediscoveryGenNamespace.RunSetup(ctx, t)
}

func (g *servicediscoveryScenarios) teardownServicediscoveryGenNamespace(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "DeleteNamespace",
			Params: `{"Id":{"$ref":"namespace.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteNamespace(ctx, in.(*servicediscovery.DeleteNamespaceInput))
			},
		},
	)
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceCreateHttpNamespace(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "CreateHttpNamespace", scenario.Test{
		Call: scenario.Call{
			Op:     "CreateHttpNamespace",
			Params: `{"Description":"compat scenario namespace","Name":{"$name":"ns"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.CreateHttpNamespaceInput{}
				in.Description = aws.String("compat scenario namespace")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("ns")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateHttpNamespace(ctx, in.(*servicediscovery.CreateHttpNamespaceInput))
			},
			Export: map[string]string{
				"namespace.operationId": "$.OperationId",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.OperationId"),
			),
			scenario.Eventually(30, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetOperation",
						Params: `{"OperationId":{"$ref":"namespace.operationId"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetOperationInput{}
							in.OperationId = aws.String(scenario.Bind[string](b, "OperationId", scenario.Ref("namespace.operationId")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetOperation(ctx, in.(*servicediscovery.GetOperationInput))
						},
						Export: map[string]string{
							"namespace.id": "$.Operation.Targets.NAMESPACE",
						},
					},
					scenario.NonEmpty("$.Operation.Targets.NAMESPACE"),
				),
			),
			scenario.Eventually(30, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetNamespace",
						Params: `{"Id":{"$ref":"namespace.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetNamespaceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetNamespace(ctx, in.(*servicediscovery.GetNamespaceInput))
						},
					},
					scenario.Equals("$.Namespace.Id", scenario.Ref("namespace.id")),
				),
			),
			scenario.Eventually(30, 2000,
				scenario.ListContains(
					&scenario.Call{
						Op:     "ListNamespaces",
						Params: `{}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListNamespacesInput{}
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListNamespaces(ctx, in.(*servicediscovery.ListNamespacesInput))
						},
					},
					"$.Namespaces",
					scenario.Where("$.Id", scenario.Ref("namespace.id")),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceGetNamespace(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "GetNamespace", scenario.Test{
		Call: scenario.Call{
			Op:     "GetNamespace",
			Params: `{"Id":{"$ref":"namespace.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetNamespace(ctx, in.(*servicediscovery.GetNamespaceInput))
			},
			Export: map[string]string{
				"namespace.arn": "$.Namespace.Arn",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Namespace.Id", scenario.Ref("namespace.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceUpdateHttpNamespace(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "UpdateHttpNamespace", scenario.Test{
		Call: scenario.Call{
			Op:     "UpdateHttpNamespace",
			Params: `{"Id":{"$ref":"namespace.id"},"Namespace":{"Description":"compat scenario namespace, updated"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.UpdateHttpNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				in.Namespace = &types.HttpNamespaceChange{
					Description: aws.String("compat scenario namespace, updated"),
				}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UpdateHttpNamespace(ctx, in.(*servicediscovery.UpdateHttpNamespaceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(30, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetNamespace",
						Params: `{"Id":{"$ref":"namespace.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetNamespaceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetNamespace(ctx, in.(*servicediscovery.GetNamespaceInput))
						},
					},
					scenario.Equals("$.Namespace.Description", "compat scenario namespace, updated"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceTagResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "TagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "TagResource",
			Params: `{"ResourceARN":{"$ref":"namespace.arn"},"Tags":[{"Key":"compat","Value":"scenario"}]}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.TagResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("namespace.arn")))
				in.Tags = []types.Tag{{Key: aws.String("compat"), Value: aws.String("scenario")}}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().TagResource(ctx, in.(*servicediscovery.TagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(30, 2000,
				scenario.ListContains(
					&scenario.Call{
						Op:     "ListTagsForResource",
						Params: `{"ResourceARN":{"$ref":"namespace.arn"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListTagsForResourceInput{}
							in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("namespace.arn")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
						},
					},
					"$.Tags",
					scenario.Where("$.Key", "compat"),
					scenario.Where("$.Value", "scenario"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceListTagsForResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "ListTagsForResource", scenario.Test{
		Call: scenario.Call{
			Op:     "ListTagsForResource",
			Params: `{"ResourceARN":{"$ref":"namespace.arn"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListTagsForResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("namespace.arn")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Tags",
				scenario.Where("$.Key", "compat"),
				scenario.Where("$.Value", "scenario"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceUntagResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "UntagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "UntagResource",
			Params: `{"ResourceARN":{"$ref":"namespace.arn"},"TagKeys":["compat"]}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.UntagResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("namespace.arn")))
				in.TagKeys = []string{"compat"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UntagResource(ctx, in.(*servicediscovery.UntagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(30, 2000,
				scenario.AbsentFromList(
					&scenario.Call{
						Op:     "ListTagsForResource",
						Params: `{"ResourceARN":{"$ref":"namespace.arn"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListTagsForResourceInput{}
							in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("namespace.arn")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
						},
					},
					"$.Tags",
					scenario.Where("$.Key", "compat"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceListNamespaces(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "ListNamespaces", scenario.Test{
		Call: scenario.Call{
			Op:     "ListNamespaces",
			Params: `{}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListNamespacesInput{}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListNamespaces(ctx, in.(*servicediscovery.ListNamespacesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Namespaces",
				scenario.Where("$.Id", scenario.Ref("namespace.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenNamespaceDeleteNamespace(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenNamespace.RunTest(ctx, t, "DeleteNamespace", scenario.Test{
		Call: scenario.Call{
			Op:     "DeleteNamespace",
			Params: `{"Id":{"$ref":"namespace.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteNamespace(ctx, in.(*servicediscovery.DeleteNamespaceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(30, 2000,
				scenario.AbsentByError(
					scenario.Call{
						Op:     "GetNamespace",
						Params: `{"Id":{"$ref":"namespace.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetNamespaceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetNamespace(ctx, in.(*servicediscovery.GetNamespaceInput))
						},
					},
					scenario.Error("NamespaceNotFound", "NamespaceNotFound"),
				),
			),
		},
	})
}

var groupServicediscoveryGenService = scenario.Group{Name: "servicediscovery-gen-service", File: "compat/model/scenarios/servicediscovery.json"}

func (g *servicediscoveryScenarios) setupServicediscoveryGenService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunSetup(ctx, t,
		scenario.Call{
			Op:     "CreateHttpNamespace",
			Params: `{"Description":"compat scenario namespace","Name":{"$name":"ns"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.CreateHttpNamespaceInput{}
				in.Description = aws.String("compat scenario namespace")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("ns")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateHttpNamespace(ctx, in.(*servicediscovery.CreateHttpNamespaceInput))
			},
			Export: map[string]string{
				"namespace.operationId": "$.OperationId",
			},
		},
		scenario.Call{
			Op:     "GetOperation",
			Params: `{"OperationId":{"$ref":"namespace.operationId"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetOperationInput{}
				in.OperationId = aws.String(scenario.Bind[string](b, "OperationId", scenario.Ref("namespace.operationId")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetOperation(ctx, in.(*servicediscovery.GetOperationInput))
			},
			Export: map[string]string{
				"namespace.id": "$.Operation.Targets.NAMESPACE",
			},
		},
	)
}

func (g *servicediscoveryScenarios) teardownServicediscoveryGenService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "DeleteService",
			Params: `{"Id":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteServiceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteService(ctx, in.(*servicediscovery.DeleteServiceInput))
			},
		},
		scenario.Call{
			Op:     "DeleteNamespace",
			Params: `{"Id":{"$ref":"namespace.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteNamespace(ctx, in.(*servicediscovery.DeleteNamespaceInput))
			},
		},
	)
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceCreateService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "CreateService", scenario.Test{
		Call: scenario.Call{
			Op:     "CreateService",
			Params: `{"Description":"compat scenario service","Name":{"$name":"svc"},"NamespaceId":{"$ref":"namespace.id"},"Type":"HTTP"}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.CreateServiceInput{}
				in.Description = aws.String("compat scenario service")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("svc")))
				in.NamespaceId = aws.String(scenario.Bind[string](b, "NamespaceId", scenario.Ref("namespace.id")))
				in.Type = types.ServiceTypeOption("HTTP")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateService(ctx, in.(*servicediscovery.CreateServiceInput))
			},
			Export: map[string]string{
				"service.arn": "$.Service.Arn",
				"service.id":  "$.Service.Id",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.Service.Arn"),
				scenario.NonEmpty("$.Service.Id"),
			),
			scenario.Eventually(15, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetService",
						Params: `{"Id":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetServiceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetService(ctx, in.(*servicediscovery.GetServiceInput))
						},
					},
					scenario.Equals("$.Service.Id", scenario.Ref("service.id")),
				),
			),
			scenario.Eventually(15, 2000,
				scenario.ListContains(
					&scenario.Call{
						Op:     "ListServices",
						Params: `{}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListServicesInput{}
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListServices(ctx, in.(*servicediscovery.ListServicesInput))
						},
					},
					"$.Services",
					scenario.Where("$.Id", scenario.Ref("service.id")),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceGetService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "GetService", scenario.Test{
		Call: scenario.Call{
			Op:     "GetService",
			Params: `{"Id":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetServiceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetService(ctx, in.(*servicediscovery.GetServiceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Service.Id", scenario.Ref("service.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceUpdateService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "UpdateService", scenario.Test{
		Call: scenario.Call{
			Op:     "UpdateService",
			Params: `{"Id":{"$ref":"service.id"},"Service":{"Description":"compat scenario service, updated"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.UpdateServiceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
				in.Service = &types.ServiceChange{Description: aws.String("compat scenario service, updated")}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UpdateService(ctx, in.(*servicediscovery.UpdateServiceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetService",
						Params: `{"Id":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetServiceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetService(ctx, in.(*servicediscovery.GetServiceInput))
						},
					},
					scenario.Equals("$.Service.Description", "compat scenario service, updated"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceTagResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "TagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "TagResource",
			Params: `{"ResourceARN":{"$ref":"service.arn"},"Tags":[{"Key":"compat","Value":"scenario"}]}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.TagResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("service.arn")))
				in.Tags = []types.Tag{{Key: aws.String("compat"), Value: aws.String("scenario")}}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().TagResource(ctx, in.(*servicediscovery.TagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.ListContains(
					&scenario.Call{
						Op:     "ListTagsForResource",
						Params: `{"ResourceARN":{"$ref":"service.arn"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListTagsForResourceInput{}
							in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("service.arn")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
						},
					},
					"$.Tags",
					scenario.Where("$.Key", "compat"),
					scenario.Where("$.Value", "scenario"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceListTagsForResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "ListTagsForResource", scenario.Test{
		Call: scenario.Call{
			Op:     "ListTagsForResource",
			Params: `{"ResourceARN":{"$ref":"service.arn"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListTagsForResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("service.arn")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Tags",
				scenario.Where("$.Key", "compat"),
				scenario.Where("$.Value", "scenario"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceUntagResource(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "UntagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "UntagResource",
			Params: `{"ResourceARN":{"$ref":"service.arn"},"TagKeys":["compat"]}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.UntagResourceInput{}
				in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("service.arn")))
				in.TagKeys = []string{"compat"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UntagResource(ctx, in.(*servicediscovery.UntagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.AbsentFromList(
					&scenario.Call{
						Op:     "ListTagsForResource",
						Params: `{"ResourceARN":{"$ref":"service.arn"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListTagsForResourceInput{}
							in.ResourceARN = aws.String(scenario.Bind[string](b, "ResourceARN", scenario.Ref("service.arn")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListTagsForResource(ctx, in.(*servicediscovery.ListTagsForResourceInput))
						},
					},
					"$.Tags",
					scenario.Where("$.Key", "compat"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceUpdateServiceAttributes(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "UpdateServiceAttributes", scenario.Test{
		Call: scenario.Call{
			Op:     "UpdateServiceAttributes",
			Params: `{"Attributes":{"compat":"scenario"},"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.UpdateServiceAttributesInput{}
				in.Attributes = map[string]string{"compat": "scenario"}
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UpdateServiceAttributes(ctx, in.(*servicediscovery.UpdateServiceAttributesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetServiceAttributes",
						Params: `{"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetServiceAttributesInput{}
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetServiceAttributes(ctx, in.(*servicediscovery.GetServiceAttributesInput))
						},
					},
					scenario.Equals("$.ServiceAttributes.Attributes.compat", "scenario"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceGetServiceAttributes(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "GetServiceAttributes", scenario.Test{
		Call: scenario.Call{
			Op:     "GetServiceAttributes",
			Params: `{"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetServiceAttributesInput{}
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetServiceAttributes(ctx, in.(*servicediscovery.GetServiceAttributesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.ServiceAttributes.ServiceArn", scenario.Ref("service.arn")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceDeleteServiceAttributes(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "DeleteServiceAttributes", scenario.Test{
		Call: scenario.Call{
			Op:     "DeleteServiceAttributes",
			Params: `{"Attributes":["compat"],"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteServiceAttributesInput{}
				in.Attributes = []string{"compat"}
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteServiceAttributes(ctx, in.(*servicediscovery.DeleteServiceAttributesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetServiceAttributes",
						Params: `{"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetServiceAttributesInput{}
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetServiceAttributes(ctx, in.(*servicediscovery.GetServiceAttributesInput))
						},
					},
					scenario.Missing("$.ServiceAttributes.Attributes.compat"),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceListInstances(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "ListInstances", scenario.Test{
		Call: scenario.Call{
			Op:     "ListInstances",
			Params: `{"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListInstancesInput{}
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListInstances(ctx, in.(*servicediscovery.ListInstancesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.IsList("$.Instances"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceDiscoverInstances(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "DiscoverInstances", scenario.Test{
		Call: scenario.Call{
			Op:     "DiscoverInstances",
			Params: `{"NamespaceName":{"$name":"ns"},"ServiceName":{"$name":"svc"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DiscoverInstancesInput{}
				in.NamespaceName = aws.String(scenario.Bind[string](b, "NamespaceName", scenario.Name("ns")))
				in.ServiceName = aws.String(scenario.Bind[string](b, "ServiceName", scenario.Name("svc")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DiscoverInstances(ctx, in.(*servicediscovery.DiscoverInstancesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.IsList("$.Instances"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceListOperations(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "ListOperations", scenario.Test{
		Call: scenario.Call{
			Op:     "ListOperations",
			Params: `{"Filters":[{"Condition":"EQ","Name":"SERVICE_ID","Values":[{"$ref":"service.id"}]}]}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListOperationsInput{}
				in.Filters = []types.OperationFilter{
					{
						Condition: types.FilterCondition("EQ"),
						Name:      types.OperationFilterName("SERVICE_ID"),
						Values:    []string{scenario.Bind[string](b, "Filters", scenario.Ref("service.id"))},
					},
				}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListOperations(ctx, in.(*servicediscovery.ListOperationsInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.IsList("$.Operations"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceListServices(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "ListServices", scenario.Test{
		Call: scenario.Call{
			Op:     "ListServices",
			Params: `{}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListServicesInput{}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListServices(ctx, in.(*servicediscovery.ListServicesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Services",
				scenario.Where("$.Id", scenario.Ref("service.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenServiceDeleteService(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenService.RunTest(ctx, t, "DeleteService", scenario.Test{
		Call: scenario.Call{
			Op:     "DeleteService",
			Params: `{"Id":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteServiceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteService(ctx, in.(*servicediscovery.DeleteServiceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(15, 2000,
				scenario.AbsentByError(
					scenario.Call{
						Op:     "GetService",
						Params: `{"Id":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetServiceInput{}
							in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetService(ctx, in.(*servicediscovery.GetServiceInput))
						},
					},
					scenario.Error("ServiceNotFound", "ServiceNotFound"),
				),
			),
		},
	})
}

var groupServicediscoveryGenInstance = scenario.Group{Name: "servicediscovery-gen-instance", File: "compat/model/scenarios/servicediscovery.json"}

func (g *servicediscoveryScenarios) setupServicediscoveryGenInstance(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunSetup(ctx, t,
		scenario.Call{
			Op:     "CreateHttpNamespace",
			Params: `{"Description":"compat scenario namespace","Name":{"$name":"ns"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.CreateHttpNamespaceInput{}
				in.Description = aws.String("compat scenario namespace")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("ns")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateHttpNamespace(ctx, in.(*servicediscovery.CreateHttpNamespaceInput))
			},
			Export: map[string]string{
				"namespace.operationId": "$.OperationId",
			},
		},
		scenario.Call{
			Op:     "GetOperation",
			Params: `{"OperationId":{"$ref":"namespace.operationId"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetOperationInput{}
				in.OperationId = aws.String(scenario.Bind[string](b, "OperationId", scenario.Ref("namespace.operationId")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetOperation(ctx, in.(*servicediscovery.GetOperationInput))
			},
			Export: map[string]string{
				"namespace.id": "$.Operation.Targets.NAMESPACE",
			},
		},
		scenario.Call{
			Op:     "CreateService",
			Params: `{"Description":"compat scenario service","Name":{"$name":"svc"},"NamespaceId":{"$ref":"namespace.id"},"Type":"HTTP"}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.CreateServiceInput{}
				in.Description = aws.String("compat scenario service")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("svc")))
				in.NamespaceId = aws.String(scenario.Bind[string](b, "NamespaceId", scenario.Ref("namespace.id")))
				in.Type = types.ServiceTypeOption("HTTP")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateService(ctx, in.(*servicediscovery.CreateServiceInput))
			},
			Export: map[string]string{
				"service.arn": "$.Service.Arn",
				"service.id":  "$.Service.Id",
			},
		},
	)
}

func (g *servicediscoveryScenarios) teardownServicediscoveryGenInstance(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "DeregisterInstance",
			Params: `{"InstanceId":{"$ref":"instance.id"},"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeregisterInstanceInput{}
				in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Ref("instance.id")))
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeregisterInstance(ctx, in.(*servicediscovery.DeregisterInstanceInput))
			},
		},
		scenario.Call{
			Op:     "DeleteService",
			Params: `{"Id":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteServiceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteService(ctx, in.(*servicediscovery.DeleteServiceInput))
			},
		},
		scenario.Call{
			Op:     "DeleteNamespace",
			Params: `{"Id":{"$ref":"namespace.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeleteNamespaceInput{}
				in.Id = aws.String(scenario.Bind[string](b, "Id", scenario.Ref("namespace.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteNamespace(ctx, in.(*servicediscovery.DeleteNamespaceInput))
			},
		},
	)
}

func (g *servicediscoveryScenarios) testServicediscoveryGenInstanceRegisterInstance(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunTest(ctx, t, "RegisterInstance", scenario.Test{
		Call: scenario.Call{
			Op:     "RegisterInstance",
			Params: `{"Attributes":{"AWS_INSTANCE_IPV4":"203.0.113.10"},"InstanceId":{"$name":"i"},"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.RegisterInstanceInput{}
				in.Attributes = map[string]string{"AWS_INSTANCE_IPV4": "203.0.113.10"}
				in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Name("i")))
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().RegisterInstance(ctx, in.(*servicediscovery.RegisterInstanceInput))
			},
			Export: map[string]string{
				"instance.operationId": "$.OperationId",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.OperationId"),
			),
			scenario.Eventually(30, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetInstance",
						Params: `{"InstanceId":{"$name":"i"},"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetInstanceInput{}
							in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Name("i")))
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetInstance(ctx, in.(*servicediscovery.GetInstanceInput))
						},
						Export: map[string]string{
							"instance.id": "$.Instance.Id",
						},
					},
					scenario.NonEmpty("$.Instance.Id"),
				),
			),
			scenario.Eventually(30, 2000,
				scenario.Readback(
					scenario.Call{
						Op:     "GetInstance",
						Params: `{"InstanceId":{"$ref":"instance.id"},"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetInstanceInput{}
							in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Ref("instance.id")))
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetInstance(ctx, in.(*servicediscovery.GetInstanceInput))
						},
					},
					scenario.Equals("$.Instance.Id", scenario.Ref("instance.id")),
				),
			),
			scenario.Eventually(30, 2000,
				scenario.ListContains(
					&scenario.Call{
						Op:     "ListInstances",
						Params: `{"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.ListInstancesInput{}
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().ListInstances(ctx, in.(*servicediscovery.ListInstancesInput))
						},
					},
					"$.Instances",
					scenario.Where("$.Id", scenario.Ref("instance.id")),
				),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenInstanceGetInstance(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunTest(ctx, t, "GetInstance", scenario.Test{
		Call: scenario.Call{
			Op:     "GetInstance",
			Params: `{"InstanceId":{"$ref":"instance.id"},"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetInstanceInput{}
				in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Ref("instance.id")))
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetInstance(ctx, in.(*servicediscovery.GetInstanceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Instance.Id", scenario.Ref("instance.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenInstanceListInstances(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunTest(ctx, t, "ListInstances", scenario.Test{
		Call: scenario.Call{
			Op:     "ListInstances",
			Params: `{"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.ListInstancesInput{}
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListInstances(ctx, in.(*servicediscovery.ListInstancesInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Instances",
				scenario.Where("$.Id", scenario.Ref("instance.id")),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenInstanceDeregisterInstance(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenInstance.RunTest(ctx, t, "DeregisterInstance", scenario.Test{
		Call: scenario.Call{
			Op:     "DeregisterInstance",
			Params: `{"InstanceId":{"$ref":"instance.id"},"ServiceId":{"$ref":"service.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.DeregisterInstanceInput{}
				in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Ref("instance.id")))
				in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeregisterInstance(ctx, in.(*servicediscovery.DeregisterInstanceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Eventually(30, 2000,
				scenario.AbsentByError(
					scenario.Call{
						Op:     "GetInstance",
						Params: `{"InstanceId":{"$ref":"instance.id"},"ServiceId":{"$ref":"service.id"}}`,
						Build: func(b *scenario.Binder) any {
							in := &servicediscovery.GetInstanceInput{}
							in.InstanceId = aws.String(scenario.Bind[string](b, "InstanceId", scenario.Ref("instance.id")))
							in.ServiceId = aws.String(scenario.Bind[string](b, "ServiceId", scenario.Ref("service.id")))
							return in
						},
						Send: func(ctx context.Context, in any) (any, error) {
							return g.cl().GetInstance(ctx, in.(*servicediscovery.GetInstanceInput))
						},
					},
					scenario.Error("InstanceNotFound", "InstanceNotFound"),
				),
			),
		},
	})
}

var groupServicediscoveryGenProbe = scenario.Group{Name: "servicediscovery-gen-probe", File: "compat/model/scenarios/servicediscovery.json"}

func (g *servicediscoveryScenarios) setupServicediscoveryGenProbe(ctx context.Context, t *harness.TestContext) error {
	// No setup steps: an empty phase is a no-op, not a missing one.
	return groupServicediscoveryGenProbe.RunSetup(ctx, t)
}

func (g *servicediscoveryScenarios) teardownServicediscoveryGenProbe(ctx context.Context, t *harness.TestContext) error {
	// No teardown steps: an empty phase is a no-op, not a missing one.
	return groupServicediscoveryGenProbe.RunTeardown(ctx, t)
}

func (g *servicediscoveryScenarios) testServicediscoveryGenProbeGetInstancesHealthStatus(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenProbe.RunTest(ctx, t, "GetInstancesHealthStatus", scenario.Test{
		Call: scenario.Call{
			Op:     "GetInstancesHealthStatus",
			Params: `{"ServiceId":"srv-compatscenario00"}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetInstancesHealthStatusInput{}
				in.ServiceId = aws.String("srv-compatscenario00")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetInstancesHealthStatus(ctx, in.(*servicediscovery.GetInstancesHealthStatusInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.Status"),
			),
		},
	})
}

func (g *servicediscoveryScenarios) testServicediscoveryGenProbeGetOperation(ctx context.Context, t *harness.TestContext) error {
	return groupServicediscoveryGenProbe.RunTest(ctx, t, "GetOperation", scenario.Test{
		Call: scenario.Call{
			Op:     "GetOperation",
			Params: `{"OperationId":"compatscenariooperationnotfound0-00000000"}`,
			Build: func(b *scenario.Binder) any {
				in := &servicediscovery.GetOperationInput{}
				in.OperationId = aws.String("compatscenariooperationnotfound0-00000000")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetOperation(ctx, in.(*servicediscovery.GetOperationInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.Operation"),
			),
		},
	})
}
