//go:build dev

package router

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"sort"
	"strings"
	"testing"

	"go.uber.org/zap"

	"github.com/overcast-sh/overcast/internal/awsapi"
	"github.com/overcast-sh/overcast/internal/clock"
	"github.com/overcast-sh/overcast/internal/config"
	"github.com/overcast-sh/overcast/internal/state"
)

// TestDeclaredProtocols_areDispatchedSymmetrically is #864's second
// enforcement point: Protocols is a *set*, and an operation has to be
// reachable over every protocol its service actually speaks.
//
// #794 was three CloudWatch tag operations present in the Query dispatch map
// and absent from the JSON one, so `aws cloudwatch list-tags-for-resource`
// failed while the identical call over Query worked. The fix was a test inside
// the cloudwatch package comparing its own two tables. That catches the next
// CloudWatch asymmetry and no other service's, and it compares one
// implementation against another rather than either against AWS.
//
// Until this test, Operation.Protocols had no consumer anywhere outside
// awsapi's own tests: generated by awsmodelgen, asserted by two lines, read by
// nothing.
//
// # Why asymmetry rather than absolute coverage
//
// Requiring every modeled protocol would fail honestly-scoped services en
// masse — a model may declare rpcv2Cbor for a service Overcast serves only
// over JSON, and #864 is explicit that a gate must not over-claim. So the
// question asked here is narrower and answers exactly the #794 shape: given a
// service that demonstrably speaks two protocols, because some of its
// operations are reachable over each, is *this* operation reachable over both?
// That needs no per-service configuration and cannot drift out of date,
// because the calibration is the emulator's own behaviour.
//
// # rpcv2Cbor (#1228)
//
// All three protocols the manifest can declare for a dispatched operation are
// probed, including rpcv2Cbor: the probe sends a well-formed rpc-v2-cbor
// request (an empty CBOR map is a valid body for every generated request
// struct, whose members are all optional to the decoder) to the Smithy RPC v2
// URI the router already dispatches on, and the same 501/503 "nobody answers
// this" signal writeNotImplemented always produces — regardless of wire
// protocol — is what "not reached" means for it too.
//
// CloudWatch is the only dispatched service the pinned models declare
// rpcv2Cbor for, and when #1228 first ran this probe it answered none of its
// fifteen declared operations over it: the smithyRPCService wiring for it had
// no ProtocolService (no Operations()/SupportedProtocols()), so CBOR was never
// claimed at all, not merely dropped for a few operations. That was uniform
// non-coverage rather than the #794 shape this test's asymmetry definition
// exists to catch (a protocol the service demonstrably speaks somewhere,
// withheld from one operation) — spoken["cloudwatch"][cbor] never became true,
// so nothing was flagged, and the gap was recorded in prose here and in
// docs/plans/manifest-enforcement.md rather than in protocolAsymmetries.
//
// #1280 closed it: CloudWatch registers a ProtocolService whose typed
// operations share the awsJson handlers' cores, so all fifteen answer over
// rpcv2Cbor and this probe exercises the service for real. The consequence
// worth knowing is that spoken["cloudwatch"][cbor] is now true, which means
// this gate has teeth for CloudWatch it did not have before: an operation
// added to the Query and JSON tables without a typed binding is a genuine
// asymmetry from here on, and fails.
func TestDeclaredProtocols_areDispatchedSymmetrically(t *testing.T) {
	// Given: the running emulator, and every dispatched capability's modeled
	// protocol set.
	srv := protocolProbeServer(t)
	reach := map[string]map[wireProtocol]bool{}
	spoken := map[string]map[wireProtocol]bool{}

	// When: each operation is probed over every protocol its model declares
	// and this emulator can address.
	for _, cap := range dispatchedCapabilities() {
		for _, op := range awsapi.Operations(cap.Service, modeledOperationName(cap)) {
			for _, probe := range protocolProbes(op) {
				if reach[cap.Service+"/"+cap.Operation] == nil {
					reach[cap.Service+"/"+cap.Operation] = map[wireProtocol]bool{}
				}
				answered := srv.answers(t, probe)
				reach[cap.Service+"/"+cap.Operation][probe.protocol] = answered
				if !answered {
					continue
				}
				if spoken[cap.Service] == nil {
					spoken[cap.Service] = map[wireProtocol]bool{}
				}
				spoken[cap.Service][probe.protocol] = true
			}
		}
	}

	// Then: no operation is reachable over one of its service's protocols and
	// unreachable over another.
	var asymmetric []string
	for _, key := range sortedKeys(reach) {
		service := strings.SplitN(key, "/", 2)[0]
		var missing []string
		for protocol, answered := range reach[key] {
			if !answered && spoken[service][protocol] {
				missing = append(missing, string(protocol))
			}
		}
		if len(missing) == 0 {
			continue
		}
		sort.Strings(missing)
		asymmetric = append(asymmetric, fmt.Sprintf("%s: unreachable over %s, which %s answers for its other operations",
			key, strings.Join(missing, " and "), service))
	}
	sort.Strings(asymmetric)

	assertProtocolAsymmetry(t, asymmetric)
}

// wireProtocol names a protocol this test can put a request on the wire in.
type wireProtocol string

const (
	protocolTarget    wireProtocol = "awsJson (X-Amz-Target)"
	protocolQuery     wireProtocol = "awsQuery (Action=)"
	protocolRPCV2CBOR wireProtocol = "rpcv2Cbor (Smithy-Protocol: rpc-v2-cbor)"
)

type protocolProbe struct {
	protocol wireProtocol
	target   string
	action   string
	version  string
	// serviceShape and operation address a Smithy RPC v2 request, which names
	// the service and operation outright in the URI (/service/{serviceShape}
	// /operation/{operation}) rather than in a header or form field — see the
	// protocolRPCV2CBOR case in (*probeServer).answers.
	serviceShape string
	operation    string
}

// protocolProbes returns one probe per protocol the operation's service
// declares that this test can address.
func protocolProbes(op awsapi.Operation) []protocolProbe {
	var probes []protocolProbe
	if op.TargetPrefix != "" && op.Protocols&(awsapi.ProtocolsAWSJSON10|awsapi.ProtocolsAWSJSON11) != 0 {
		probes = append(probes, protocolProbe{protocol: protocolTarget, target: op.TargetPrefix + op.Name})
	}
	if op.Protocols&awsapi.ProtocolsAWSQuery != 0 && op.APIVersion != "" {
		probes = append(probes, protocolProbe{protocol: protocolQuery, action: op.Name, version: op.APIVersion})
	}
	if op.Protocols&awsapi.ProtocolsRPCV2CBOR != 0 && op.ServiceShape != "" {
		probes = append(probes, protocolProbe{protocol: protocolRPCV2CBOR, serviceShape: op.ServiceShape, operation: op.Name})
	}
	return probes
}

// TestProtocolProbes_rpcv2CBOR pins the #1228 addition against the unit that
// decides whether a probe is emitted at all, ahead of the far more expensive
// whole-router walk in TestDeclaredProtocols_areDispatchedSymmetrically.
func TestProtocolProbes_rpcv2CBOR(t *testing.T) {
	declared := awsapi.Operation{
		Service: "cloudwatch", ServiceShape: "GraniteServiceVersion20100801",
		Name: "ListMetrics", Protocols: awsapi.ProtocolsRPCV2CBOR,
	}
	probes := protocolProbes(declared)
	if len(probes) != 1 {
		t.Fatalf("declared rpcv2Cbor operation: got %d probes, want 1: %+v", len(probes), probes)
	}
	if probes[0].protocol != protocolRPCV2CBOR {
		t.Errorf("protocol = %v, want %v", probes[0].protocol, protocolRPCV2CBOR)
	}
	if probes[0].serviceShape != declared.ServiceShape || probes[0].operation != declared.Name {
		t.Errorf("probe = %+v, want serviceShape %q operation %q", probes[0], declared.ServiceShape, declared.Name)
	}

	// An operation with no ServiceShape cannot be addressed by the RPC v2 URI
	// at all — the model itself never leaves this combination declared, but
	// the probe builder must not emit an unaddressable request if it somehow
	// were.
	noShape := declared
	noShape.ServiceShape = ""
	if probes := protocolProbes(noShape); len(probes) != 0 {
		t.Errorf("no ServiceShape: got %d probes, want 0: %+v", len(probes), probes)
	}

	// An operation that does not declare rpcv2Cbor at all gets no probe for it.
	notDeclared := declared
	notDeclared.Protocols = awsapi.ProtocolsAWSJSON10
	for _, probe := range protocolProbes(notDeclared) {
		if probe.protocol == protocolRPCV2CBOR {
			t.Errorf("operation without ProtocolsRPCV2CBOR got a CBOR probe: %+v", probe)
		}
	}
}

type probeServer struct{ url string }

func protocolProbeServer(t *testing.T) *probeServer {
	t.Helper()

	cfg := &config.Config{
		Host:      "127.0.0.1",
		Port:      0,
		Region:    "us-east-1",
		AccountID: "000000000000",
		State:     config.StateBackendMemory,
		LogLevel:  "error",
		DataDir:   t.TempDir(),
	}
	handler, preShutdown, cleanup, _ := New(cfg, state.NewMemoryStore(), zap.NewNop(), clock.New())
	t.Cleanup(func() {
		preShutdown()
		cleanup(t.Context())
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	return &probeServer{url: srv.URL}
}

// rpcv2CBOREmptyMap is the two-byte CBOR encoding of an empty definite-length
// map (major type 5, 0 pairs) — the whole of what the probe needs to send.
// The probe asks only whether the operation was dispatched, not whether the
// body decodes into anything real, so an empty map (which every generated
// request struct accepts — every member is optional to the decoder) is enough
// to reach the handler exactly as an empty JSON "{}" is for the other two
// probes.
var rpcv2CBOREmptyMap = []byte{0xa0}

// answers reports whether some handler took the operation.
//
// It asks only whether the request was dispatched, not whether it succeeded: a
// probe sends an empty body, so a validation error is the *expected* answer
// from a working handler and means the operation was reached. Only the router's
// own "nobody serves this" replies count as unreachable — 501 from the
// generated-registry fallback, and the 400 UnknownOperationException a service
// returns from the default arm of its own dispatch. The CBOR probe shares
// that same 501/503 signal — writeNotImplemented always answers ErrNotImplemented
// as HTTP 501 regardless of wire protocol — so no CBOR-specific status check is
// needed; the body-contains check is simply moot for it, since CBOR never
// spells UnknownOperationException as that literal JSON shape.
func (s *probeServer) answers(t *testing.T, probe protocolProbe) bool {
	t.Helper()

	var request *http.Request
	var err error
	switch probe.protocol {
	case protocolTarget:
		request, err = http.NewRequest(http.MethodPost, s.url+"/", strings.NewReader("{}"))
		if err == nil {
			request.Header.Set("Content-Type", "application/x-amz-json-1.0")
			request.Header.Set("X-Amz-Target", probe.target)
		}
	case protocolQuery:
		body := "Action=" + probe.action + "&Version=" + probe.version
		request, err = http.NewRequest(http.MethodPost, s.url+"/", strings.NewReader(body))
		if err == nil {
			request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		}
	case protocolRPCV2CBOR:
		// The Smithy RPC v2 URI names the service and operation outright; the
		// Smithy-Protocol header is what tells the router this is RPC v2
		// rather than an S3 object read of "operation/<Op>" in a bucket named
		// after the service — see smithyRPCDispatch.
		uri := "/service/" + probe.serviceShape + "/operation/" + probe.operation
		request, err = http.NewRequest(http.MethodPost, s.url+uri, bytes.NewReader(rpcv2CBOREmptyMap))
		if err == nil {
			request.Header.Set("Content-Type", "application/cbor")
			request.Header.Set("Smithy-Protocol", "rpc-v2-cbor")
		}
	}
	if err != nil {
		t.Fatalf("building %s probe: %v", probe.protocol, err)
	}

	response, err := http.DefaultClient.Do(request)
	if err != nil {
		t.Fatalf("%s probe: %v", probe.protocol, err)
	}
	// Drain before closing so the transport reuses the connection. This loop
	// makes thousands of requests, and a close with an unread body tears the
	// connection down — enough sockets in TIME_WAIT to exhaust the Windows
	// ephemeral port range and fail every later dial in the package.
	body, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
	response.Body.Close()

	if response.StatusCode == http.StatusNotImplemented || response.StatusCode == http.StatusServiceUnavailable {
		return false
	}
	return !strings.Contains(string(body), "UnknownOperationException")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
