//go:build dev

package router

import (
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"sort"
	"strings"
	"testing"

	"go.uber.org/zap"

	"github.com/Neaox/overcast/internal/awsapi"
	"github.com/Neaox/overcast/internal/clock"
	"github.com/Neaox/overcast/internal/config"
	"github.com/Neaox/overcast/internal/state"
)

// TestDeclaredProtocols_areDispatchedSymmetrically is #864's second
// enforcement point: Protocols is a *set*, and an operation has to be
// reachable over every protocol its service actually speaks.
//
// #794 was three CloudWatch tag operations present in the Query dispatch map
// and absent from the JSON one, so `aws cloudwatch list-tags-for-resource`
// failed while the identical call over Query worked. The fix was a test inside
// the cloudwatch package comparing its own two tables. That catches the next
// CloudWatch asymmetry and no other service's, and it compares one
// implementation against another rather than either against AWS.
//
// Until this test, Operation.Protocols had no consumer anywhere outside
// awsapi's own tests: generated by awsmodelgen, asserted by two lines, read by
// nothing.
//
// # Why asymmetry rather than absolute coverage
//
// Requiring every modeled protocol would fail honestly-scoped services en
// masse — a model may declare rpcv2Cbor for a service Overcast serves only
// over JSON, and #864 is explicit that a gate must not over-claim. So the
// question asked here is narrower and answers exactly the #794 shape: given a
// service that demonstrably speaks two protocols, because some of its
// operations are reachable over each, is *this* operation reachable over both?
// That needs no per-service configuration and cannot drift out of date,
// because the calibration is the emulator's own behaviour.
func TestDeclaredProtocols_areDispatchedSymmetrically(t *testing.T) {
	// Given: the running emulator, and every dispatched capability's modeled
	// protocol set.
	srv := protocolProbeServer(t)
	reach := map[string]map[wireProtocol]bool{}
	spoken := map[string]map[wireProtocol]bool{}

	// When: each operation is probed over every protocol its model declares
	// and this emulator can address.
	for _, cap := range dispatchedCapabilities() {
		for _, op := range awsapi.Operations(cap.Service, modeledOperationName(cap)) {
			for _, probe := range protocolProbes(op) {
				if reach[cap.Service+"/"+cap.Operation] == nil {
					reach[cap.Service+"/"+cap.Operation] = map[wireProtocol]bool{}
				}
				answered := srv.answers(t, probe)
				reach[cap.Service+"/"+cap.Operation][probe.protocol] = answered
				if !answered {
					continue
				}
				if spoken[cap.Service] == nil {
					spoken[cap.Service] = map[wireProtocol]bool{}
				}
				spoken[cap.Service][probe.protocol] = true
			}
		}
	}

	// Then: no operation is reachable over one of its service's protocols and
	// unreachable over another.
	var asymmetric []string
	for _, key := range sortedKeys(reach) {
		service := strings.SplitN(key, "/", 2)[0]
		var missing []string
		for protocol, answered := range reach[key] {
			if !answered && spoken[service][protocol] {
				missing = append(missing, string(protocol))
			}
		}
		if len(missing) == 0 {
			continue
		}
		sort.Strings(missing)
		asymmetric = append(asymmetric, fmt.Sprintf("%s: unreachable over %s, which %s answers for its other operations",
			key, strings.Join(missing, " and "), service))
	}
	sort.Strings(asymmetric)

	assertProtocolAsymmetry(t, asymmetric)
}

// wireProtocol names a protocol this test can put a request on the wire in.
// rpcv2Cbor is modeled for several services and is deliberately absent: it
// needs a CBOR encoder, and an operation Overcast serves over neither JSON nor
// Query is already reported by the binding gate.
type wireProtocol string

const (
	protocolTarget wireProtocol = "awsJson (X-Amz-Target)"
	protocolQuery  wireProtocol = "awsQuery (Action=)"
)

type protocolProbe struct {
	protocol wireProtocol
	target   string
	action   string
	version  string
}

// protocolProbes returns one probe per protocol the operation's service
// declares that this test can address.
func protocolProbes(op awsapi.Operation) []protocolProbe {
	var probes []protocolProbe
	if op.TargetPrefix != "" && op.Protocols&(awsapi.ProtocolsAWSJSON10|awsapi.ProtocolsAWSJSON11) != 0 {
		probes = append(probes, protocolProbe{protocol: protocolTarget, target: op.TargetPrefix + op.Name})
	}
	if op.Protocols&awsapi.ProtocolsAWSQuery != 0 && op.APIVersion != "" {
		probes = append(probes, protocolProbe{protocol: protocolQuery, action: op.Name, version: op.APIVersion})
	}
	return probes
}

type probeServer struct{ url string }

func protocolProbeServer(t *testing.T) *probeServer {
	t.Helper()

	cfg := &config.Config{
		Host:      "127.0.0.1",
		Port:      0,
		Region:    "us-east-1",
		AccountID: "000000000000",
		State:     config.StateBackendMemory,
		LogLevel:  "error",
		DataDir:   t.TempDir(),
	}
	handler, preShutdown, cleanup, _ := New(cfg, state.NewMemoryStore(), zap.NewNop(), clock.New())
	t.Cleanup(func() {
		preShutdown()
		cleanup(t.Context())
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	return &probeServer{url: srv.URL}
}

// answers reports whether some handler took the operation.
//
// It asks only whether the request was dispatched, not whether it succeeded: a
// probe sends an empty body, so a validation error is the *expected* answer
// from a working handler and means the operation was reached. Only the router's
// own "nobody serves this" replies count as unreachable — 501 from the
// generated-registry fallback, and the 400 UnknownOperationException a service
// returns from the default arm of its own dispatch.
func (s *probeServer) answers(t *testing.T, probe protocolProbe) bool {
	t.Helper()

	var request *http.Request
	var err error
	switch probe.protocol {
	case protocolTarget:
		request, err = http.NewRequest(http.MethodPost, s.url+"/", strings.NewReader("{}"))
		if err == nil {
			request.Header.Set("Content-Type", "application/x-amz-json-1.0")
			request.Header.Set("X-Amz-Target", probe.target)
		}
	case protocolQuery:
		body := "Action=" + probe.action + "&Version=" + probe.version
		request, err = http.NewRequest(http.MethodPost, s.url+"/", strings.NewReader(body))
		if err == nil {
			request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		}
	}
	if err != nil {
		t.Fatalf("building %s probe: %v", probe.protocol, err)
	}

	response, err := http.DefaultClient.Do(request)
	if err != nil {
		t.Fatalf("%s probe: %v", probe.protocol, err)
	}
	// Drain before closing so the transport reuses the connection. This loop
	// makes thousands of requests, and a close with an unread body tears the
	// connection down — enough sockets in TIME_WAIT to exhaust the Windows
	// ephemeral port range and fail every later dial in the package.
	body, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
	response.Body.Close()

	if response.StatusCode == http.StatusNotImplemented || response.StatusCode == http.StatusServiceUnavailable {
		return false
	}
	return !strings.Contains(string(body), "UnknownOperationException")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
